### ISSUE TITLE
Дубликаты форм

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#104]
(перенос из http://code.google.com/p/opencorpora/issues/detail?id=418), от @bzaar

"Некоторые статьи имеют формы-дубликаты - разные формы, которым приписаны одни и те же граммемы.  В некоторых случаях это допустимо (как обезьяночеловеки и обезьянолюди), в других - явные ошибки (проорал - проору и проорю), в третьих статьи нужно разделить (пропуски и пропуска).  См. приложенный файл."

Файл: https://yadi.sk/i/ljJctKl5bgenV

**Comment by svbichineva** [comment]
если мы, например, из 1-го слова 'зуб' сделаем два с разницей только в формах мн числа (зубы vs зубья), то когда размечающий встретит слово зуб, он не сможет выбрать из двух лемм на основе морфологии. Сохраняю формы-дубликаты до того, как мы дойдем до семантики
