### ISSUE TITLE
Автоматический поиск примеров для пулов

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#106]
Для типов пулов, у которых есть сложость и инструкция, искать примеры автоматически с некоторой регулярностью. Варианты регулярности (что проще сделать):

- через неделю (или месяц) после того, как был опубликован последний пул этого типа
- если остаток от деления номера типа на номер дня недели (номер дня в месяце) равен нулю ;)

И сразу автоматически их публиковать, если найдутся.

**Comment by grandsbor** [comment]
А если нет инструкции - что, правда не искать?

**Comment by vbocharov** [comment]
Давай так: если нет инструкции, то не генерировать пулы из найденного. Просто оставлять найденные примеры.

**Comment by grandsbor** [comment]
Первая часть сделана и выкачена: http://opencorpora.org/pools.php?type=1. Это автопоиск, автопубликация скоро тоже будет.

**Comment by akmetainfo** [comment]
А как же "новые пулы разбивать по 50"? Оставили по 200, верно?

**Comment by grandsbor** [comment]
Там настраивается.

**Comment by grandsbor** [comment]
Пулы, которые будет публиковать робот, будут размером по 50 заданий.

**Comment by grandsbor** [comment]
Вторая часть [выехала](http://opencorpora.org/pools.php?type=1), но публикация по крону пока не включена.
Зеленым цветом, соответственно, подсвечены типы, публикацией которых занимается робот.

**Comment by grandsbor** [comment]
Кстати, о регулярности: вроде бы нет никаких проблем с тем, чтобы производить полный поиск и публикацию ежедневно. Но я пока поставил поиск 10 (самых устаревших) типов в сутки.

**Comment by akmetainfo** [comment]
А почему именительный/винительный ничего не нашлось пока? Их будет ещё?

**Comment by grandsbor** [comment]
Если там написано "никогда", значит, ещё не запускалось ни разу для этого
типа.

**Comment by vbocharov** [comment]
Клёво очень. Когда планируешь включать публикацию по крону?

**Comment by grandsbor** [comment]
Да хоть прямщас. Вообще планировал завтра показать тебе, после чего
включить :)
Le 1 juil. 2015 12:43 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by vbocharov** [comment]
Пусть хулиганит. К утру посмотрим, что натворит ;)

**Comment by grandsbor** [comment]
Вообще тебе проще будет включить, а то я без ноутбука

sudo su grand
crontab /corpus/scripts/conf/crontab.list
Le 1 juil. 2015 12:54 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by vbocharov** [comment]
ага. Сделал.

**Comment by vbocharov** [comment]
http://opencorpora.org/pools.php?type=1
теперь это отличный список типов заданий, у которых нет инструкции.
@svbichineva , @named-entity , посмотрите, пожалуйста.

**Comment by grandsbor** [comment]
За ночь порядка 500 пулов опубликовалось (по 50).
Le 1 juil. 2015 9:04 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by named-entity** [comment]
Не знаю, в чем тут проблема, но
http://opencorpora.org/pools.php?act=candidates&pool_type=34 и
http://opencorpora.org/pools.php?act=candidates&pool_type=32
выдают одинаковые задания.

**Comment by akmetainfo** [comment]
Любопытно будет попробовать промодерировать короткий пул на 50 примеров. Сижу, помогаю закрыться быстрее тому типу, который уже проверял.;) Мне кажется, там вообще нужды в фильтрах не будет -- пул практически как на ладони.
