### ISSUE TITLE
Выделение пулов, которые нужно размечать в первую очередь

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#107]
Пулы: существительное и прилагательное им/вн и рд/вн

Выделение: картинка слева? какая?

**Comment by grandsbor** [comment]
Тупо: http://opencorpora.org/tasks.php

**Comment by grandsbor** [comment]
Сделал довольно порнографически, кто умеет css - сделайте по-нормальному :)
