### ISSUE TITLE
Перевести текст настройки (NE)

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#121]
![2014-12-02 0 26 05](https://cloud.githubusercontent.com/assets/1223831/5253617/a88f9398-79b9-11e4-9c85-469167c52964.png)

**Comment by akmetainfo** [comment]
Самый очевидный вариант перевода - "Использовать быстрый режим в разметке именованных сущностей", также поскольку это режим "разметка кликом/выделением" уместно перевести как "Использовать разметку выделением для разметки именованных сущностей"
Id записи в sql-базе - 5 таблицы user_options (на текущий момент за рамками версионного контроля, см. https://github.com/OpenCorpora/opencorpora/issues/137 )

**Comment by grandsbor** [comment]
Кстати, это ведь случилось
