### ISSUE TITLE
Добавить на локальную вики кнопку "ПримерЗадания"

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#124]
Чисто для удобства работы. Фактически, это самый используемый шаблон на вики.
Это начало кнопки:
{{ПримерЗадания|
Это - окончание:
|}}

Самый простой способ -- правка includes/EditPage.php (в районе $toolarray = array( находятся все системные кнопки), есть и более правильные способы ( http://www.mediawiki.org/wiki/Manual:Custom_edit_buttons )

**Comment by grandsbor** [comment]
[Сделал](http://opencorpora.org/w/index.php?title=MediaWiki:Common.js&curid=289&diff=44446&oldid=44427)

**Comment by akmetainfo** [comment]
Попроовал, работает. То, что надо! Ждите в будущем много новых инструкций! )

**Comment by madfriend** [comment]
>imageFile: '//upload.wikimedia.org/wikipedia/commons/thumb/4/49/Grammar_Nazi_Icon_Text_Bcg.svg/200px-Grammar_Nazi_Icon_Text_Bcg.svg.png',

это прекрасно :smiley:
