### ISSUE TITLE
Дампы базы данных

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#13]
Есть идея публиковать раз в неделю / N дней дамп базы данных для тех, кто хочет развернуть сайт локально. Понятное дело, что в дампе не должно быть конфиденциальных данных (таблица с пользователями).

**Comment by akmetainfo** [comment]
up

**Comment by grandsbor** [comment]
Так а у кого есть идеи, как это нормально сделать? (В смысле - вычистить пароли/емейлы)

**Comment by akmetainfo** [comment]
Лично мне пока приходит в голову пока только достаточно костыльный, но рабочий вариант.
Делаем sh-скрипт из четырёх шагов.
1. Шаг первый. Запускается sql-скрипт, который создаст таблицу user1 и таблицу user_token1, при этом некоторые поля СРАЗУ будут заполняться пустыми значениями.
2. Шаг два. Запускается mysqladmin c параметром skip-tables (пропускаются две таблицы: пользователи и токены). Создаётся обычный SQL-бэкап (не надо XML)
3. Шаг три. В полученно дампе делается замена текста `user_token1` на `user_token`
4. Шаг четыре. Удаляются временные таблицы user1 и user_token1.

Этот вариант у меня родился, пока я читал список параметров mysqldump на предмет чего-то типа skip-fields.
Гугление подсказывает ещё один вариант: [select outfile](http://dba.stackexchange.com/questions/34887/mysqldump-tables-excluding-some-fields), в принципе, ничего не мешает каждую таблицу базы данных перечислить и в отдельный файл закинуть (а потом в архив кинуть), но я не уверен, что этот способ менее костыльный.
Чем-то типа:
````
#!/bin/bash
MUSER="$1"
MPASS="$2"
MDB="$3"
 
# Detect paths
MYSQL=$(which mysql)
AWK=$(which awk)
GREP=$(which grep)
 
if [ $# -ne 3 ]
then
	echo "Usage: $0 {MySQL-User-Name} {MySQL-User-Password} {MySQL-Database-Name}"
	echo "Drops all tables from a MySQL"
	exit 1
fi
 
TABLES=$($MYSQL -u $MUSER -p$MPASS $MDB -e 'show tables' | $AWK '{ print $1}' | $GREP -v '^Tables' )
 
for t in $TABLES
do
	#echo "Deleting $t table from $MDB database..."
	#$MYSQL -u $MUSER -p$MPASS $MDB -e "drop table $t"
done
````
Надо в общем, подумать, как правильно сделать.

**Comment by madfriend** [comment]
Если бы `mysqldump` умел экспортировать в формате `INSERT INTO ... SET FIELD=VALUE, FIELD=VALUE, ...`, я бы предложил дампить таблицу отдельно, регуляркой заменять данные и потом приклеивать к общему дампу. Но, к сожалению, у меня не получилось его заставить так дампить (он всегда использует `VALUES(...)`, а там регуляркой опасно пользоваться).

**Comment by akmetainfo** [comment]
Можно вообще скриптом делать копию рабочей базы corpora -> corpora_backup, занулять всё, что необходимо, бэкапить как есть, чистить базу до следующего запуска. Или, держать постоянно включенной.
Лично я склоняюсь к варианту create table `user_backup` as select field1, field2, null as field3б field4... - по двум причинам:
1. при каких-либо потенциальных сбоях всегда будет соблюдаться прайваси: таблица либо создаётся уже занулённой, либо не создаётся вообще. Это очень важно.
2. меньше всего придётся делать ресурсоёмких замен (никаких регулярок)
Самый значительный минус который я вижу: нужно будет поддерживать актуальность Select'а (если вдруг будем расширять список полей на таблицах)

**Comment by akmetainfo** [comment]
UP. Для некоторых задач мне нужна занулённая копия рабочей базы, а #13 опять месяц без движения.

Давайте попробуем понять, в какой мы точке и куда двигаемся. Выше есть несколько вариантов скрипта/решения задачи: можно делать пулл-риквест по любому варианту ("лишь бы работал") или мы всё-таки выберем какой-то из вариантов и будем ожидать пулл-риквест только по выбранному варианту?

Я готов  написать два варианта скриптов:
а) создание рядом с продакшн базой второй базы (занулённой), которая и будет бэкапиться
б) создание копий нужных таблиц (при создании уже занулённых), затем обычный бэкап с --ignore-table и косметические замены в файле бэкапа

**Comment by grandsbor** [comment]
Копия всей базы потенциально плоха тем, что это требует в два раза больше места, а база растёт. Так что я бы выбрал только копии таблиц

**Comment by akmetainfo** [comment]
Нда. Скачал первый дамп, надо было жать в gz: 1601 Мб (несжатый) -> 159 Мб (сжатый файл).
Ещё надо куда-нибудь ссылку дать на файл. И сразу договориться, что чаще, чем раз в неделю не стоит такой бэкап делать.

**Comment by grandsbor** [comment]
Это уже моя забота :)

**Comment by grandsbor** [comment]
Сделал ссылочку со страницы "Скачать" (внизу). Дамп будем делать раз в неделю.
