### ISSUE TITLE
После создания первого пользователя падает при попытке аутентификации

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#132]
Создал чистую базу (phinx), зарегистрировал первого пользователя.

Как только пытаешься залогиниться им -- тут же прилетает эксепшн из функции init_session

    if (!$options || !$permissions)
        throw new Exception();
При этом и options и permission если нет нужных записей в таблицах -- они их тут же вставляют на лету. В таблице user_permission записи есть, в таблице user_options -- записей нет, таблица полностью пуста.

На текущий момент я выкрутился, заменив условие с || на &&, но давайте поймём как правильно починить.

Место поломки -- функция get_user_options, из которой прилетел ответ.
Почему прилетел пустой? Функция регистрации пользователя (user_register) создаёт записи в таблицах users и user_permisiion, ничего в user_option не создаёт.
Поэтому чисто по логике в пустой базе будет падать.

Вариант замены условия с или на и -- не смотрел в других местах, поэтому полагаю, что это не самый правильный вариант решения проблемы.

Второй вариант, который вижу -- при создании нового пользователя сразу вставлять ему запись в таблицу user_options.

**Comment by madfriend** [comment]
На мой взгляд, эту проблему нужно решать вставкой записи в таблицу user_options при создании нового пользователя.

**Comment by akmetainfo** [comment]
Я тоже изначально писал про то, что нужно делать вставку (см. описание про второй вариант) в таблицу настроек, но у себя локально я изменил тип условия с "или" на "и".

Данный баг ведь почему возник? Потому что вставка настроек при создании пользователей УЖЕ есть. Посмотрите: любой вызов [функции логина пользователя](https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_users.php#L67) ведёт к [вызову get_user_options](https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_users.php#L330) -- и там происходит вставка значений настроек.

Почему не отрабатывала вставка настроек? Потому что в дистрибутиве не было значений настроек в таблице user_options (см. https://github.com/OpenCorpora/opencorpora/issues/137). Поэтому на продакшн-среде никто и не догадывался о подобном баге.

Сейчас когда https://github.com/OpenCorpora/opencorpora/issues/137 закрыт -- можно смело закрывать и данный вопрос. А тот коммит, который я предлагал (замена "или" на "и") нужно грохнуть. Почему? Потому что я считаю, что более корректно, если к моменту init_session будут собраны все нужные для записи в $_SESSION. Поэтому если *ИЛИ* $options отсутствует *ИЛИ* $permissions отсутствует -- нужно выкидывать исключение, этот вариант более правильнее.

**Comment by madfriend** [comment]
Правильно понимаю, что сейчас все работает корректно, по второму варианту (записи в user_options_values появляются)? Тогда тикет закрываем.

**Comment by akmetainfo** [comment]
Да, правильно понимаете. Закрываем: ненужные ветки и pull request'ы я уже удалил.
