### ISSUE TITLE
Исключить код яндекс:метрики из исходников

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#133]
Код templates/footer.tpl содержит код яндекс:метрики с продакшн-сервера.
Как и локальная вики -- коду не место в репозитории, кому нужно будет развернуть с нуля -- поставит себе свой счётчик, если вообще нужно будет.

**Comment by akmetainfo** [comment]
https://github.com/akmetainfo/opencorpora/compare/akmetainfo:master...YaMetrikaSettings

Как-то в общем, я себе представляю (не стал пока оформлять пулл реквест в основной репозиторий, у себя ветку сделал).

Параметр помещён в секцию web конфига, код метрики вынес в отдельный файл (периодически яндекс меняет код метрики)

NB После коммита и обновления на продакшен нужно добавить в "боевой" конфиг-файл строку:
yandex_metrika_counter_id = 9552538

**Comment by grandsbor** [comment]
Вроде нормально, оформляйте как пулл-реквест

**Comment by grandsbor** [comment]
Всем спасибо, выкатилось
