### ISSUE TITLE
Невозможно добавить текст в пустую книгу: некорректно работает бекенд счётчика абзацев

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#134]
На add.php?act=check счётчик абзацев висит в положении "загрузка" в случае, если книга только что добавлена и в ней нет ни одного абзаца. (По-правильному должно писать "Нет ни одного абзаца")

Steps to reproduce: Обнаружено на чистом рабочем окружении: нет ни одной записи в таблице paragraphs (при этом books и sources заполнены правильно, видно даже визуально: в селекторах книга/раздел всё выбирается правильно)

При этом в /js/main.js фунукция UpdateLastParInfo зависает на на $p.html('<i>Загрузка...</i>'); и не может дождаться ответа от бэкенда (/ajax/lastpar.php)

Проблема устраняется заменой в /ajax/lastpar.php фрагмента:
````php
$par_id = $r['par_id'];
````
на 
````php
$par_id = $r['par_id'] ?: 0;
````

Это -- минимально необходимый фикс, также нужно понять, а не должен ли вставляться в paragraphs элемент (как это видимо принято в других местах проекта), а то может я какой-то шаг пропустил при создании первого текста.

**Comment by akmetainfo** [comment]
Возможно, лучше оставить такую фичу. Кушать не просит, поддержки никакой не требует, давно отлажена, а начнёшь выпиливать -- это как и любой рефакторинг потенциально может привести к возникновению новых глюков (которые ещё и отловить будет непросто, если никто долгое время не будет текст добавлять). Помимо того, "нам ранее ни разу не пригодилась" -- не факт, что не понадобится в будущем, кроме того, пусть опенкорпора задаёт высокий стандарт для систем такого класса. Глядишь, форкнет кто-нибудь -- и спасибо скажут за готовую фичу.

**Comment by grandsbor** [comment]
Можно закрыть?
