### ISSUE TITLE
Включить настройки user_options в дистрибутив чистой базы

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#137]
В текущем варианте инсталлятора пустой базы даётся пустая таблица user_options: что хочешь -- то и заполняй.

Всё бы было ничего, только настройки так сильно захардкожены и настройки так сильно влияют на работу пустого проекта -- что лучше внести некоторые важные элементы настроек в дистрибутив.

Один момент я уже описывал ранее: если настроек нет (чистая база) -- то будет падать при входе в систему (см. https://github.com/OpenCorpora/opencorpora/issues/132 )

Более чем уверен: подобных примеров найдётся ещё немало... Где не предусмотрено, что настроек ещё может не быть. Вариантов собственно два. Первый я вынес в заголовок issue, второй -- найти и написать код, чтобы не было никаких претензий, ни один warning не прорвался.

Я рекомендую идти по первому варианту (а покуда не появится ни одного желающего создать проект, аналогичный нашему -- нет никакого смысла прямо досконально вычищать мелкие баги)

Приведу некоторые фрагменты кода, за которые я зацепился взглядом.

Есть какая-то магическая настройка с id=2 которая не показывается на окне настроек:
https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_users.php#L370

Либо она не должна показываться совсем никому, очень важная и настраивается только посредством прямого доступа к sql-базе, либо её уже давно нет.

Настройка с id=3 просто захардкожена:
https://github.com/OpenCorpora/opencorpora/blob/master/tasks.php#L25

Ну и так далее. Предлагаю пожалеть нервы тех, кто будет читать код и разгадывать логические ребусы, угадывая какие настройки за каким id'шником спрятаны.

**Comment by akmetainfo** [comment]
А настройка, указанная в https://github.com/OpenCorpora/opencorpora/issues/121 скрывается за цифрой "5":
https://github.com/OpenCorpora/opencorpora/blob/master/books.php#L69
Заодно и https://github.com/OpenCorpora/opencorpora/issues/121 можно будет закрыть.

**Comment by akmetainfo** [comment]
Хм, вот что ещё по той же тематике https://github.com/OpenCorpora/opencorpora/issues/92

**Comment by madfriend** [comment]
Можно попробовать миграцию теперь.
Значения настроек описаны в самой таблице user_options.

**Comment by akmetainfo** [comment]
Да, вижу значения от 1 до 4, спасибо.
Сейчас ещё посмотрю какие-то проблемы с кодировкой... База UTF-8, general_ci, кодировка в файле UTF-8, а после импорта кракозябры (побилось в направлении CP1252 → UTF-8)

**Comment by akmetainfo** [comment]
А давайте ещё в рамках данного issue явно укажем в начале файла initial_schema.sql кодировку
````sql
SET NAMES utf8;
````
На структуре таблиц ранее было некритично, а как появились вставки -- сразу нужно определяться с форматом данных. База в UTF-8 (и во всех инструкциях по развёртыванию окружения прописано явно), файл в UTF-8... 

Если бы не это -- уже бы закрыл вопрос.

**Comment by grandsbor** [comment]
Кстати, а как вы (оба) думаете: может, вообще убрать опции из базы? Пусть только user_options_values останется, остальное в коде прописать.

**Comment by akmetainfo** [comment]
Предлагаю с этим вопросом переместиться сюда: https://github.com/OpenCorpora/opencorpora/issues/92
@grandsbor
