### ISSUE TITLE
ner (still) availible to any logged

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#138]
https://github.com/OpenCorpora/opencorpora/blob/master/ner.php#L5

C августа и до сих пор: https://github.com/OpenCorpora/opencorpora/commits/master/ner.php

Красивый интерфейс (заходил из любопытства)

**Comment by madfriend** [comment]
Пока что планов закрывать интерфейс не было. Проверка в коде приехала из интерфейса для разметки именных групп, оставил на будущее - если все-таки сделаем интерфейс закрытым.
