### ISSUE TITLE
не работает кнопка 'v' при ручном снятии неоднозначности

### ISSUE THREAD

**Issue by svbichineva** [OpenCorpora/opencorpora#141]
В интерфейсе типа http://opencorpora.org/sentence.php?id=740# не работает кнопка 'v' (чтобы сразу выбрать правильный вариант), работает только 'x' (убрать неправильный)

**Comment by madfriend** [comment]
Света, это на айпаде? На ноуте, в браузере, вроде работает (другие варианты разбора становятся серыми)

**Comment by svbichineva** [comment]
Заработало, ты что-то сделал? Не работало на айпаде и просто в Сафари на компе

**Comment by madfriend** [comment]
Нет, ничего не делали. Странно :-)

**Comment by svbichineva** [comment]
Поняла, когда это происходит. После того, как я делаю переразбор из словаря перестает работать эта кнопка

**Comment by madfriend** [comment]
cc @grandsbor 
Как воспроизвести? Возможно, нужны какие-то права пользователя (чтобы сделать переразбор)?

**Comment by grandsbor** [comment]
Вроде не нужны никакие особенные права.

**Comment by svbichineva** [comment]
переразбор слово в этом интерфейсе — это две стрелочки на зеленом фоне у каждого слова

**Comment by madfriend** [comment]
Воспроизвел.

Диме, стектрейс (если интересно)
>Uncaught TypeError: Cannot set property 'value' of null
>del_var main.js?3:134
>best_var main.js?3:143
>sentence.php?id=740:1
