### ISSUE TITLE
Предложение обрывается при разметке

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#144]
Исходное предложение: http://opencorpora.org/books.php?book_id=2973&full#sen71899
При разметке выглядит так: http://opencorpora.org/pools.php?act=samples&pool_id=2601&ext&filter=comments

**Comment by akmetainfo** [comment]
ещё один подобный пример выловил в базе: http://opencorpora.org/tasks.php?act=annot&pool_id=2908
> Проживание ( пребывание , нахождение ) в каком-либо 

Полностью контекст: http://opencorpora.org/books.php?book_id=3359&full#sen86560
> Проживание  (  пребывание  ,  нахождение  )  в  каком-либо  ином  месте  –  не  может  считаться  нарушением  закона  .

**Comment by akmetainfo** [comment]
А этот пример я просто покажу картинкой. Так получается, что в одном и том же пуле рядом могут быть примеры из одного и того же предложения -- и в одном полностью сохраняется предложение, а в другом -- нет:
![222222222222222](https://cloud.githubusercontent.com/assets/6085279/5987714/9cbd361c-a94b-11e4-8c3f-aae9b2dc6741.png)
