### ISSUE TITLE
Научить питоновскую библиотеку расстановке связей

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#145]
`python/Annotation.py`

В базе устроено так:

``` sql
mysql> explain dict_lemmata;
+------------+-----------------------+------+-----+---------+----------------+
| Field      | Type                  | Null | Key | Default | Extra          |
+------------+-----------------------+------+-----+---------+----------------+
| lemma_id   | mediumint(8) unsigned | NO   | PRI | NULL    | auto_increment |
| lemma_text | varchar(50)           | NO   |     | NULL    |                |
| deleted    | tinyint(3) unsigned   | NO   | MUL | NULL    |
+------------+-----------------------+------+-----+---------+----------------+

mysql> explain dict_links_types;
+-----------+----------------------+------+-----+---------+----------------+
| Field     | Type                 | Null | Key | Default | Extra          |
+-----------+----------------------+------+-----+---------+----------------+
| link_id   | smallint(5) unsigned | NO   | PRI | NULL    | auto_increment |
| link_name | varchar(50)          | NO   |     | NULL    |                |
+-----------+----------------------+------+-----+---------+----------------+

mysql> explain dict_links;      
+-----------+-----------------------+------+-----+---------+----------------+
| Field     | Type                  | Null | Key | Default | Extra          |
+-----------+-----------------------+------+-----+---------+----------------+
| link_id   | int(10) unsigned      | NO   | PRI | NULL    | auto_increment |
| lemma1_id | mediumint(8) unsigned | NO   | MUL | NULL    |                |
| lemma2_id | mediumint(8) unsigned | NO   | MUL | NULL    |                |
| link_type | smallint(5) unsigned  | NO   |     | NULL    |                |
+-----------+-----------------------+------+-----+---------+----------------+

mysql> explain dict_links_revisions;
+-----------+-----------------------+------+-----+---------+----------------+
| Field     | Type                  | Null | Key | Default | Extra          |
+-----------+-----------------------+------+-----+---------+----------------+
| rev_id    | int(10) unsigned      | NO   | PRI | NULL    | auto_increment |
| set_id    | int(10) unsigned      | NO   |     | NULL    |                |
| lemma1_id | mediumint(8) unsigned | NO   |     | NULL    |                |
| lemma2_id | mediumint(8) unsigned | NO   |     | NULL    |                |
| link_type | smallint(5) unsigned  | NO   |     | NULL    |                |
| action    | tinyint(3) unsigned   | NO   |     | NULL    |                |
+-----------+-----------------------+------+-----+---------+----------------+

```

Также см. тематические функции:
https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_dict.php#L643
https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_dict.php#L633

**Comment by grandsbor** [comment]
cc @yourmary

**Comment by gisly** [comment]
Здравствуйте! Возникло несколько вопросов:
1) в php-библиотеке перед добавлением и удалением проверяются права пользователя. Здесь тоже нужно принимать данные пользователя?
2) сейчас не запрещено создавать сколько угодно связей между одними и теми же леммами одного и того же типа. Это правильно? Если нет, что нужно сделать: добавить констрейнт в БД или проверку в функции? В БД таких дублей сейчас нет.
3) при выполнении нескольких удалений и добавлений  надо создавать новый revset или оставлять один и тот же?
4) нужно ли приводить синтаксис в соответствие с Python3 (например, менять ConfigParser)?

**Comment by grandsbor** [comment]
1. Нет
2. Это сойдёт, проверку можно не делать
3. Неважно. Как проще.
4. А для python3 уже есть модуль для работы с MySQL?

**Comment by gisly** [comment]
4. Вроде есть несколько штук (http://stackoverflow.com/questions/4960048/python-3-and-mysql).

**Comment by grandsbor** [comment]
Тогда это было бы неплохо, но потом. В другом тикете :)

**Comment by gisly** [comment]
подскажите, еще, пожалуйста: в питоновской библиотеке есть find_lexeme_by_lemma. В запросе используется поле is_last, которого нет в дампе БД с сайта. Дамп неактуален или поменять запрос?

**Comment by grandsbor** [comment]
Дамп неактуален. Выясню, можно ли обновить.

**Comment by grandsbor** [comment]
Завтра утром будет новый дамп. Или можно раньше

**Comment by gisly** [comment]
спасибо! для отладки это вообще не критично
еще несколько вопросов:
1) что делать, если в списке по заданным лемме и списку граммем найдено несколько лексем? делать связи для каждой или сообщать об ошибке?
2) что делать, если лексемы не нашли? или в актуальном дампе такого не будет?

**Comment by grandsbor** [comment]
1) думаю, сообщать об ошибке
2) а при чем тут дамп? мы искать же будем не по дампу, а по базе

**Comment by gisly** [comment]
я имела в виду, в выгрузке с сайта нет некоторых лемм+граммем (например, нет "славка"+NOUN,anim,Name — это из списка имен)

**Comment by grandsbor** [comment]
Ну в любом случае можно выводить какое-нибудь сообщение, если чего-то не нашлось.

**Comment by irinfox** [comment]
Оно готово?
Может, закрыть? Или надо что-то проверять после мёрджа?

**Comment by grandsbor** [comment]
Кажется, оно работало, да
