### ISSUE TITLE
Экспорт корпуса с разбиением по текстам

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#147]
Каждый текст - в отдельном файле, все вместе - в архиве

**Comment by sepulchered** [comment]
https://github.com/sepulchered/opcorp_splitter написал скрипт, могу сделать pull request в этот репозиторий.
В принципе можно сразу генерировать zip-файл в скрипте, питон это позволяет, без создания папки на диске, а потом архивации.

**Comment by grandsbor** [comment]
Да, сделай пулл-реквест, пожалуйста.
На мой вкус, лучше зиповать отдельно.

**Comment by sepulchered** [comment]
Куда положить?

**Comment by grandsbor** [comment]
В `export/annot`

**Comment by grandsbor** [comment]
Теперь надо включить это в ежедневный экспорт

**Comment by grandsbor** [comment]
Что-то я не посмотрел, а у тебя там DOM-парсер :) Мы в память не влезаем с ним, нужен SAX-парсер.

**Comment by sepulchered** [comment]
А сколько памяти?

**Comment by sepulchered** [comment]
По идее он не должен больше одного узла текста в память загружать.

**Comment by grandsbor** [comment]
Да даже не очень важно, сколько, всё равно с ростом корпуса она начнёт кончаться.
На продакшен-машине мы можем потратить около гигабайта, сейчас он ест больше (и прибивается менеджером памяти)

**Comment by sepulchered** [comment]
Да, есть проблемы, но это очевидно зависит от размера текста. Картинка от профайлера ![memory usage](https://raw.githubusercontent.com/sepulchered/opcorp_splitter/master/memory_usage_iterparse.png). 
Добавлю обработку sax'ом, но уже на следующей неделе.

**Comment by grandsbor** [comment]
Ещё у нас питон 3.1, может, как-то тоже влияет

**Comment by grandsbor** [comment]
Андрей, спасибо, выкатилось
