### ISSUE TITLE
Добавить пулы для супер-частотных случаев (или просто их поправить)

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#151]
Например, сейчас у слова "нее" неоднозначность нигде не снята (ни в одном слове), хотя мне кажется, что ни одной "Неи" в корпусе нет. Туда же "того". У слова "Тому" вариант с "мест-п" гораздо чаще должен встречаться, как мне кажется.

Я просто в pymorphy2 оцениваю вероятности разбора по результатам снятия неоднозначности в OpenCorpora (для отдельных слов); если даже немного такие случаи поснимать, то это сильно помочь должно.

Я бы мог и сам попомогать поснимать, но непонятно, как это делать пользователям в текущем интерфейсе.

**Comment by svbichineva** [comment]
Хорошо. Я отмодерирую пулы с того и тому. А пула про слово "нее"  нет, это к Диме или Вите.

**Comment by akmetainfo** [comment]
А что это за пул на "Того" (существительное, страна в Африке" и "того" (мест-п)? Или это раскидано по разным пулам?

**Comment by svbichineva** [comment]
Да, это пул сущ - местоим прил, где слово "того" либо форма слова тот, либо страна в Африке "Того"

**Comment by kmike** [comment]
Спасибо!

**Comment by akmetainfo** [comment]
А, я понял: не там ищу. Это уже снято с разметки, на модераторах висит. ADJF&Apro@NOUN

**Comment by grandsbor** [comment]
Да, пулов про "нее" (NOUN/NPRO) просто нет. Света, сделаем?

**Comment by svbichineva** [comment]
Я не против. Ты сделаешь? Я, если честно, не знаю/не помню как

**Comment by grandsbor** [comment]
Поставил примеры искаться

**Comment by grandsbor** [comment]
Ну, не назвал бы это суперчастотными случаями, нашлось 469 примеров (слова "кому", "неё", "им"). Сделал три пула, вывесил.

**Comment by kmike** [comment]
Да, я плохо выразился. "супер-частотные" имелось в виду по отношению к другим вариантам разбора - "того" как Apro супер-частотный вариант по сравнению с NOUN. Другими словами, "простые".
