### ISSUE TITLE
Турборазметка: дать возможность разметки по 100 и 200 примеров за раз

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#152]
Сейчас [есть только по 5, 10, 20 и 50](https://github.com/OpenCorpora/opencorpora/blob/master/tasks.php#L25). А мне очень надо бывает именно открыть сразу 100 или 200. Не то, чтобы я садист, который готов повесить базу своими запросами ("ну и запросы у вас", -- сказала база данных и зависла"), нужно для зачистки хвостов:
![123](https://cloud.githubusercontent.com/assets/6085279/6026985/fd08594c-abef-11e4-9a26-5fb557f2028e.png)

Это очень помогает вот чем. 

Во-первых, позволяет отложить некоторые неудобные примеры из пула и пройти дальше, делая на ходу лёгкие. (Есть кнопка "пропустить", по которой пример никогда уже не покажется, но нет кнопки "отложить", чтобы потом можно было вернуться. Собственно из-за этого и появился этот таск). У меня в именительном/винительном сделано 75% заданий, при этом ещё ~20% я могу доделать за день-другой. И вот когда в именительном/винительном останется в каждом пуле по 2-3 примера -- я тогда их буду проходить ещё пару месяцев минимум.

Но, во-вторых, и это ещё важнее -- очень удобно потом осматривать остающиеся 1-2 сложных примера (т.е. разметка по 200 включается уже под конец работы с очередной "двухсоточкой"), пытаясь отыскать наиболее часточные случаи для задавания вопросов в рассылке.

Готов согласиться, что этот режим по 100 и 200 будет включаться ограниченно -- только какой-то отдельной категории пользователей и при том, что будет специальная GET-переменная, которую я буду добавлять руками по необходимости в адресную строку браузера.

**Comment by grandsbor** [comment]
Сложно.
Давайте я в какой-то момент руками залезу в базу и верну вам все пропущенные примеры? (Возможно, только в некоторых типах пулов)

**Comment by akmetainfo** [comment]
У меня нет пропущенных примеров: я их уже давно не пропускаю. И смысл не в том, чтобы обратно вернуть пропущенные -- а пройти размечать дальше тех примеров, которые я не ответил, но и не пропустил.

**Comment by grandsbor** [comment]
Вот я и предлагаю пока пропускать, а потом вернем

**Comment by akmetainfo** [comment]
Ладно, если сложно -- тогда буду выкручиваться как раньше.

**Comment by irinfox** [comment]
Ещё в интерфейсе предусмотрена возможность (кажется) сохранить те примеры,
которые разметили сейчас.
Т.е. существует такой вариант: выбрать 50 примеров, разметить те из них, в
которых уверены, сказать "с меня хватит" вместо "ещё", а затем выбрать
снова этот пул. Таким образом, получится, что "сложные примеры" вы не
пропустили, т.е. что они будут доступны.
Да это не самый лёгкий путь, но он работает.

2015-02-04 17:56 GMT+03:00 Dmitry Granovsky <notifications@github.com>:

> Вот я и предлагаю пока пропускать, а потом вернем
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/152#issuecomment-72868250>
> .
>



-- 
Ирина

**Comment by grandsbor** [comment]
Кстати, да, так проще всего. Неразмеченные примеры будут висеть сверху, но их можно проматывать

**Comment by akmetainfo** [comment]
Ирина, вот я именно так и поступаю: нажимаю "хватит". Только в том-то и фишка, что эти примеры "не промотаешь". Взял 50, осталось два несделанных -- будет висеть цифра "48 сделано" и "доступно 150+2". А мне как раз надо обойти эти два и разметить оставшиеся 150 -- там возможно останется ещё 1-2 -- но главное, что я повыбираю все тривиальные примеры, а над сложными подумаю месяц-другой.

Могу подтвердить скриншотом.
![s1](https://cloud.githubusercontent.com/assets/6085279/6042774/8215fdb2-ac98-11e4-90cd-0469ed423c51.png)

![s2](https://cloud.githubusercontent.com/assets/6085279/6042777/86f7d47c-ac98-11e4-8013-9a54d21cf59b.png)

**Comment by grandsbor** [comment]
Давайте мы ещё раз всей командой скажем, что месяц-другой может думать модератор, а от просто участника мы этого не ждем :-) свои сомнения пусть пишет в комментарии. если уж там есть над чем думать месяц, этот пример должен попасть к модератору

**Comment by akmetainfo** [comment]
Да на над чем там думать обычно... Я держу их в качестве примеров под будущие фрагменты инструкций или вопросов для рассылки. Очень удобно: сразу десяток несколько примеров посмотрел, выбрал поудачнее, горстью закинул а потом ещё выбираешь к ним уточняющие.
Вон на скриншоте -- будущий фрагмент про счётный падеж применительно к этому пулу.

**Comment by irinfox** [comment]
Мы вообще изначально не задумывались о том, что инструкции будут писать
участники, поэтому этот случай употребления кажется нам крайне редким.
А примеры, к которым разметчики написали комментарии, как раз повод для
модератора задуматься о том, что эти примеры надо включать в инструкцию.

В общем usecase странный, не вижу повода, по которому мы должны задуматься
о то, чтоб специально прописывать код под эту задачу.


4 февраля 2015 г., 18:26 пользователь Andrey <notifications@github.com>
написал:

> Да на над чем там думать обычно... Я держу их в качестве примеров под
> будущие фрагменты инструкций или вопросов для рассылки. Очень удобно: сразу
> десяток несколько примеров посмотрел, выбрал поудачнее, горстью закинул а
> потом ещё выбираешь к ним уточняющие.
> Вон на скриншоте -- будущий фрагмент про счётный падеж применительно к
> этому пулу.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/152#issuecomment-72874366>
> .
>



-- 
Ирина
