### ISSUE TITLE
Добавить несклоняемые варианты для аббревиатур типа "ГОСТ"?

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#153]
Не стал продолжать [тему "Домодедово"](https://github.com/OpenCorpora/opencorpora/issues/35) (там всё же речь сугубо о Geox)
Очень часто аббревиатуры используют как нескл., пример - [ГОСТ](http://opencorpora.org/dict.php?act=edit&id=74088&found_form=):
> с указанными целями должны применяться соответствующие требования ранее принятых ГОСТ, санитарных и строительных норм и правил ( СанПиН , СНиП ).

Здесь plur+gent, должно быть ГОСТов.
СанПиН и СНиП -- вообще в словаре отсутствуют почему-то.
Такое добавление опять добавит лишнюю неоднозначность в корпусе, не стоит?

PS Многих аббревиатур нет в словаре, например ВИЧ есть, а СПИД - нет. Но если брать самое частотное - то это ГОСТ, его и вынес в заголовок для примера.

**Comment by grandsbor** [comment]
cc @svbichineva

**Comment by grandsbor** [comment]
cc @kmike Что думаешь?

**Comment by kmike** [comment]
Мне кажется, это хорошая идея, аббривеатуры часто не склоняют.

В pymorphy2 я когда-нибудь добавлю разборщик-предсказатель для неизвестных аббривеатур, но иметь аббривеатуры в словаре все равно хорошо - это доп. информация о роде и числе, например.

**Comment by akmetainfo** [comment]
1. Добавьте метку "словарь"
2. Вопрос ранее обсуждался (как раз на примере аббревиатуры ВИЧ - https://github.com/OpenCorpora/opencorpora/issues/54), как раз фиксировали в нескл

**Comment by svbichineva** [comment]
ГОСТу добавила неизменно варианты, добавила слова СНиП и СанПиН, слово СПИД в словаре было, я его отредактировала
