### ISSUE TITLE
получас

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#155]
http://opencorpora.org/dict.php?act=edit&id=256939
Оно нам точно надо? Есть хорошее слово "полчаса": http://opencorpora.org/dict.php?act=edit&id=257020

**Comment by akmetainfo** [comment]
В корпусе встречается в текстах. Навскидку из недавнего:
http://opencorpora.org/pools.php?act=samples&pool_id=3669&skip=150
http://opencorpora.org/books.php?book_id=2199&full#sen55810
> После  длительного  подъёма  мы  подъехали  к  границе  ,  и  подождав  около  **получаса**  ,  мы  вместе  с  кампанией  монголов  ,  везущих

Не знаю, чем они там различаются лингвистически, но сказать можно "около получаса", но "примерно полчаса" (а не наоборот).

**Comment by madfriend** [comment]
@akmetainfo 
>Есть хорошее слово "полчаса": http://opencorpora.org/dict.php?act=edit&id=257020

**Comment by akmetainfo** [comment]
Одно - SGTM, второе -- без, насколько я понимаю устройство словаря слова не получится объединить в одной лемме?

PS Лично меня больше удивляет, что "полчаса" -- это средний род, а "получас" - -мужской. Собственно, только поэтому и пришлось снимать неоднозначность.

**Comment by svbichineva** [comment]
Основной вариант полчаса, сняла помету sgtm, оставила ср род, так как нормальное выражение "прошло полчаса",  добавила формы им, мн и вир, мн "полчаса" (прошли последние полчаса)
Из парадигмы слова получас удалила все формы, совпадающие с формами внутри "полчаса"
Связала два слова связью norm-orhovar
