### ISSUE TITLE
Ссылки "править" на странице с заданиями

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#156]
Зашел неавторизованным на http://opencorpora.org/tasks.php, вижу:

![2015-02-08 14 08 26](https://cloud.githubusercontent.com/assets/1223831/6096300/39484e18-af9b-11e4-9ef4-d03537a6322b.png)

Раньше этих ссылок, если мне не изменяет память, не было. Они нам точно нужны и в таком виде?

**Comment by akmetainfo** [comment]
Раньше действительно не было, появилось как побочный эффект после обновления движка mediaiki. Вы не авторизованы на сайте, но авторизация в вики-движке осталась.
Я много и часто правлю вики, плюс как только Дмитрий обновил вику -- сразу пошёл проверять, не отвалилось ли что и так же заметил данный эффект.
Штука не критичная на мой взгляд, в принципе, если очень не нравится -- нужно посмотреть, что и как поменялось в авторизационных кукисах вики-движка.

**Comment by grandsbor** [comment]
Редактирование этой страницы анонимами и так отключено, так что оно, очевидно, не помогает. Опция тоже. Так что сделал css-ом
