### ISSUE TITLE
Сохранённая копия документа 3429

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#157]
301 Moved Permanently
Почему?
Исходный документ исчез, т.е. не перезакачать.

**Comment by grandsbor** [comment]
cc @madfriend 
Надо полагать, curl не умеет (или не настроен) ходить по 301-м перенаправлениям.
А что за документ? Больше нет копий в сети?

**Comment by madfriend** [comment]
Дима, а где это в коде?

**Comment by akmetainfo** [comment]
Curl умеет ходить по редиректам. CURLOPT_FOLLOWLOCATION

**Comment by grandsbor** [comment]
Да, уже нашёл и поправил :)

**Comment by victorbocharov** [comment]
Спасибо. Не знаю как проверить. Закрываю.
