### ISSUE TITLE
Невозможно завершить модерацию пула.  Error in sample #

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#158]
При попытке закрыть [пул 3676](http://opencorpora.org/pools.php?act=samples&pool_id=3676&ext&filter=not_moderated) выдаёт:
> Произошла ошибка. Error in sample #

Не знаю, с чем связано -- подозреваю, что связано с [обсуждаемым примером про получас](https://github.com/OpenCorpora/opencorpora/issues/155).

**Comment by grandsbor** [comment]
Скорее всего, неправильная комбинация ответа и статуса: к примеру выбран
один из ответов и проставлено "нет правильного разбора"

**Comment by akmetainfo** [comment]
Попробовал вспомнить примеры, где я ставил "нет правильного разбора". Да, был один пример, где слово было женского рода, а попало в пул на мужской/средний. Проверил: стоит "Other" +"Частично правильно" (видимо, переключатель соскользнул с "Нет правильного разбора"). Да, в этом дело: при "нет правильного разбора" пул закрыть можно, при "частично правильно" - не даёт закрыть.
Не могу сказать, что весьма информативно пишет, но всё ж приятно, что ошибка вспыла сразу, а не на проверке метамодератором.
