### ISSUE TITLE
Не обновляется статистика по тегам

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#162]
http://opencorpora.org/?page=tag_stats

**Comment by grandsbor** [comment]
Как ты это понял?

**Comment by victorbocharov** [comment]
Два дня назад убрал тег https: у всех документов, у которых он был. А он остался в статистике.

**Comment by grandsbor** [comment]
Вообще ты прав, обновление выключено больше года назад (19/11/2013) с комментарием "disable tag stats updates for now". Не помню, зачем это было сделано. Включаю обратно
