### ISSUE TITLE
Счётная форма для "бит" и "байт"

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#169]
В словаре проставлена счётная форма у "[бит](http://opencorpora.org/dict.php?act=edit&id=30104&found_form=%D0%B1%D0%B8%D1%82)" (но "[килобит](http://opencorpora.org/dict.php?act=edit&id=132830&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%B1%D0%B8%D1%82)", "[мегабит](http://opencorpora.org/dict.php?act=edit&id=156901&found_form=%D0%BC%D0%B5%D0%B3%D0%B0%D0%B1%D0%B8%D1%82)", "[терабит](http://opencorpora.org/dict.php?act=edit&id=345150&found_form=%D1%82%D0%B5%D1%80%D0%B0%D0%B1%D0%B8%D1%82)" -- уже без счётной формы идут). "[Гигабит](http://opencorpora.org/dict.php?search_form=%D0%B3%D0%B8%D0%B3%D0%B0%D0%B1%D0%B8%D1%82&act=lemmata)" в словаре отсутствует, видимо не попадалось ещё в примерах.

У "[байт](http://opencorpora.org/dict.php?act=edit&id=22500&found_form=%D0%B1%D0%B0%D0%B9%D1%82)" счётной формы нет ни в каком варианте (проверил префиксы "[кило](http://opencorpora.org/dict.php?act=edit&id=132826&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%B1%D0%B0%D0%B9%D1%82)", "[мега](http://opencorpora.org/dict.php?act=edit&id=156896&found_form=%D0%BC%D0%B5%D0%B3%D0%B0%D0%B1%D0%B0%D0%B9%D1%82)", "[гига](http://opencorpora.org/dict.php?act=edit&id=69540&found_form=%D0%B3%D0%B8%D0%B3%D0%B0%D0%B1%D0%B0%D0%B9%D1%82)" и "[тера](http://opencorpora.org/dict.php?act=edit&id=345149&found_form=%D1%82%D0%B5%D1%80%D0%B0%D0%B1%D0%B0%D0%B9%D1%82)").

Предлагаю поправить -- из-за этого в некоторых примерах на падежи будет не совсем корректно.

http://opencorpora.org/tasks.php?act=annot&pool_id=2583

Например , на дисках с размером секторов в 512 |байт| , 512 - байтный кластер содержит один сектор , тогда как 4-килобайтный кластер содержит восемь секторов .

http://opencorpora.org/tasks.php?act=annot&pool_id=2560

В стадии разработки находятся системы , позволяющие передавать от 400 гигабит до 1 |терабит| в секунду .

PS [Грамм](http://opencorpora.org/dict.php?act=edit&id=74555&found_form=%D0%B3%D1%80%D0%B0%D0%BC%D0%BC) и [килограмм](http://opencorpora.org/dict.php?act=edit&id=132839&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC) -- содержат счётную форму, а [метр](http://opencorpora.org/dict.php?act=edit&id=159296&found_form=%D0%BC%D0%B5%D1%82%D1%80), [километр](http://opencorpora.org/dict.php?act=edit&id=132850&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%BC%D0%B5%D1%82%D1%80), [сантиметр](http://opencorpora.org/dict.php?act=edit&id=313431&found_form=%D1%81%D0%B0%D0%BD%D1%82%D0%B8%D0%BC%D0%B5%D1%82%D1%80) и [дециметр](http://opencorpora.org/dict.php?search_form=%D0%B4%D0%B5%D1%86%D0%B8%D0%BC%D0%B5%D1%82%D1%80&act=lemmata) -- не содержат. (Или в метрах не особо и нужно?)

**Comment by akmetainfo** [comment]
Продолжаю [разбираться со счётной формой](http://opencorpora.org/wiki/%D0%A3%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA:Andrey_Kruglov/%D0%9F%D1%80%D0%BE_%D1%81%D1%87%D1%91%D1%82%D0%BD%D1%8B%D0%B9_%D0%BF%D0%B0%D0%B4%D0%B5%D0%B6). 
[Грамм](http://opencorpora.org/dict.php?act=edit&id=74555&found_form=%D0%B3%D1%80%D0%B0%D0%BC%D0%BC) и [килограмм](http://opencorpora.org/dict.php?act=edit&id=132839&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC) -- содержат счётную форму, а [метр](http://opencorpora.org/dict.php?act=edit&id=159296&found_form=%D0%BC%D0%B5%D1%82%D1%80), [километр](http://opencorpora.org/dict.php?act=edit&id=132850&found_form=%D0%BA%D0%B8%D0%BB%D0%BE%D0%BC%D0%B5%D1%82%D1%80), [сантиметр](http://opencorpora.org/dict.php?act=edit&id=313431&found_form=%D1%81%D0%B0%D0%BD%D1%82%D0%B8%D0%BC%D0%B5%D1%82%D1%80) и [дециметр](http://opencorpora.org/dict.php?search_form=%D0%B4%D0%B5%D1%86%D0%B8%D0%BC%D0%B5%D1%82%D1%80&act=lemmata) -- не содержат.

**Comment by grandsbor** [comment]
А кто-то пишет "100 метр"? :)
