### ISSUE TITLE
Ошибки в экспорте текстов с разбивкой по файлам

### ISSUE THREAD

**Issue by vtqveant** [OpenCorpora/opencorpora#172]
Лишние пробелы внутри тегов, не заэкранированы символы, вкл. " и & в урлах. В экспорте одним файлом всё ок.

    ~/data/annot.opcorpora.xml.byfile$ cat 1.xml 
    <?xml version="1.0" encoding="utf-8"?><text id="1" parent="0" name=""Частный корреспондент""><tags ><tag >url:http://www.chaskor.ru</tag><tag >Тип:Газета</tag></tags><paragraphs ></paragraphs></text>

**Comment by madfriend** [comment]
Дима, проверь, пожалуйста, корректно ли работает скрипт с исправлениями (не было под рукой файлов)

**Comment by vtqveant** [comment]
Ещё наблюдаю, что в некоторых текстах предложения в //sentence/source содержат пробелы, добавленные при токенизации (напр. 102.xml -- "Альдо Нове . No future XXI века Только в « Часкоре » : лидер « юных людоедов » удивил всех , собрав коллекцию бесед с « новыми бедными »), а часть нет.

**Comment by grandsbor** [comment]
Саш, по-моему, ничего не изменилось:
`<text id="1" parent="0" name=""Частный корреспондент"">`

**Comment by madfriend** [comment]
Дима, поправил это

**Comment by grandsbor** [comment]
Сейчас файлы уже перегенерированы. Костя, закрой тикет, если они тебя устраивают :)

**Comment by vtqveant** [comment]
Пока не устраивают. 

Ещё https://github.com/OpenCorpora/opencorpora/issues/172#issuecomment-78988730 (может быть это специально, но я как пользователь ожидаю, что source содержит текст до всякой обработки, т.е. в дампе исходный текст не совпадает с копией на http://opencorpora.org/files/saved/4e3ecb18b5e716.84197313.html )

И ещё амперсанды в урлах, напр. в 146.xml (должно быть &amp;amp;)

    <?xml version="1.0" encoding="utf-8"?><text id="146" parent="56" name="Контрабанда водки по трубопроводу"><tags><tag>url:http://ru.wikinews.org/w/index.php?title=Контрабанда_водки_по_трубопроводу&oldid=16552</tag>

**Comment by grandsbor** [comment]
А вот мы спросим у Насти :) @lasveritas Ты вот тут 3,5 года назад заливала [текст](http://opencorpora.org/books.php?book_id=102), не помнишь, делала с ним что-нибудь особенное? Там исходник текста оказался токенизирован

**Comment by vtqveant** [comment]
Кажется, проблема с source упоминается в #443. Можно перенести туда, а здесь доделать амперсанд и закрыть. Проблема с амперсандом сейчас затрагивает 1092 текста в дампе.

**Comment by lasveritas** [comment]
Да, когда я только начинала заливать тексты, первые из них токенизировала вручную, пока мы не выяснили, что так делать не надо. Но тогда вроде как решили, что это поправимо. 

Если эти тексты остались нетронутыми, то стоит тогда посмотреть на мои первые заливки, чтобы не было тех же проблем)

**Comment by madfriend** [comment]
Дима, потести, пожалуйста, корректно ли эскейпятся амперсанды

**Comment by grandsbor** [comment]
@lasveritas Спасибо!

**Comment by grandsbor** [comment]
Кстати, @sepulchered Этот тикет тебе к сведению :)

**Comment by sepulchered** [comment]
@grandsbor да, я об этом думал, но не сделал эскейпинг символов.  В принципе там сейчас все теги руками пишутся - надо либо в этих местах сделать чтоб эскейпилось, либо культурно писать теги опираясь на библиотеку какую-нибудь. Если в ближайшее время дойдут руки - закоммичу апдейт, если вы конечно раньше не исправите :)

**Comment by madfriend** [comment]
Дим, я же коммитил изменения. В т.ч. для ссылок в тегах (экранирование
амперсанда)

Там проблема в том, что sax-парсер анэскейпит содержимое тега перед
тем, как отдать его в метод characters

23.03.15, Andrey Dresvyannikov<notifications@github.com> написал(а):

**Comment by grandsbor** [comment]
А я и не утверждал, что не коммитил :)

**Comment by grandsbor** [comment]
Нормально теперь, да?

**Comment by vtqveant** [comment]
Парсится ок; //source некорректный примерно в нескольких десятках мест, потом сделаю список в #443

**Comment by grandsbor** [comment]
Хорошо. Всем спасибо!
