### ISSUE TITLE
Частичное задваивание предложения в задании

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#173]
Это пример, противоположный закрытому ныне #144, но фраза про частичное исправление намекает, что природа бага может быть похожей.

При просмотре в интерфейсе модератора тоже задваивается:
http://opencorpora.org/pools.php?act=samples&pool_id=153&ext&skip=75
![222](https://cloud.githubusercontent.com/assets/6085279/6657719/dd6ad7e2-cb64-11e4-8edb-a8124f1da6e2.png)

При разметке -- не знаю, пул размечен пару лет назад.

А вот при просмотре текста всё ОК:
http://opencorpora.org/books.php?book_id=459&full#sen19710

**Comment by akmetainfo** [comment]
На заметку. Похоже, что этот баг имеет свойство пропадать после каких-то активных действий модератора.
Заметил ещё один пример подобного рода, решил проверить пул до конца, а потом уже написать - однако сейчас я вижу, что баг самоликвидировался.
Заметил я его [на фразе](http://opencorpora.org/books.php?book_id=1541&full#sen43137) "В  результате  этого  паровозы  были  переведены  на  равнинные  участки  дороги" (см. [тут](http://opencorpora.org/pools.php?act=samples&pool_id=187&ext&filter=disagreed&skip=30)) - при этом дублировалось буквально 4 слова (до паровозы).
Всё, что я сделал -- это выбрал один из вариантов, дошёл до конца страницы и нажал "завершить модерирование" (это была последняя страница disagree)

**Comment by grandsbor** [comment]
Очень странно, если так

**Comment by akmetainfo** [comment]
> Очень странно, если так

Тем не менее это действительно так, только что убедился. 
У меня есть такая привычка -- через час-другой после модерирования пула я ещё раз пересматриваю disagreed. Смотрю -- а [в примере](http://opencorpora.org/pools.php?act=samples&pool_id=1970&ext&filter=disagreed) задвоение. (Причём хоть и час прошёл -- а я точно помню, что не было задвоения, когда я модерировал пул.
Ну да это некритично.) 

Я тогда то сделал? Я снял скриншот (чтобы быть точно уверенным, что мне не пригрезилось задвоение), а потом решил проверить -- пропадёт ли оно, если я открою и тут же закрою пул.
Так и получилось: задвоение тут же пропало. Ради интереса открывал и закрывал пул, но задвоение больше уже не появлялось.
![12345](https://cloud.githubusercontent.com/assets/6085279/6771166/4bbad2d2-d0e8-11e4-88ca-20e1e387f616.png)

**Comment by akmetainfo** [comment]
Вот ещё пример этого бага. Начинать заново модерирование в этом пуле уже вряд ли буду, так что можно посмотреть, как он самопроизвольно исчезает или просто как пример для устранения:
ID = 562544, линк http://opencorpora.org/pools.php?act=samples&pool_id=2615&ext&filter=disagreed&skip=15

**Comment by grandsbor** [comment]
Не воспроизводится у меня на 562544

**Comment by grandsbor** [comment]
В общем, я не могу это нигде воспроизвести, пока прикроем
