### ISSUE TITLE
Подозрение на ошибку снятия неоднозначности

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#217]
Проверить разбор слова "расстройства" в [предложении 41921](http://opencorpora.org/sentence.php?id=41921): на текущий момент размечено как sing+gent, хотя похоже это plur+accs.
Задание из [пула Существительное: единственное / множественное число #208](http://opencorpora.org/pools.php?act=samples&pool_id=469&ext&filter=disagreed)

**Comment by grandsbor** [comment]
cc @svbichineva

**Comment by akmetainfo** [comment]
Вот ещё выловил.
> 25572 Вот идёшь ты по улице , и что видишь вокруг ?
> [25573](http://opencorpora.org/sentence.php?id=25573) Банки , продуктовые магазины с бухлом , магазины со шмотками , банки , магазины со шмотками , салоны сотовой связи , банки...

Здесь слово "магазины" в именительном падеже, правильно - в винительном.
Размечалось в этом пуле: [Существительное, мн. ч.: именительный / винительный #19](http://opencorpora.org/pools.php?act=samples&pool_id=189&ext&skip=75)

PS Кто-нибудь, у кого есть права ставить метки -- пожалуйста, добавьте метку "словарь", искать стало тяжело после импорта issue из GoogleCode.

**Comment by akmetainfo** [comment]
Ещё подозрительный пример.
Вот это [предложение](http://opencorpora.org/sentence.php?id=41589), слово "уши" размечено как винительный падеж, при этом в [подобных случаях](https://groups.google.com/forum/?fromgroups#!topic/opencorpora-dev/lwDP2E1XAXA) мы определились, что все элементы [этого списка](http://opencorpora.org/books.php?book_id=1475&full#sen41582) находятся в именительном падеже.

**Comment by akmetainfo** [comment]
Ещё подозрительный пример.
Вот это [предложение](http://opencorpora.org/sentence.php?id=41589), слово "уши" размечено как винительный падеж, при этом в [подобных случаях](https://groups.google.com/forum/?fromgroups#!topic/opencorpora-dev/lwDP2E1XAXA) мы определились, что все элементы находятся в именительном падеже. Вот [исходный текст с закладкой на начале списка](http://opencorpora.org/books.php?book_id=1475&full#sen41582).

@grandsbor 
Дмитрий, технический вопрос, поясните. Для того, чтобы поправить разметку в архивном пуле -- нужна эта ссылка? Если нужна - то [вот ссылка на пул для этого примера](http://opencorpora.org/pools.php?act=samples&pool_id=72&ext&filter=focus&skip=285), если нет - напишите, я их не буду больше прикладывать.

**Comment by akmetainfo** [comment]
[Предложение 8979](http://opencorpora.org/sentence.php?id=8979) - мне было любопытно понять, "в кои-то веки" -- это тоже пример второго винительного или нет. Резануло то, что приписанный разбор - от слова "веко", а не "век". 
Причём, что странно: это точно не ошибка модератора, уже в самой первой версии текста есть только вариант "веко" (хотя слово "век" было добавлено в словарь корпоры раньше слова "веко" - если судить по цифрам в ID) - поэтому вероятно, могут попасться ещё подобные примеры.

**Comment by svbichineva** [comment]
расстройства, магазины, уши - поправила в корпусе
в парадигму слова век добавила - веки как вин устар. и поправила в корпусе

**Comment by grandsbor** [comment]
@akmetainfo Чтобы поправить разметку в архивном пуле, нужна только ссылка на предложение и описание ошибки.

Это если мы не правим ответ модератора в пуле (а мы этого не делаем и даже возможности нет, хотя это, конечно, чуть-чуть влияет на процент ошибок пользователей)

**Comment by grandsbor** [comment]
Кстати, все начальные слова (из АОТ) были добавлены в словарь одновременно, id выстроены по алфавиту. Корректнее смотреть на номер changeset-a, это первая колонка в истории правок лексемы.

**Comment by akmetainfo** [comment]
А, если ответы модератора не помечать неверными -- тогда да, всё через интерфейс предложения делается. Я думал, что это сложнее устроено.

Вот ещё пример несогласованности. 
В [этом пуле](http://opencorpora.org/pools.php?act=samples&pool_id=1818&ext&skip=90) разобрано как винительный, а [в этом пуле](http://opencorpora.org/pools.php?act=samples&pool_id=631&ext&filter=focus) разобрано в именительный. Надо привести к единому знаменателю. 
> Включает в себя острова Новосибирские , Вайгач , Врангеля , Карагин , Медный , Беринга , Диомида .
> новосибирский, ADJF, plur, nomn
> новосибирский, ADJF, inan, plur, accs

Тут на самом деле всё упирается в вопрос, насколько притянуто будет считать слово "острова" за родовое понятие.

**Comment by akmetainfo** [comment]
А вот этот как раз этот issue я уже почти созрел закрыть. (Ну, как "почти" -- осталось ещё 9 пулов проверить и тогда закрою). Ибо ошибки, которые проходят по текущим пулам нет сюда вписывать (их на модерации поправляем со Светланой), а прошлых пулов было-то совсем немного, похоже что больше и не будет ошибок подобного рода.
Через недельку надо будет не забыть закрыть issue.

**Comment by akmetainfo** [comment]
В [этом списке](http://opencorpora.org/books.php?book_id=1470&full#sen40978) элементы в винительном падеже, в то время как при модерации [пула#120](http://opencorpora.org/pools.php?act=samples&pool_id=905&ext&skip=135) слово "производство" размечено в именительный.
@svbichineva

**Comment by akmetainfo** [comment]
[В приговоре Пусси Райот есть список "что делать с вещ. доками"](http://opencorpora.org/books.php?book_id=2241&full#sen58479) - если внимательно дочитать до конца списка, то можно увидеть явно винительную конструкцию ("чёрную шапку - уничтожить"), в то же время при модерации всем элементам списка ставили именительный, т.к. уж очень похоже на предложение.
Предлагаю всем элементам списка проставить винительный. На текущий момент в двух предложениях ([58490, слово "нетбук"](http://opencorpora.org/sentence.php?id=58490) и [58494, слово "нетбук"](http://opencorpora.org/sentence.php?id=58494)) проставлен именительный, остальное пока модерируется (выловим при проверке).
@svbichineva

**Comment by svbichineva** [comment]
изменила "производство" и оба "нетбука"

15 апреля 2015 г., 11:04 пользователь Andrey <notifications@github.com>
написал:

**Comment by akmetainfo** [comment]
--- Выше этой строки Света уже выверила все примеры.

**Comment by akmetainfo** [comment]
Впрочем -- закрываю это issue. Пулы на именительный/винительный мн. ч. уже все закончились, поэтому врял ли что-то накопаю ещё (по кр. мере -- в ближайшие пару месяцев), а открытый таск лишь зря висеть будет.

**Comment by akmetainfo** [comment]
Предлагаю пересмотреть [предложение 34040](http://opencorpora.org/sentence.php?id=34040): изменить на неснимаемую.

> « Большой приз » состязания составит 1 млн долларов , а призы за второе и третье места — 300 и 200 тыс . долларов соответственно .

Проверялось в [пуле #5](http://opencorpora.org/pools.php?act=samples&pool_id=99&ext&filter=disagreed&skip=75)

Вот оба варианта прочтения предложения:

Награда (за первое место) составит тысячу долларов, а награда за второе и третье место - тысячу лир и тысячу рупий соответственно.

Награду (за первое место) составит одна тысяча долларов и новенькая иномарка, а награду за второе и третье место -- тысяча франков и тысяча гульденов соответственно.

Может я чего не вижу, но по мне вполне типичный образчик "рэп загрушает звук мотора".

@svbichineva

**Comment by svbichineva** [comment]
Что скажет Дима, я бы оставила им

Best,
Svetlana Alexeeva

**Comment by akmetainfo** [comment]
Ещё [сомнительное место](http://opencorpora.org/sentence.php?id=6574) -- вполне возможно, что стоит убрать именительный и поставить неснимаемую. Причина -- можно задать вопрос от глагола "пишу" вовнутрь скобок и винительный имеет равные права с именительным:

>  	контекст « Я пишу о смерти ( « Обмен » ) — мне говорят , что я пишу о быте ; я пишу о любви ( « Долгое прощание » ) — говорят , что тоже о быте ; я пишу о распаде семьи ( « **Предварительные** итоги » ) — опять слышу про быт … »
>
>    предварительный, ADJF, plur, nomn
>    предварительный, ADJF, inan, plur, accs


Модерировалось [раз](http://opencorpora.org/pools.php?act=samples&pool_id=100&ext&filter=disagreed&skip=30), [два](http://opencorpora.org/pools.php?act=samples&pool_id=2026&ext&skip=120).

**Comment by svbichineva** [comment]
Я бы оставила имен, опять, что скажет Дима

2 мая 2015 г., 18:50 пользователь Andrey <notifications@github.com> написал:

**Comment by grandsbor** [comment]
Я согласен со Светой в обоих последних примерах

**Comment by akmetainfo** [comment]
Хорошо, закрываю этот issue.

**Comment by akmetainfo** [comment]
В [-DEV обсуждали](https://groups.google.com/forum/#!topic/opencorpora-dev/UN8q_nJQP2g), что в [предложении 39881](http://opencorpora.org/books.php?book_id=1417&full#sen39881) неснимаемая. На одном из слов ("пинки") по-прежнему остался именительный, пул уже успели сдать в архив, поэтому не могу поправить.

**Comment by akmetainfo** [comment]
Предлагаю дополнительно проверить фрагмент про [города республиканского значения](http://opencorpora.org/books.php?book_id=3298&full#sen78647).
Склоняюсь к мысли, что везде нужно ставить слову "города" единственное число (sing+gent). 
На текущий момент из трёх правок в архиве два раза проставлено единственное число ([тут](http://opencorpora.org/sentence.php?id=78648) и [тут](http://opencorpora.org/sentence.php?id=78650)), один раз -- множественное ([тут](http://opencorpora.org/sentence.php?id=78653)).
Альтернатива - на первом предложении ([78648](http://opencorpora.org/sentence.php?id=78648)) оставить единственное число, остальным вхождениям проставить неснимаемую. Мне этот вариант нравится много меньше.

Я вижу структуру предложения так:

>  5) координирует деятельность областных заведений (<заведений> города республиканского значения, <заведений> столицы);

**Comment by svbichineva** [comment]
оба примера исправила

**Comment by akmetainfo** [comment]
Закрываю, пока подозрительных примеров не осталось.

**Comment by akmetainfo** [comment]
Как и [обсуждали предложение "одни плевки в наш адрес"](https://groups.google.com/forum/?fromgroups#!topic/opencorpora-dev/lo3QzQ7z_MM) - нужно поставить "винительный, частично правильно". (Один из пулов уже ушёл в архив - у меня прав нет)

**Comment by svbichineva** [comment]
В интерфейсе для ручной разметки я не могу поставить Частично правильно, поэтому лучше давайте прилагательному "одни" поставим им + частично правильно (как у слово плевки), а потом на этапе просмотра случаев с Частично правильно мы измени на вин

Best,
Svetlana Alexeeva

**Comment by akmetainfo** [comment]
Хорошо, пусть оба остаются пока в именительном. Поправил, добавил комментарий к предложению.
Выше снова нет примеров на корректировку, закрываю таск.

@svbichineva
