### ISSUE TITLE
поправить слова с Dist

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#24]
Мне кажется, там много "странных" разборов. 

* "Барби" - почему-то все разборы с Dist, у некоторых форм по 2 пометы Dist;
* "болит",  "болящая" - почему с Dist? "болит рука"
* "заболели", "переболели", "поболит", "разболелись" - почему с Dist?
* "броней", "бронею" - есть ли смысл добавлять варианты без ё с пометкой Dist (см. формы единственного числа) - нигде больше этого не делается?
* "саввишна" и т.д. - почему-то это единственное отчество (от имени "Савва"), для которого указано Dist. Это, может, и OK, но все равно странно - для более популярных имен вариантов с Dist ("Ильинишна", ...) нет.

**Comment by svbichineva** [comment]
Разобралась с барби и саввишной

**Comment by svbichineva** [comment]
Исправила глаголы поля "боль".
С броней ситуация тяжелая. Есть два омонима БрОня и БронЯ. В одном случае ё нет в форме тв падежа, во втором --- есть. Миша, как работает pymorphy2? Если слово явно написано ё, то онине пытается предложить разбор с е? У нас вроде бы оба разбора припишутся.

**Comment by kmike** [comment]
Спасибо! 

> Миша, как работает pymorphy2? Если слово явно написано с ё, то он не пытается предложить разбор с е?

Ага. 

варианты в словаре | разбираемое слово | предлагаемые разборы
-----------------------------|---------------------------|----------------------------------
только с е | ..е.. | только с е
только с ё | ..е.. | только с ё
е, ё | ..е.. | е, ё
только с е| ..ё.. | ничего
только с ё| ..ё.. | только с ё
е, ё| ..ё.. | только с ё

**Comment by svbichineva** [comment]
Tо, что надо. Убираю Dist. Тогда если напишут "бронёй" получат один вариант, а если "броней", то два (под разные омонимы)
