### ISSUE TITLE
добавить несклоняемый вариант Домодедово

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#35]
Привет. 

С [gramota.ru](http://gramota.ru/spravka/buro/search_answer/?s=%E4%EE%EC%EE%E4%E5%E4%EE%E2%EE):

> Вопрос № 265259 	 
> склоняется ли аэропорт "Домодедово"? Например, в "Домодедове"??? Спасибо!
    Шаповалова Н.

> Ответ справочной службы русского языка

> Название не склоняется в сочетании с родовым словом: в аэропорту Домодедово (названия аэропортов рекомендуется писать без кавычек). Если же родового слова нет, то нормативны оба варианта, склоняемый и несклоняемый: в Домодедове и в Домодедово. При этом склоняемый вариант соответствует строгой литературной норме (и рекомендуется, например, для речи дикторов). Подробнее см. в рубрике «Азбучные истины».

В словаре сейчас только склоняемый вариант. Люди жалуются, просят добавить несклоняемое Домодедово.

**Comment by akmetainfo** [comment]
Встречаются, да. "Как представители Аэрофлота общались с людьми из Пулково я опущу" и т.п.

**Comment by svbichineva** [comment]
нашла еще пример  "в случае признания Косово"
Я наверное добавляю неизм варианты трех упомянутых слов (Домодедово, Пулково, Косово) в виде разг вариантов внутри парадигмы. 
Какие слова еще добавить? Лучше бы не все подряд, а которые встречаются в корпусе

**Comment by akmetainfo** [comment]
Это самые частотные. Скоро буду проходить пул на неизменяемые существительные -- буду иметь ввиду, потом допишу сюда наиболее частотные примеры, может быть что-то ещё встретится из подобных примеров.
По факту же: у нас в стране аэропортов много (см. например [список на википедии](https://ru.wikipedia.org/wiki/%D1%EF%E8%F1%EE%EA_%E0%FD%F0%EE%EF%EE%F0%F2%EE%E2_%D0%EE%F1%F1%E8%E8)), но из тех, что на слуху в прессе -- не так и уж и много. Это как раз все три московских аэропорта (Шереметьево, Домодедово, Внуково) и один питерский (Пулково). Есть ещё какой-то аэропорт "Остафьево" в Москве , но в корпусе не встречается и прожив в москве десяток лет не могу утверждать, что слышал такое название.

**Comment by svbichineva** [comment]
Добавила раз варианты для:
Пулково, Внуково, Шереметьево, Домодедово, Косово, Гугл, интернет

**Comment by kmike** [comment]
А там точно Infr? 

Поискал новости по Пулково - везде несклоняемый вариант, например http://rusnovosti.ru/posts/361253, http://www.fontanka.ru/2015/01/21/038/ и https://news.mail.ru/inregions/st_petersburg/91/economics/20584748/. Склоняемого варианта как минимум в новостях сейчас нет.

Внуково - тоже самое, везде только несклоняемый вариант: http://www.rg.ru/2015/01/21/tablo-site-anons.html, http://top.rbc.ru/business/17/01/2015/54baa9559a79476aa5b1c24d, http://www.interfax.ru/tourism/tourisminf.asp?sec=1470&id=419646

Косово - встречается оба варианта, но несклоняемый чаще - http://lenta.ru/news/2014/12/26/hitler_from_kosovo, http://24.kz/ru/news/in-the-world/item/46719-shakhtery-kosovo-bastuyut-pod-zemlej, http://ria.ru/world/20141226/1040334947.html

Шереметьево - встречаются оба варианта, несклоняемый вроде чаще - http://www.aif.ru/society/healthcare/1427659, http://www.ntv.ru/novosti/1290818/ (но http://itar-tass.com/ekonomika/1712624)

Домодедово - чаще несклоняемый (склоняемого в новостях не видел) - http://www.kommersant.ru/doc/2651795, http://www.rbc.ru/rbcfreenews/54c2017d9a79477e2c209ca3, http://www.m24.ru/articles/64732?attempt=1

Из личного опыта - у нас в городе аэропорт Кольцово (пятый по обороту после московских и питерских, кстати) и одноименный район. Никогда не слышал, чтоб их кто-то склонял, ни в устной речи, ни в новостях. В словаре OpenCorpora - только склоняемый вариант.

**Comment by svbichineva** [comment]
У нас в словаре есть ограничение, что в парадигме не может быть двух одинаковых разборов (есть исключения, но это очень маленький список). Пока по справочниках по русской орфографии считается, что склонять надо (строгая норма), поэтому я и поставила infr. Конечно, частотность сейчас в противоположную сторону, тогда  тому, что сейчас с infr надо ставить основной, а второму варианту устар. Но как-то это идет в разрез с предписаниями. Чем плохо, что стоит разг. У кого-то генерация работает не как хотелось бы?

**Comment by grandsbor** [comment]
Кажется, тут всё сделано
