### ISSUE TITLE
Поправить и включить функции, влияющие на токенизацию

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#49]
Отключены [этим коммитом](https://github.com/OpenCorpora/opencorpora/commit/49271ca2b68b1b0b2592a0c867af8c3a999d0065)

**Comment by vbocharov** [comment]
Дима, сделай, пожалуйста, этот тикет. Хочется навести порядок в токенизации и делении на предложения.

**Comment by grandsbor** [comment]
Поправил частично. Сейчас можно разбивать-склеивать предложения

**Comment by vbocharov** [comment]
Спасибо!
Сработало пока везде, кроме предложения 69095 (пытался поделить по первому восклицательному знаку).

**Comment by vbocharov** [comment]
Как удалить границу абзацев?

Пример проблемы:
http://opencorpora.org/books.php?book_id=671&full#sen25444

**Comment by vbocharov** [comment]
И, вот ещё один пример, с которым непонятно, что делать:

http://opencorpora.org/books.php?book_id=1865&full

Там порядок должен быть 14, 15, 27, 28. Но что-то пошло не так.

**Comment by grandsbor** [comment]
В предложении 69095, как и намекает текст ошибки, есть разметка named entities, пока такие предложения не будут разбиваться

**Comment by grandsbor** [comment]
Сделал возможность склеивать абзацы, твой пример склеил (но только абзацы, предложения не трогал).

**Comment by grandsbor** [comment]
Последний пример поправил в базе. Попробую понять, что пошло не так.

**Comment by grandsbor** [comment]
Включил все функции обратно, можно пробовать
