### ISSUE TITLE
Генератор корпуса со снятой омонимией по немодерированным пулам

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#537]
Original [issue 367](https://code.google.com/p/opencorpora/issues/detail?id=367) created by OpenCorpora on 2012-11-08T15:06:19.000Z:

Скрипт, удаляющий омонимы из разборов при помощи данных из ещё неотмодерированных пулов.

**Comment by grandsbor** [comment]
@gisly 
Меня смущает, что в выходном файле получается одна огромная строка. Там нет настройки типа `pretty-output`?

**Comment by gisly** [comment]
@grandsbor Настройки, к сожалению, нет. Могу просто делать отступы вручную при формировании XML.

**Comment by grandsbor** [comment]
Ну, было бы неплохо, потому что, например, некоторая статистика считается
по дампам, и там используется то, что каждый токен на новой строке, чтобы
вообще не парсить xmlqq

**Comment by gisly** [comment]
закоммитила (в свой fork) версию с переносом на новую строку: думаю, полноценный pretty-print  с разным количеством отступов — это не так важно?

**Comment by grandsbor** [comment]
Не знаю пока, надо проверить

**Comment by gisly** [comment]
А как можно проверить? Какой-то скрипт прогнать?

**Comment by grandsbor** [comment]
Ага, нужно проверить, что [вот этот скрипт](https://github.com/OpenCorpora/opencorpora/blob/master/scripts/stats/update_stats.pl) адекватно считает статистику по дампу. Не уверен, что вы этого хотите :)

**Comment by grandsbor** [comment]
Вообще, даже проще. Надо проверить, что верно считаются вот эти три функции:

    sub sentences_in_file {
        return `bzcat $_[0] | grep -c '<sentence '`
    }
    sub tokens_in_file {
        return `bzcat $_[0] | grep -c '<token '`
    }
    sub words_in_file {
        return `bzcat $_[0] | grep '<token ' | grep -Eo 'text="[^\"]+"' | cut -d\\" -f2 | grep -v '[[:punct:]]' | grep -civ '[a-z0-9]'`
    }

**Comment by grandsbor** [comment]
Что-то я не то написал. Этот скрипт же никак не влияет на число предложений или токенов, так что он годен.
Но зато к нему в пару нужен ещё скрипт, который будет стирать предложения, в которых есть неоднозначные токены.

**Comment by gisly** [comment]
Проверила, что на исходном дампе и на результате работы скрипта
`bzcat  | grep -c '<sentence '` и `bzcat  | grep -c '<token '` выдают одно и то же

Элементы paragraph тоже надо стирать, если в них все предложения неоднозначные?

**Comment by gisly** [comment]
и аналогичный вопрос про text, где все предложения неоднозначны

**Comment by grandsbor** [comment]
paragraph стирать, text оставлять

**Comment by gisly** [comment]
скрипт закоммитила в форк: https://github.com/gisly/opencorpora/commit/727a442e765af3463685ee94c4df9810b1f2f996

Обнаружила ошибку в первоначальном скрипте:
может быть так, что в тексте токен вообще не имеет неоднозначности, но был при этом включен в пул, и разметчики выбрали не тот вариант, который был в тексте.
Пример: текст 2, токен 165; текст 2241, токен 1067135. В обоих случаях для "и" в текстах стояло INTJ, а разметчики выбрали CONJ. Может быть, дело в рассинхронизированности дампов текста и пулов?
Прежняя версия скрипта вообще не создавала лексемы в таких случаях. Теперь создаю лексему, которую заполняю вариантами разметчиков. Также на всякий случай печатаю идентификаторы таких токенов.

**Comment by grandsbor** [comment]
В описанном варианте надо выбирать вариант из дампа. Вариант, который
выбрали разметчики, может, уже вообще не существует. Пулу может быть года
три :-)

**Comment by gisly** [comment]
А, тогда переделаю.

**Comment by gisly** [comment]
переделала, беру из дампа теперь

**Comment by grandsbor** [comment]
Отлично, давайте пулл-реквест

**Comment by grandsbor** [comment]
Ура, вроде работает
