### ISSUE TITLE
только - наречие?

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#574]
Original [issue 406](https://code.google.com/p/opencorpora/issues/detail?id=406) created by OpenCorpora on 2013-10-28T03:34:29.000Z:

Привет. В викисловаре пишут, что &quot;только&quot; может быть наречием, и примеры приводят (http://ru.wiktionary.org/wiki/%D1%82%D0%BE%D0%BB%D1%8C%D0%BA%D0%BE). В других местах тоже вроде как наречие разбирают иногда. В OpenCorpora - частица или союз. Если это специально, то есть какая-нибудь инструкция, где бы было сказано, как &quot;только&quot; разбирать? Если не специально, может, поправить?

**Comment by svbichineva** [comment]
добавила наречие
