### ISSUE TITLE
[proposal] Новые шрифты

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#58]
Решил немного поэкспериментировать со шрифтами, используемыми на сайте, с целью сделать внешний вид приятнее и читабельнее. Вот что из этого получилось:

![2014-08-17 19 32 37](https://cloud.githubusercontent.com/assets/1223831/3944999/de43052a-2625-11e4-986a-027fcbf0c9d3.png)

![2014-08-17 19 49 11](https://cloud.githubusercontent.com/assets/1223831/3945004/2b11e2fe-2626-11e4-96f2-99df0a1951d3.png)

Если это выглядит хорошо (\сс @svbichineva, @yourmary, @victorbocharov, @irinfox), можно закоммитить и выкатить.

**Comment by grandsbor** [comment]
Переоткрывайте, если будет что-то новое
