### ISSUE TITLE
Добавить сокращения вроде "млн", "г" и т.д. в словарь

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#580]
Original [issue 412](https://code.google.com/p/opencorpora/issues/detail?id=412) created by OpenCorpora on 2013-10-30T06:21:33.000Z:

У меня есть скрипт, который разбирает доступную часть НКРЯ с помощью pymorphy2 и смотрит на ошибки (теги соотносятся с помощью большой самопальной функции). Вышло примерно 6000 токенов, для которых pymorphy2 не нашел верного варианта, часть из них - на самом деле не ошибки, а различия между подходами в НКРЯ и OpenCorpora, т.е. настоящих ошибок меньше. 

Так вот, из этих 6000 на долю сокращений вида &quot;млн&quot;, &quot;г&quot;, &quot;тыс&quot;, &quot;т.д&quot; и т.д. приходится 1300. Так что, просто добавив эти слова в словарь, можно полноту разбора сильно повысить. 

Это самый большой класс ошибок, который, к тому же, проще всего исправляется. Для сравнения, ошибок в аббривеатурах (ГКРФ) - примерно 900, в инициалах (В. В. Пу) - 550, в фамилиях - 450, именах (&quot;Серёжа&quot;) - 200.

**Comment by svbichineva** [comment]
дошла пока до напр

**Comment by grandsbor** [comment]
Света, а ты проверяешь, что добавляемого слова ещё нет? А то сейчас вот стало две леммы "мг"

**Comment by svbichineva** [comment]
я проверяю, но это слово просмотрела :( спасибо

**Comment by grandsbor** [comment]
Света и Миша, как вы думаете: может быть, в случаях, когда одно и то же сокращение подходит к двум существительным разного рода (допустим, т: том и тонна), ставить таким сокращениям GNdr? Чтобы не плодить омонимию. И аналогично с одушевлённостью, ставить ANim (о: отец и остров).

**Comment by svbichineva** [comment]
Я наверное за то, что бы оставить как есть. Вроде бы, эту омонимию легко
снять

25 июня 2015 г., 21:54 пользователь Dmitry Granovsky <
notifications@github.com> написал:

**Comment by svbichineva** [comment]
я просмотрела список и добавила то, что показалось нужным. Посмотрите, может быть что-то важное упустила. Еще боюсь при проставлении связи могла забыть поменять направление на правильное, так что было бы хорошо проверить (там где Full, не должно быть Abbr)

**Comment by grandsbor** [comment]
Давайте закроем, если что, по ситуации ещё добавим
