### ISSUE TITLE
Варианты окончания им.п. мн.ч. -И/-А

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#585]
Original [issue 417](https://code.google.com/p/opencorpora/issues/detail?id=417) created by OpenCorpora on 2013-11-06T10:17:02.000Z:

Распространенные варианты вида тракторы - трактора, цехи - цеха, бухгалтеры - бухгалтера и т.п. представлены в словаре очень непоследовательно - лишь у отдельных слов (примерно с десяток). А их, возможно, сотни.

Хотелось бы, чтобы все такие варианты были описаны (эта информация есть в Зализняке), причем было указано, какой из вариантов нормативный.

Пары вида ордены - ордена, образы - образа следует разделить на две статьи, т.к. они имеют разный смысл.

**Comment by grandsbor** [comment]
cc @svbichineva Закроем?

**Comment by grandsbor** [comment]
@svbichineva @Shimorina 
закроем? :)

**Comment by svbichineva** [comment]
да
