### ISSUE TITLE
"полвека" может быть мужского рода

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#612]
* полвека в смысле "половина века(столетия)" - мужской род
* полвека в смысле "половина века(части тела)" - средний род

Сейчас в словаре только вариант со средним родом.

**Comment by kmike** [comment]
Кстати, а почему "полгода" - среднего рода? Год - он, а по тому, как слово согласуется - не понять ничего, т.к. там множественное число вылезает. 

Еще кстати - раз слово участвует в конструкциях, как слово множественного числа, то может множественное число ему и проставить?

**Comment by akmetainfo** [comment]
С трудом могу представить контекст в котором говорится о половине такой части тела как веко, это явно что-то синтетическое.

**Comment by svbichineva** [comment]
Полвека забылось --- пример из вин словаря 
Полгода прошло --- пример с Грамоты.
(Помимо варианта с мн. ч). Таким образом, видно, что слова ср. Рода

**Comment by grandsbor** [comment]
Вообще кажется, что "пол-что-угодно" всегда среднего рода:
- полдома было отдано брату (а не "был отдан")
- полстраны пришло в запустение (а не "пришла")

Миша, ты согласен?

**Comment by grandsbor** [comment]
Будем считать, что никто никого не убедил
