### ISSUE TITLE
DB Error после переезда на другой сервер

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#613]
После переезда на другой сервер на большинстве страниц DB Error. Словарь пустой, задания на разметку выдают ошибку. Похоже, что-то поломалось при миграции.

**Comment by grandsbor** [comment]
Проблемы есть, чинятся

**Comment by grandsbor** [comment]
cc @victorbocharov

**Comment by grandsbor** [comment]
Те ошибки, которые я видел, я починил и отключил ридонли. Есть ещё - пишите

**Comment by akmetainfo** [comment]
Лучше выключите ридонли. У меня под двумя логинами продолжаются ошибки - см. подробности в почте. И это явно не только ошибки контекста ( #614 ).

**Comment by grandsbor** [comment]
Похоже, это таки были только #614

**Comment by akmetainfo** [comment]
Разметка заработала, проверил. Модерирование тоже работает - взял в работу новый пул, проверил десяток примеров.
По идее, можно закрывать.
