### ISSUE TITLE
А мы еще используем jquery-ui?

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#615]
Заметил, что в templates/common.tpl до сих пор подключается jquery-ui (и тема smoothness). А мы еще реально используем его где-то? Пробовал найти коммит, где появился jquery-ui, с помощью blame, но так и не дошел до конца :)

**Comment by grandsbor** [comment]
Судя по всему, последним эту строчку менял ты в [этом коммите](https://github.com/OpenCorpora/opencorpora/commit/e3f7deea69631f609d8f63189084b8f0e2841e48#diff-e746b3685faeb779fa7dd9fa77b0c80cL18)

**Comment by grandsbor** [comment]
Выпилил локально - ничего необычного не заметил.
Так что выпилил в продакшене, пока не коммичу. Заметите что-то не то - пишите

**Comment by madfriend** [comment]
я только инкрементил версию, вместе с jquery :)

26.03.15, Dmitry Granovsky<notifications@github.com> написал(а):

**Comment by madfriend** [comment]
вот откуда оно тянется: https://github.com/OpenCorpora/opencorpora/commit/ce0882b0cfff2023ccc132376c350536208ff317

**Comment by madfriend** [comment]
и где используется: https://github.com/OpenCorpora/opencorpora/blob/8fd3f23b46e52ae6c8a417900fe30585652cdfb5/templates/tokenizer_monitor.tpl (datepicker)

**Comment by grandsbor** [comment]
Сможешь заменить?
Le 27 mars 2015 22:33, "Alex Chuchunkov" <notifications@github.com> a écrit
:

**Comment by madfriend** [comment]
Выпилил в этом коммите: https://github.com/OpenCorpora/opencorpora/commit/084724368199f84f3098ab3d38faf5c8b18feeda

Надо посмотреть на tokenizer_monitor.php, работает ли все, как нужно (у меня доступа нет)

**Comment by grandsbor** [comment]
Выкатил, вроде работает
