### ISSUE TITLE
Сделать новые ачивки (бэкенд)

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#617]
Завел тикет, чтобы следить за прогрессом.

Дима, как успехи с бэкендом? Ты будешь вносить какие-то изменения в ту схему, которая есть сейчас или нет? Если да, то я повременю с user_splash.tpl.

**Comment by grandsbor** [comment]
Да, буду

**Comment by madfriend** [comment]
Переехали в PR https://github.com/OpenCorpora/opencorpora/pull/629
