### ISSUE TITLE
Русские -> UNKN

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#620]
@grandsbor 

Дима, посмотри, как такое технически оказалось возможным и не повторится ли ещё где:

В двух словах: словоформа ID=310319 ("русский") сброшена в UNKN, хотя в словаре есть ещё такая же словоформа D=310321 русский ADJF.

Подробнее: [пример из пула #51](http://opencorpora.org/pools.php?act=samples&pool_id=2184&ext&filter=not_ok)

> [контекст](http://opencorpora.org/books.php?book_id=305&full#sen15867) Просто не знаю , не будут фыркать **русские** на армян ещё больше ...
>    русские, UNKN

[History](http://opencorpora.org/history.php?sent_id=15867): [изменил Робот 01.05.2013, 03:56 Комментарий: Update tokens from dictionary](http://opencorpora.org/diff.php?sent_id=15867&set_id=10819)

PS Кстати, если уже читал [эту тему](https://groups.google.com/forum/?fromgroups#!topic/opencorpora-dev/4e9ZMB2pUJA) -- то может ты добавишь разбор и я сразу посмотрю добавит ли варианты разбора, чтобы я не ставил other + нет верного разбора?

**Comment by akmetainfo** [comment]
То же самое ещё раз со словом "русские": 
http://opencorpora.org/pools.php?act=samples&pool_id=2199&ext&filter=not_ok

Сообразил. Вот она [история удалённой леммы](http://opencorpora.org/dict_history.php?lemma_id=310319). Светлана 03.04.2013 удалила лемму-дубликат ("русская", осталось только "русский") и ночью  01.05.2013 прошёлся робот и сбросил в ноль разбор.

Вопрос возникает такого характера: а почему не подхватилась лемма "русский" вместо "русская"? Или это следы каких-то давних, уже исправленных ошибок?

**Comment by grandsbor** [comment]
А почему, кстати, в обоих случаях стоит "Нет правильного разбора"? Люди же ответили верно

**Comment by grandsbor** [comment]
А вообще так получилось потому, что
- сначала при модерации были почему-то [удалены](http://opencorpora.org/diff.php?sent_id=18768&set_id=8511) разборы с леммой "русский"
- потом была удалена из словаря вторая лемма "русская", тем самым доступных разборов не осталось

**Comment by grandsbor** [comment]
Оба примера я поправил, спасибо.

Вообще если есть желание сделать ревизию всех UNKN, для которых в словаре есть хотя бы один разбор - welcome :-)

**Comment by akmetainfo** [comment]
> А почему, кстати, в обоих случаях стоит "Нет правильного разбора"? 
> Люди же ответили верно
Чтобы оранжевым загорелось и пример точно попал к постмодератору. 
Частично правильно не попадают в фильтр, который not_ok -- я уже где-то писал об этом.
Оба примера поправил - они ещё не в архиве, у меня есть право их править.

**Comment by akmetainfo** [comment]
> Вообще если есть желание сделать ревизию всех UNKN, 
> для которых в словаре есть хотя бы один разбор - welcome :-)

Если мне какая-то нестыковка попадается в корпусе (когда размечаю, либо проверяю пулы) -- я о ней всегда найду куда написать. Где-то в гитхаб (в принципе, все таски я уже знаю "в лицо"), где-то в комментарии для модератора, в предложение...

А как сделать ревизию всех UNKN для которых есть один разбор -- я не знаю как. Есть какой-то готовый фильтр? Или нужно сначала подумать, как написать запрос к базе?

**Comment by grandsbor** [comment]
Зачем база, есть же дамп.

**Comment by akmetainfo** [comment]
А, ну да. grep'овскими регулярками по дампу. В принципе, вариант.

**Comment by akmetainfo** [comment]
Хотя нет, не поможет. Корпус делится на промодерированную часть корпуса (дамп) и непромодерированную (задания на разметку). Можно убедиться, что в дампе всё ок.
(Ну реально, выверенный корпус выверен очень хорошо: на три двушечки один оранжевый ответ (личная статистика), в архивных пулах ошибки ещё более редки)
А вот немодерированная часть корпуса -- там-то бы формулку и запускать... Но такие примеры и глазами сразу видно. А потому смысл проводить подтверждающую инвентаризацию (что вот тут всё хорошо, как мы и думали) небольшой -- это примерно как искать потерянный пятак там,. где светло, а не там где потеряли?
