### ISSUE TITLE
Подсвечивать в тексте выделенное предложение

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#621]
Когда открываешь ссылки на контекст - то сразу не найти глазами предложение, на котором установлен якорь ссылки. 
Касается только случаев, когда предложение находится в конце текста и браузер не может поднять предложение на самый верх: [пример](http://opencorpora.org/books.php?book_id=3389&full#sen89921). А в начале текста нормально - просто смотрим наверх страницы: [пример](http://opencorpora.org/books.php?book_id=3389&full#sen89812)

Давайте подсвечивать выделенное предложение. Хороший пример - сайт гитхаба в показе исходников ([пример](https://github.com/OpenCorpora/opencorpora/blob/master/templates/stats.tpl#L18)), также и у нас есть пример, когда в статистике подсвечивается желтым строка залогиненного пользователя ([образец ссылки](http://opencorpora.org/?page=stats&weekly#user398), [подсвечивается так](https://github.com/OpenCorpora/opencorpora/blob/master/templates/stats.tpl#L18)).

Для чего нужно думаю объяснять не стоит. Упростит работу модератора, когда он кликает на просмотр контекста.

Достаточно даже слабого выделения, не обязательно прямо всю строку заливать фоном (не будет видно маркеры токенов)

**Comment by madfriend** [comment]
Подсвечивается же. Может, в браузере дело? Скрин в последнем хроме (первая ссылка):
![2015-04-06 14 35 09](https://cloud.githubusercontent.com/assets/1223831/7003821/c8d08afa-dc69-11e4-9bda-96286fea84ee.png)

**Comment by akmetainfo** [comment]
О как... В FF (последней стабильной версии за последний год) никогда не видел подсветки.
Открыл ради интереса в IE 11 -- тоже нет подсветки.
Согласен на browser-specific, хотя может быть дело в специфичных правах (как недавно столкнулись с кнопками раскрытия контекста слева и справа).

**Comment by akmetainfo** [comment]
Не согласен на browser-specific ;) Нашёл виртуалку с хромом, обновился до последней версии -- у меня не показывает жёлтую рамку (ни под анонимом, ни под пользователем, ни с модераторскими правами).
Похоже, дело в правах. Если так -- предлагаю дать возможность и незалогированным пользователям видеть подсветку.

**Comment by akmetainfo** [comment]
Ага, в правах дело: https://github.com/OpenCorpora/opencorpora/blob/master/templates/book.tpl#L4
Предлагаю разбить скрипт на две части: где нужно проверить на user_permission_adder и на отрисовку указателя.

**Comment by madfriend** [comment]
сделаете пулл-реквест?

06.04.15, Andrey<notifications@github.com> написал(а):

**Comment by irinfox** [comment]
Погодите, а этот интерфейс разве вообще доступен незалогиненым
пользователям?

Я помню, что на добавление текстов, например, нужно было просить права.
Если это тот же интерфейс, то отрисовывать всем-всем не надо.

6 апреля 2015 г., 15:57 пользователь Alex Chuchunkov <
notifications@github.com> написал:

> сделаете пулл-реквест?
>
> 06.04.15, Andrey<notifications@github.com> написал(а):
> > Ага, в правах дело:
> >
> https://github.com/OpenCorpora/opencorpora/blob/master/templates/book.tpl#L4
> > Предлагаю разбить скрипт на две части: где нужно проверить на
> > user_permission_adder и на отрисовку указателя.
> >
> > ---
> > Reply to this email directly or view it on GitHub:
> >
> https://github.com/OpenCorpora/opencorpora/issues/621#issuecomment-90028893
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/621#issuecomment-90052243>
> .
>



-- 
Ирина

**Comment by akmetainfo** [comment]
Нет, недоступен. И у меня залогиненного он не показывается. И показываться будет по-прежнему с сохранением условия. Доберусь до машины с корпорой -- сделаю пулл-риквест, а пока только ещё раз отправлю к предыдущему сообщению, я там дописывал что и как поменять в коде.
Вкратце: проверка user_permission_adder остаётся, интерфейс этот остаётся только для тех, у кого есть права. А за пределы условия выносится строка где addClass('bgyellow') или как там.

**Comment by akmetainfo** [comment]
https://github.com/OpenCorpora/opencorpora/pull/623
@madfriend

**Comment by akmetainfo** [comment]
Теперь и у меня заработала подсветка в FF.
