### ISSUE TITLE
Ошибки автоматического разбора (нет нужных слов в словаре)

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#622]
Даже не уверен, что эти баги в ближайшее время будут правиться, потому что все эти кейсы требуют добавления слов в словарь (читай: увеличивают парадигму, количество заданий на разметку). И тем не менее, пока попадаются на глаза -- буду скидывать в это issue.

[Предложение 69304](http://opencorpora.org/sentence.php?id=69304), слово "молочка" автоматически разобралось как sing+gent, хотя правильно plur+nomn, потому что в словаре нет слова "молочка, NOUN, femn" (сокращение от "молочная продукция")

**Comment by grandsbor** [comment]
Нет, почему же, в словарь мы быстро добавляем. До заданий это, конечно, нескоро доедет

**Comment by akmetainfo** [comment]
Зря закрыли. Ладно, найду следующий кейс такого типа - впишу сюда и попрошу переоткрыть.

**Comment by grandsbor** [comment]
А что, переоткрыть не хватает прав?

**Comment by akmetainfo** [comment]
Не хватает. А должно хватать? Вот в akmetainfo\opencorpora вижу кнопку "Reopen" рядом с "Comment", в основном репозитории корпоры - недоступна. Ещё метки не даёт менять и проставлять Assignee при заведении таска.

**Comment by grandsbor** [comment]
Ну можно писать сюда или в новый тикет, неважно

**Comment by akmetainfo** [comment]
OK, если появится -- буду сюда писать. Просто удобнее, когда подобные вещи сгруппированы, как например #110 - это одно issue, а не десяток.
