### ISSUE TITLE
Не открывается словарь на чистой установке

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#624]
Вспомнил сегодня про свою виртуалку с чистой корпорой ;)

На чистой установке не открывается /dict.php, выдаёт DB Error.

![dict_lemmata](https://cloud.githubusercontent.com/assets/6085279/7010618/50db92be-dcab-11e4-99b5-4da575c75250.png)

Ругается на 
````sql
SELECT COUNT(*) AS cnt_l FROM `dict_lemmata` WHERE deleted=0
````

Вызывается [отсюда](https://github.com/OpenCorpora/opencorpora/blob/master/lib/lib_dict.php#L11), а поле [deleted таблицы dict_lemmata в дистрибутиве базы](https://github.com/OpenCorpora/opencorpora/blob/master/migrations/initial_schema.sql#L164) и правда отсутствует. Надо поправить инсталлятор.

**Comment by grandsbor** [comment]
cc @madfriend 
Так сверху инсталлятора надо запускать все миграции.

**Comment by madfriend** [comment]
Это поле добавлено в этой миграции: https://github.com/OpenCorpora/opencorpora/blob/master/migrations/20150216164636_undelete_lemmata.php

Соответственно, при чистой установке `phinx migrate` должен ее тоже подхватывать.

**Comment by madfriend** [comment]
Скорее всего, на "виртуалке с чистой корпорой" не делали `git pull; vendor/bin/phinx migrate` после того, как добавили новую миграцию.

**Comment by akmetainfo** [comment]
А ведь Саша прав. Это не совсем "чистая" корпора, забыл миграцию накатить.
Всё, тут же пропал баг после phinx migrate.
