### ISSUE TITLE
При автозаполнении парадигмы не заполняются граммемы леммы

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#625]
Остаётся тот же селект со словом "граммемы".

**Comment by grandsbor** [comment]
Выкатил, ничего не изменилось (Я.Браузер 14.5)

**Comment by madfriend** [comment]
Ты про вот это?

![2015-04-25 18 13 15](https://cloud.githubusercontent.com/assets/1223831/7333377/5eca841e-eb76-11e4-9843-82e078084b0a.png)

**Comment by grandsbor** [comment]
Ага, про это. Теперь работает
