### ISSUE TITLE
Отправляются пустые комментарии

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#626]
Не закрыта взможность отправлять пустые комментарии.
Вот [два образца](http://opencorpora.org/pools.php?act=samples&pool_id=1907&ext&filter=comments):

> [контекст](http://opencorpora.org/books.php?book_id=248&full#sen14151) Вот смотрим « Идеальный незнакомец » .
>
>    идеальный, ADJF, Qual, masc, sing, nomn
>    идеальный, ADJF, Qual, inan, masc, sing, accs
>
>    (AK, 19.04.2015, 21:46)
>    неснимаемая: нет родового понятия (AK, 19.04.2015, 21:47)
>    (AK, 19.04.2015, 21:48)

Первый пустой -- это я нечаянно поставил [при разметке](http://opencorpora.org/tasks.php?act=annot&pool_id=1907), второй -- пробовал со страницы пула, уже [осмысленно проверял на странице пула](http://opencorpora.org/pools.php?act=samples&pool_id=1907&ext&filter=comments). Оба коммента можно удалить, может и ещё в базе есть.

**Comment by grandsbor** [comment]
В базе было 64 пустых комментария, стёр
