### ISSUE TITLE
Автоматом полностью снята неоднозначность - но на деле опечатка

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#627]
[В предолжении 10399](http://opencorpora.org/sentence.php?id=10399) слово "тревога" полностью размечено автоматом. Однако это опечатка, корректно: ", которые запустили пожарную тревогу".

**Comment by grandsbor** [comment]
Наверное, лучшее, что можно сейчас сделать - добавлять комментарий к предложению. К этому добавил

**Comment by akmetainfo** [comment]
Оу, оказывается комментарии -- это вполне активный модуль (я как-то смотрел -- [последние комментарии](http://opencorpora.org/comments.php) были сделаны два года назад и я думал, что фичу комментирования давно выпилили за ненадобностью). И права у меня есть комментарии делать, вообще прекрасно ;)

В общем, тогда я сразу буду в предложениях писать, а не таски на гитхабе плодить.
