### ISSUE TITLE
Сломалось сохранение копий

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#635]
Документ №3472, урл с oid

**Comment by grandsbor** [comment]
Что именно сломалось?

**Comment by vbocharov** [comment]
Нажимаешь "скачать", оно думает, потом говорит "ошибка при сохранении файла"

**Comment by grandsbor** [comment]
Ага, это конкретно для викиновостей сломалось

**Comment by grandsbor** [comment]
А, нет, были неправильные права на каталог. Починил

**Comment by vbocharov** [comment]
Спасибо. Починилось.
