### ISSUE TITLE
ListenerInterface

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#639]
Нигде не используется. Надо или убрать, или унаследовать все листенеры от него (это как-то нетривиально, в лоб не получается)

**Comment by madfriend** [comment]
Вот да. С одной стороны, все эти интерфейсы хочется объединить (у всех есть метод `dispatch`), с другой - интерфейсы в PHP, вроде бы, не наследуются(

**Comment by grandsbor** [comment]
[Здесь](https://php.net/manual/ru/language.oop5.interfaces.php) написано, что наследуются

**Comment by madfriend** [comment]
Починилось, стоило перенести `require_once`
