### ISSUE TITLE
равиоли

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#644]
http://opencorpora.org/dict.php?act=edit&id=290588
Уберём Sgtm?

**Comment by grandsbor** [comment]
Туда же - [спагетти](http://opencorpora.org/dict.php?act=edit&id=331390)

**Comment by svbichineva** [comment]
Уберешь? 

Best,
Svetlana Alexeeva

**Comment by svbichineva** [comment]
убрала
