### ISSUE TITLE
Инициалы в словаре

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#645]
Переезд из #580.

cc @svbichineva, @kmike

**Comment by grandsbor** [comment]
Предлагаю добавить на пробу несколько неомонимичных инициалов (З, Р, Ф, Х, Ц, Ш, Ю). Предварительно, конечно, включить особую обработку пометы Init.

**Comment by kmike** [comment]
А что там насчет пометки "использовать разбор только для заглавных букв"?

**Comment by grandsbor** [comment]
"Особая обработка пометы Init" - это она и есть.
Le 19 juin 2015 9:18 PM, "Mikhail Korobov" <notifications@github.com> a
écrit :

**Comment by grandsbor** [comment]
А вот вопрос: это что же, для каждого инициала добавлять 4 леммы? (мужское имя, женское имя, мужское отчество, женское отчество) Как-то не хочется. Может, хотя бы две? (Name+Ms-f, Patr+Ms-f)

**Comment by svbichineva** [comment]
Давай как две. Только тогда всё равно какой-то род нужно выбрать (давай мр). Это как у других сущ общего рода. Слова общего рода можно потом обсудить 

Best,
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Вышеупомянутые 7 инициалов (14 лемм) добавил, в ближайшее время доведу их до разметки

**Comment by svbichineva** [comment]
Можно, кстати вместо мр, поставить GNdr, как сейчас у неизм фамилий

**Comment by grandsbor** [comment]
Вот да. Поставь, если не сложно.

**Comment by svbichineva** [comment]
вроде поставила. Может, ты и остальные инициалы тоже добавишь?

**Comment by grandsbor** [comment]
Спасибо.
Добавлю, но постепенно.

**Comment by grandsbor** [comment]
Добавил Б, Д, Е

**Comment by grandsbor** [comment]
Добавил Ж, Л, Н, П

**Comment by grandsbor** [comment]
Добавил Т, Ч, Э, Я

**Comment by grandsbor** [comment]
Добавил А, В, Г, И, Й

**Comment by grandsbor** [comment]
Добавил К, М, О, С, У. Всё.
