### ISSUE TITLE
Сокращения в парадигмах полных слов

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#646]
Кажется, мы от этого отказались? Остались ещё случаи:

- [далее](http://opencorpora.org/dict.php?act=edit&id=77935)
- [есть](http://opencorpora.org/dict.php?act=edit&id=37265)
- [как](http://opencorpora.org/dict.php?act=edit&id=128192)
- [наш](http://opencorpora.org/dict.php?act=edit&id=178492)
- [наука](http://opencorpora.org/dict.php?act=edit&id=177429)
- [подобный](http://opencorpora.org/dict.php?act=edit&id=248293)
- [технический](http://opencorpora.org/dict.php?act=edit&id=345946)
- [так](http://opencorpora.org/dict.php?act=edit&id=342453)
- [тот](http://opencorpora.org/dict.php?act=edit&id=348430)
- [число](http://opencorpora.org/dict.php?act=edit&id=376585)

**Comment by svbichineva** [comment]
я сделала отдельной леммой сокращения для наш, наука, подобный, технический, тот и число
у далее, так и как всего одна форма, поэтому я бы оставила в парадигме, но могу выделить
с есть точно нужно оставить внутри парадигмы, так как там сокращение (т.е.) только для одной формы, либо создавать связь лемма-форма

Дима, что думаешь?

**Comment by grandsbor** [comment]
Здесь у меня нет мнения. Делай, как тебе кажется правильным, лишь бы консистентно

**Comment by svbichineva** [comment]
Хорошо, тогда закрываю

**Comment by grandsbor** [comment]
Света, будет ли корректно включить форму "с" (одну) в парадигму слова "северный" для случаев типа "столько-то градусов с.ш."?
