### ISSUE TITLE
Связь непонятно с чем

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#648]
http://opencorpora.org/dict.php?act=edit&id=345946

**Comment by svbichineva** [comment]
я ее точно удаляла, не знаю, как она снова появилась

Расскажу, как происходит, что появляется связь непонятно с чем. Я добавляю
лемму, в данном случае "т", затем, забывая сохранить, сразу выбираю связь.
При нажатии на кнопку "добавить", создаваемое слово не сохраняется и
появляется связь непонятно с чем. То есть нужно сначала сохранить новое
слово, нажав кнопку "сохранить", а потом добавлять связь.

2015-06-25 16:05 GMT+03:00 Dmitry Granovsky <notifications@github.com>:

**Comment by grandsbor** [comment]
О, спасибо, значит, это можно победить интерфейсно
