### ISSUE TITLE
Крупные повторяющиеся куски текстов в базе

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#654]
В тексте http://opencorpora.org/books.php?book_id=3474&full повторяются целые абзацы текстов
19 = 21
18 = 22
17 = 20

@grandsbor Дима посмотри обязательно: это и срочно и важно. Примеры попали в разметку, хорошо если это всего лишь ошибка при внесении текста, а не нарушение консистентности базы.

**Comment by grandsbor** [comment]
Автоматизировать бы это...

**Comment by vtqveant** [comment]
Это тексты из Часкора, в которых один абзац продублирован в качестве аннотации (видно в сохраненной копии, напр. http://opencorpora.org/files/saved/547623b7ab64a7.58388062.html) Точно помню обсуждение, но не смог найти тикет.

**Comment by grandsbor** [comment]
Нет, тут ошибка заливки

**Comment by grandsbor** [comment]
Вроде стёр лишнее

**Comment by akmetainfo** [comment]
В заданиях на разметку останутся дубликаты или оттуда тоже удалены?

**Comment by grandsbor** [comment]
Тоже удалены

**Comment by akmetainfo** [comment]
> Вроде стёр лишнее
Закрываем тогда? Конкретный кейс устранён.

**Comment by grandsbor** [comment]
Ага
