### ISSUE TITLE
ея

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#655]
Есть идеи, что [это](http://opencorpora.org/dict.php?act=edit&id=95554) такое? Возможно, надо или грохнуть, или поставить Abbr

**Comment by victorbocharov** [comment]
естественный язык?
Судя по всему это не форма слова "она". ;)


6 июля 2015 г., 14:32 пользователь Dmitry Granovsky <
notifications@github.com> написал:

**Comment by svbichineva** [comment]
Нету, я тоже долго на это слово смотрела. Давай удалим 

Best,
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Может, и правда - естественный язык? Тогда я поставлю Abbr.

**Comment by victorbocharov** [comment]
ну, раз подходит ;)

2015-07-07 16:26 GMT+03:00 Dmitry Granovsky <notifications@github.com>:

**Comment by grandsbor** [comment]
Поставил Abbr
