### ISSUE TITLE
Упростить подсчёт рейтинга

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#656]
Сейчас рейтинг пользователей (первый столбец в статистике) считается так: каждый тип пулов имеет числовую характеристику, предположительно отражающую его сложность. Каждый ответ прибавляет к рейтингу юзера это число.

Но на самом деле только 39 из 113 типов пулов имеют эту характеристику, причём никто, кажется, не помнит, как мы её высчитывали. Короче, рейтинг плохо отражает реальность.

Предлагаю от этой характеристики избавиться, вместо этого считать рейтинг исходя из сложности типа (от 1 до 4), для чего понадобится определить всего 5 чисел - вес ответа в каждом уровне сложности (включая 0-й, т.е. неопределённый, серая звёздочка).

cc @victorbocharov @irinfox @madfriend @lasveritas

**Comment by irinfox** [comment]
Я была уверена, что рейтинг считается по сложности типа, поэтому мне сложно
что-то новое сказать :)

Если хочется продолжать считать довольно просто, то можно перейти на
подсчёт по типу сложности (0-4).
Ты хочешь цифры отличные от 1-5?)

Мне просто кажется, что типы с красной звездой без инструкции это,
например, очень сложно и весомо. И можно бы за это давать больше очков. Но
если человек поразмечал и везде налажал, то толку от него немного, и по
рейтингу поднимать не очень хочется.


7 июля 2015 г., 17:46 пользователь Dmitry Granovsky <
notifications@github.com> написал:

> Сейчас рейтинг пользователей (первый столбец в статистике) считается так:
> каждый тип пулов имеет числовую характеристику, предположительно отражающую
> его сложность. Каждый ответ прибавляет к рейтингу юзера это число.
>
> Но на самом деле только 39 из 113 типов пулов имеют эту характеристику,
> причём никто, кажется, не помнит, как мы её высчитывали. Короче, рейтинг
> плохо отражает реальность.
>
> Предлагаю от этой характеристики избавиться, вместо этого считать рейтинг
> исходя из сложности типа (от 1 до 4), для чего понадобится определить всего
> 5 чисел - вес ответа в каждом уровне сложности (включая 0-й, т.е.
> неопределённый, серая звёздочка).
>
> cc @victorbocharov <https://github.com/victorbocharov> @irinfox
> <https://github.com/irinfox> @madfriend <https://github.com/madfriend>
> @lasveritas <https://github.com/lasveritas>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/656>.
>



-- 
Ирина

**Comment by grandsbor** [comment]
Наличие/отсутствие инструкции, к сожалению, не логируется. Хочется пока продолжать считать по-простому, предполагая, что точность влияет на ачивки, а не на рейтинг.

**Comment by grandsbor** [comment]
Да, а ещё я предлагаю пересчитывать рейтинг пользователю не после каждого ответа, как сейчас, а раз в час/день всем сразу. И не логировать изменение этого рейтинга. Профит: будет меньше тормозить бэкенд разметки.

**Comment by irinfox** [comment]
Ну вот :(
А я люблю разметить и тут же посмотреть, получилось ли у меня обогнать
своего впередистоящего..

Я так и не поняла, тебя устраивают цифры 1-5 или ты хочешь коэффициенты для
типов сложности?

7 июля 2015 г., 20:08 пользователь Dmitry Granovsky <
notifications@github.com> написал:

> Да, а ещё я предлагаю пересчитывать рейтинг пользователю не после каждого
> ответа, как сейчас, а раз в час/день всем сразу. И не логировать изменение
> этого рейтинга. Профит: будет меньше тормозить бэкенд разметки.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/656#issuecomment-119270246>
> .
>



-- 
Ирина

**Comment by grandsbor** [comment]
Цифры 1-5 меня не устраивают. Не думаю, что красное задание впятеро сложнее зеленого.

**Comment by grandsbor** [comment]
Кстати, текущие веса варьируют от 0.6 до 2.7. В связи с этим хочу сделать так:
- 0.6 за зелёные
- 1 за серые
- 1.2 за жёлтые
- 2 за оранжевые
- 2.5 за красные

**Comment by irinfox** [comment]
А для отображения в статистике оно потом округляется по обычным правилам?

Серые сложнее зелёных?) Хотя я тоже думала о том, что они должны быть между
зелёными и жёлтыми.

8 июля 2015 г., 18:05 пользователь Dmitry Granovsky <
notifications@github.com> написал:

> Кстати, текущие веса варьируют от 0.6 до 2.7. В связи с этим хочу сделать
> так:
>
>    - 0.6 за зелёные
>    - 1 за серые
>    - 1.2 за жёлтые
>    - 2 за оранжевые
>    - 2.5 за красные
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenCorpora/opencorpora/issues/656#issuecomment-119616565>
> .
>



-- 
Ирина

**Comment by grandsbor** [comment]
Да, серые, как правило, сложнее зелёных. Я бы сказал, обычно в районе оранжевых скорее.

**Comment by victorbocharov** [comment]
ok
как будем объяснять всем резкое изменение рейтинга?

8 июля 2015 г., 18:19 пользователь Dmitry Granovsky <
notifications@github.com> написал:

**Comment by grandsbor** [comment]
Например, будем давать ссылку на этот тикет :-)

**Comment by akmetainfo** [comment]
В шкале, которую привёл Дима за базу взят "серый" -- он равен единице. За зелёный предполагается психологический штраф (уменьшение баллов).

А давайте возьмём за базис самый простой пример и приравнять его к единице? Домножив все значения получим следующие цифры:
1 за зелёные
1,66 за серые
2 за жёлтые
3,33 за оранжевые
4.1 за красные

Плюс -- нет штрафа, наглядно видно во сколько раз пример сложнее базового. Например, красный -- в 4 раза сложнее ценится нами, чем зелёный.

Цифры, кстати, получились очень близкие к целым, можно подумать о том, чтобы сделать ряд таким: 1.0 - 1.5 - 2.0 - 3.5 - 4.0 (оранжевые обычно ближе к красным)

**Comment by grandsbor** [comment]
Мне, честно сказать, всё равно, какая будет шкала. Я хочу:
- уменьшить тормоза
- сделать консистентно

Я привёл шкалу, которая, вероятно, приведёт к сравнительно небольшому изменению текущих рейтингов. Но в целом пусть будет большое, не думаю, что это критично.

**Comment by akmetainfo** [comment]
Мне в общем-то тоже без разницы, какая будет шкала. Я бы предпочёл, чтобы она менялась как можно реже, но если уж менялась -- то менялась к более точному рейтингу. 

По факту же сложность заданий как меряли на глазок -- так и продолжаем и не особо этими вопросами забиваем себе голову: как зависит сложность пула от скорости разметки, однородности пулов, количества сложных заданий или других попугаев и т.п.

Но уменьшение тормозов -- цель благая. Я тоже люблю смотреть кто размечает онлайн, но ради ускорения разметки готов обойтись перерасчётом рейтинга раз в час.

**Comment by svbichineva** [comment]
Я тоже хочу сказать, что серые задания сейчас остались сложные, я бы точно выше желтых поставила, а может,  и выше оранжевых

Best,
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Пока поставлю 3 (серый), 1, 2, 3.5, 4.
И оно поехало в продакшен.

**Comment by akmetainfo** [comment]
А нельзя сделать перерасчёт рейтинга хотя бы раз в час, а то ну совсем уныло размечать стало.

**Comment by grandsbor** [comment]
Он раз в 20 минут. +5 минут кэш шаблонизатора. F5 не помогает?

**Comment by akmetainfo** [comment]
Дима, кстати да -- если открываешь страницу, то показывается старая версия. 
Но если тут же нажать F5 - то появляются свежие данные. Локальных кэширующих проксей у меня в подсети и на компе нет.

**Comment by grandsbor** [comment]
Я думаю, это как-то связано с обновлённой версией Smarty, но доказательств нет
