### ISSUE TITLE
Правый контекст не хочет раскрываться

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#658]
Уже не первый раз замечаю какой-то непонятный баг: хочешь раскрыть правый контекст (когда размечаешь задания), кликаешь на него, кликаешь -- а он не раскрывается.

И такое впечатление, что это не сетевые задержки, когда одновременно с тобой кто размечает и ты на деле уже кликнул и ajax идёт неторопливо с бекенда. Впечатление именно будто, что кнопка не хочет нажиматься, потому что её заслоняет какой-то невидимый DIV не дающий кликнуть. 

Особые приметы: полтора слова (до размечаемого слова) курсор не хочет выделять слова, как будто на них тоже поверх что-то мешает выделять текст.

Спасает от этого только перезагрузка страницы, либо держать в соседней вкладке открытый модераторский интерфейс (там тоже кнопки контекста есть и они работают)

Даже не знаю, воспроизводим ли баг у кого-то? Я его сам случайно увидел, когда закончились лёгкие примеры, не требующие раскрытия контекста.

**Comment by madfriend** [comment]
браузер? можете сделать скриншот, если воспроизведется, открыв веб-инспектор?

**Comment by akmetainfo** [comment]
Я предлагаю закрыть данный баг: даже у меня больше не воспроизводится. 

Сначала я грешил на то, что кнопка мышки поломалась, но с мышью всё ок, только при разметке проявлялось, в других приложениях -- нет.

Из более-менее обоснованных гипотез -- только то, что сервер не успевал отработать множество ajax-запросов (много размечающих например).

Если всплывёт ещё раз -- посмотрю, что веб-инспектор покажет.

Браузер: Firefox, последний стабильный (в тот день обновился на 39тую версию).
