### ISSUE TITLE
Провести связь между наречием и компаративом

### ISSUE THREAD

**Issue by svbichineva** [OpenCorpora/opencorpora#662]
сейчас в словаре компаративы связаны только с прил., но должны таким же образом быть связаны с наречием. 
Добавить связь "ADVB-COMP" и найти кандидатов на связывание:
- от компаратива отделить окончание -ее и добавить -о, поискать полученное слово среди наречий в словаре, если оно есть добавить пару в список кандидатов.
- перечислить компаративы, образованное от которых наречие не нашлось в словаре

**Comment by grandsbor** [comment]
Есть 143 компаратива, не оканчивающихся на -ее, [список](https://yadi.sk/i/ulRbuKHnhyPr6)

**Comment by gisly** [comment]
Добавила скрипт, который ищет компаративы: https://github.com/gisly/opencorpora/commit/f70510bdfa5899d428cabc197f80bd1dc9a74b88
Локально работал 1 час 20 минут, список найденных компаративов прикладываю
[link_file.txt](https://github.com/OpenCorpora/opencorpora/files/253423/link_file.txt)

**Comment by svbichineva** [comment]
Чтобы можно было хоть что-то просмотреть, было бы хорошо выделить из списка link_file те компаративы, которые есть у нас в корпусе (вместе с найденными кандидатами)

**Comment by gisly** [comment]
В этом списке перечислены только компаративы, которые есть в корпусе (т. е. тут нет сгенерированных компаративов, отсутствующих в корпусе). Или я не так поняла вопрос?

**Comment by grandsbor** [comment]
Все, кроме 143 не на -ее, добавили

**Comment by grandsbor** [comment]
Света, с тебя список наречий для тех компаративов

**Comment by Shimorina** [comment]
[Список](https://www.dropbox.com/s/hmyyc9vebrirqag/%D0%BA%D0%BE%D0%BC%D0%BF%D0%B0%D1%80%D0%B0%D1%82%D0%B8%D0%B2%D1%8B-%D0%BD%D0%B0%D1%80%D0%B5%D1%87%D0%B8%D1%8F.txt?dl=0). Надо, чтобы кто-нибудь его тоже прочитал.

После наречий есть комментарий, если что-то ещё надо изменить/удалить в словаре.
Комментарий _удалить компаратив?_ может означать:

- что соответствующее прилагательное надо изменить на относительное в словаре;

- что соответствующее прилагательное является качественным, но не имеет формы сравнительной степени (_толстенький_).

См. также #660 и #661.
