### ISSUE TITLE
Дубликат "простыл"

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#668]
http://opencorpora.org/dict.php?act=edit&id=285312
http://opencorpora.org/dict.php?act=edit&id=285317

Одно связано с "простыть", другое с "простынуть". Наверно, такие есть ещё.

**Comment by svbichineva** [comment]
разобралась с простынуть (удалила дубликаты, добавила прич и дееприч). Если еще есть, пиши

**Comment by grandsbor** [comment]
Ок, найду ещё - переоткрою
