### ISSUE TITLE
исполняющий - существительное?

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#67]
Там сейчас 2 леммы для "исполняющий", NOUN и PRTF: http://opencorpora.org/dict.php?search_form=%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D0%BD%D1%8F%D1%8E%D1%89%D0%B8%D0%B9&act=lemmata

Разве бывает существительное "исполняющий"? Если по аналогии с "ведущий", то это ведь PRTF, Subx или ADJS, Subx?

**Comment by svbichineva** [comment]
Раз никто не ответил, считаю, что согласились с моей точкой зрения. Лемму сохраняю
