### ISSUE TITLE
При открытии словаря срабатывает ачивка "аист"

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#672]
Уже пятый раз захожу на /dict.php и который раз вижу аиста, это какой-то баг.
С утра не было такого.

**Comment by grandsbor** [comment]
А если нажать F5?

**Comment by akmetainfo** [comment]
Повторно на той же странице не срабатывает. Вообще, добрался до домашнего компа и тут ещё получил с десяток аистов -- но уже не только на странице "словарь", а просто на произвольных страницах верхнего меню. На /?page=downloads вот только что. Откуда они идут??

**Comment by grandsbor** [comment]
Я подозреваю, что это всё тот же кэш смарти, который непонятно как
отключить.

**Comment by akmetainfo** [comment]
А ````$smarty->caching = false;```` не подходит?

**Comment by madfriend** [comment]
полный отказ от кэширования - плохая идея. Страницы со статистикой должны кэшироваться.

**Comment by grandsbor** [comment]
Ну раньше кэширование было по умолчанию выключено (в самой библиотеке смарти), и мы его включали для отдельных страниц. Сейчас, возможно, внутри смарти что-то изменилось, и нам нужно что-то изменить в коде, только сначала нужно понять, что изменилось.

**Comment by grandsbor** [comment]
Я там выкатил Сашин коммит. Починилось?

**Comment by akmetainfo** [comment]
Пока не появляется. Специально пощёлкал по страницам -- не воспроизводится. Закрываю пока, если всплывёт снова -- вернём.
