### ISSUE TITLE
Баг при выдаче ачивки "собака"

### ISSUE THREAD

**Issue by irinfox** [OpenCorpora/opencorpora#674]
Почему-то этому пользователю - http://opencorpora.org/user.php?id=4595 показывается активная ачивка с 0 уровнем. Должен быть либо 1 уровень, либо заблюренный чб.

Сравни, например, с http://opencorpora.org/user.php?id=4833

**Comment by madfriend** [comment]
Дима, а можешь посмотреть, что в базе у этого пользователя в user_achievements?
cc @grandsbor

**Comment by grandsbor** [comment]
Я уже смотрел, выдана ачивка 0-го уровня

**Comment by madfriend** [comment]
как обнаружилось, собака нулевого уровня была у 4000 пользователей, выпилили ее (т.к. по смыслу это отсутствие ачивки)

**Comment by grandsbor** [comment]
А они первого числа не выдадутся заново?
