### ISSUE TITLE
Кнопка "согласиться со всеми однозначными" вполне себе обратима

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#676]
Из серии мелких деталей.

Раньше я обычно пользовался разбивкой постранично и на каждой странце кликал _линк_ "согласиться со всеми однозначными".

Сейчас на коротких пулах прохожу все 50 заданий и потом жму уже _кнопку_ "согласиться со всеми однозначными".

Обратил внимание: на ней текстовка поп-апа такая же, как у кнопки "начать модерацию" - "Вы уверены? Это действие необратимо".

А по факту оно обратимо: модератор может туда-сюда перещёлкивать ответы, может долго думать, никакого наказания за это не будет и действие вполне себе обратимое.

**Comment by grandsbor** [comment]
Ну ок, давайте поменяем текст :)
