### ISSUE TITLE
Не даёт размечать #118 пул

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#677]
Только для моего логина и только этот пул: http://opencorpora.org/tasks.php?act=annot&pool_id=2405

Остальные продолжаю размечать, а при переходе по этой ссылке выдаёт "Произошла ошибка" и всё

**Comment by akmetainfo** [comment]
До сих пор не могу войти в этот пул для разметки.

**Comment by grandsbor** [comment]
А если http://opencorpora.org:8080/tasks.php?act=annot&pool_id=2405?

**Comment by akmetainfo** [comment]
Тот же самый эффект.

**Comment by grandsbor** [comment]
А теперь? (там же на 8080)

**Comment by akmetainfo** [comment]
А теперь -- даёт.

**Comment by grandsbor** [comment]
Интересно.
Видимо, где-то попорчена разметка. (Бывает.)

**Comment by grandsbor** [comment]
Сейчас на 8080 появилась более детальная ошибка?

**Comment by akmetainfo** [comment]
Вот так сейчас:
Произошла ошибка.
Incorrect MorphParseSet initialization

**Comment by grandsbor** [comment]
О как. Совсем интересно.

**Comment by grandsbor** [comment]
Должно стать ок

**Comment by akmetainfo** [comment]
Да, проверил - работает и на продакшене. Спасибо.

**Comment by akmetainfo** [comment]
Ан, нет. Вот какой баг теперь не хочет пропадать:
![master](https://cloud.githubusercontent.com/assets/6085279/10648842/9877ace0-7849-11e5-972c-2d53e0916aa9.png)

**Comment by grandsbor** [comment]
Ну тут только если вычищать плохие ревизии... Ладно, я подумаю
