### ISSUE TITLE
Склеить предложения

### ISSUE THREAD

**Issue by named-entity** [OpenCorpora/opencorpora#680]
16963 Герцог из Гарлема (id=3497) 
абзац 39, предложения 94915 и 94916
абзац 40, предложения 94917 и 94918, и там же 94919 и 94920.

**Comment by vbocharov** [comment]
Это я уже склеил.
Осталась проблема с тем, что не получается склеить токены.

**Comment by grandsbor** [comment]
Здесь ещё что-то нужно от меня?

**Comment by vbocharov** [comment]
В документе http://opencorpora.org/books.php?book_id=3555 две копии одного и того же текста. Удалять по предложениям очень долго. Удали, пожалуйста, вторую (именно вторую) напрямую в базе.

**Comment by grandsbor** [comment]
А быстрее, чем по предложениям, никак и не удалить. Там затрагивается
что-то около десятка таблиц в базе.
Le 22 oct. 2015 1:33 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by akmetainfo** [comment]
Не только в тексте 3555 два больших фрагмента, посмотрите ещё сюда: #688 - там повторы в тексте 3520

**Comment by grandsbor** [comment]
В 3555 стёр вторую копию. Если что-то ещё нужно в этом тикете - переоткрывайте

**Comment by akmetainfo** [comment]
В 3526 есть повторяющийся абзац:
http://opencorpora.org/books.php?book_id=3526&full#sen96320
http://opencorpora.org/books.php?book_id=3526&full#sen96404

Откуда взялся дубликат. Часто бывает на многих новостниках, когда на заглавной сайта есть краткое описание статьи, причём в разных статьях по-разному подходят к этому. Иной раз выхватывают один абзац из середины текста, иногда компилируют из разных предложений, иногда новый текст пишут.

Здесь как раз случай, когда полностью абзац вставили в начало. Предлагаю убрать фрамент в начале статьи.

Прав переоткрыть issue нет, поэтому @grandsbor @vbocharov

**Comment by grandsbor** [comment]
Согласен. Стёр.
