### ISSUE TITLE
Нужны исправления в базе (токены, на которых сломался токенизатор)

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#686]
По номерам токенов:
#1699198 - нужно заменить "по^детски" на "по-детски"
#1678922 - "sciposter" на "LATEX"
#1569283 - "visa " на "visa"
#1632610 - удалить токен (его нет в тексте)
#1244691 - удалить токен (но, вначале, проверить, что в нём, т.к. у него нулевая ширина)
#1302394 - почему он ломает токенизатор?

**Comment by vbocharov** [comment]
А чего токенизатор ломается на многоточиях?
Сломалось на предложении 96693, токен «...».

**Comment by grandsbor** [comment]
Все ошибки такого вида можно править самостоятельно в интерфейсе ручного
редактирования предложения. Кажется, двойной клик на текст токена открывает
его редактирование.
Le 24 oct. 2015 9:22 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by vbocharov** [comment]
Дима, там какой-то косяк с отображением текста токена по двойному клику. В поле ввода влезает кусок HTML.

**Comment by vbocharov** [comment]
А как удалить токен?

**Comment by vbocharov** [comment]
Не понимаю, чем токенизатору не нравится текст на иврите в предложении 67197 (это не срочно).

**Comment by grandsbor** [comment]
> Дима, там какой-то косяк с отображением текста токена по двойному клику.
> В поле ввода влезает кусок HTML.

Согласен, косяк. Починил.

**Comment by grandsbor** [comment]
Текст на иврите может содержать юникодный спецсимвол-переключатель направления текста

**Comment by grandsbor** [comment]
Токен удалить из интерфейса сейчас никак нельзя.
#1632610 стёр
#1244691 - это какая-то странная штуковина, я её тоже стёр (если очень интересно, можно в исходнике найти)

**Comment by grandsbor** [comment]
> #1302394 - почему он ломает токенизатор?
Не знаю :(

**Comment by vbocharov** [comment]
Редактирование токена у меня изменилось так: показывает то, что нужно (без HTML), но по нажатию на зелёную галку всё остаётся как было (т.е. не редактируется).

**Comment by grandsbor** [comment]
Починил редактирование токенов

**Comment by grandsbor** [comment]
Мест слома сейчас нет
