### ISSUE TITLE
Крупные повторяющиеся куски текстов в базе 2

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#688]
Нет прав переоткрыть #654 -- а снова та же самая проблема.

В тексте http://opencorpora.org/books.php?book_id=3520& - повторяется один крупный участок текста (три абзаца).

Вот два маркера однотипных фрагментов:
http://opencorpora.org/books.php?book_id=3520&full#sen95985
http://opencorpora.org/books.php?book_id=3520&full#sen96065

Видимо, опять ошибка заливки?

**Comment by grandsbor** [comment]
cc @victorbocharov

**Comment by grandsbor** [comment]
Вроде стёрли?
