### ISSUE TITLE
Пулы опять не перемешиваются?

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#689]
И к старой теме, что статистика по нажатию на кнопки раскрытия контекстов слева/справа невалидна, когда рядом идущие подряд предложения можно не раскрывать контекст.

Новые пулы и новые примеры. Вроде же делали перемешивалку - поломалась снова?

![thesame](https://cloud.githubusercontent.com/assets/6085279/10710724/d37c20ec-7a6e-11e5-80cc-359d6378cb8c.png)
![thesame2](https://cloud.githubusercontent.com/assets/6085279/10710725/d3adb7ba-7a6e-11e5-8f18-26f5745ab1d3.png)

**Comment by grandsbor** [comment]
А что, правда делали перемешивалку? Я не помню.

**Comment by akmetainfo** [comment]
Странно. У меня как раз отложилось, что ты её собрался делать, более того -- уже сделал. Но я уже не найду концов того обсуждения ни на гитхабе, ни в рассылке.

**Comment by vbocharov** [comment]
Кажется, что перемешивалка всегда была. Когда я создавал пулы вручную, была опция "набрать случайных примеров" или "набрать первых по порядку примеров". Я всегда выбирал первое.

**Comment by grandsbor** [comment]
Автопубликатор пулов фигачит их подряд, не рандомно. Пусть делает рандомно?
