### ISSUE TITLE
Интерфейс модерации ИС

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#69]
@madfriend @svbichineva @named-entity тикет для обсуждения. как скоро будем делать модерацию?

**Comment by grandsbor** [comment]
И такой тикет есть

**Comment by madfriend** [comment]
Дима, мне нужны следующие штуки от бэкенда:

- (модератору) получить всю разметку абзаца (разбитую по юзерам)
- нужно поле с id модератора NE у книжек
- какой-то способ понять, ты ли модератор книжки
- ручки в апи: скопировать спан от одного юзера другому, скопировать упоминание (со всеми спанами)

**Comment by grandsbor** [comment]
cc @yourmary

**Comment by grandsbor** [comment]
Тут ещё что-то осталось?

**Comment by vbocharov** [comment]
1. Интерфейс работает.

2. После модерации 100+ текстов кажется, что лучше показывать дифф на N колонок под абзацем. Наверное, это лучше другим тикетом.

**Comment by grandsbor** [comment]
Ок, сделайте, пожалуйста, п. 2 другим тикетом
