### ISSUE TITLE
Учёт токенизатором диакритических знаков (учёт ударения)

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#691]
Пример см. в предложении http://opencorpora.org/sentence.php?id=94704

Здесь в слове чуднóе автором проставлено ударение (оно там нужно), токенизатор разбил на два unkn - "чудн" и "ое".

Это баг или ещё просто токенизатор не умеет с этим работать?

Дима писал в #686 что такое можно поправить вручную, да? У кого есть права хотя бы конкретный случай исправить?

**Comment by vbocharov** [comment]
Я так понимаю, что это косяк ручного деления. Исправил.

**Comment by grandsbor** [comment]
Можно закрыть?
