### ISSUE TITLE
Сделать возможность удалять абзац/предложение

### ISSUE THREAD

**Issue by named-entity** [OpenCorpora/opencorpora#692]
Для всех, кто может добавлять тексты.

**Comment by grandsbor** [comment]
Для всех я бы не хотел, это тяжёлая и деструктивная (и необратимая)
операция. Можно, например, для модераторов морфологии.

**Comment by vbocharov** [comment]
Будет ок, если будет тикет со списком того, что нужно удалить.

**Comment by grandsbor** [comment]
Да, я готов оперативно удалять по списку.
