### ISSUE TITLE
Удалить предложения

### ISSUE THREAD

**Issue by named-entity** [OpenCorpora/opencorpora#693]
99609 - 99669

**Comment by vbocharov** [comment]
Катя, указывай, пожалуйста, ещё и номер документа. Тогда будет существенно проще это сделать из интерфейса.

**Comment by grandsbor** [comment]
Да, было бы удобнее.
Эти стёр.

**Comment by named-entity** [comment]
Весь текст (он пустой) 3534

**Comment by named-entity** [comment]
Отбой, текст удалять не надо. Его содержимое волшебным образом оказалось в тексте 3533. Если я могу сама это поправить, скажите как.

**Comment by grandsbor** [comment]
Надо перенести все абзацы из текста 3533 в текст 3534? Это в базе проще всего.

**Comment by named-entity** [comment]
Да. А в тексте 3534 соответственно удалить все разделы (пустые)

**Comment by grandsbor** [comment]
А что сделать с текстом 3533 и чем он плох? (Т.е., может, грохнуть 3534?)

**Comment by grandsbor** [comment]
И кстати, у них обоих неправильное название

**Comment by named-entity** [comment]
У него неправильное название и оригинальный источник (должен быть как у 3534)

**Comment by grandsbor** [comment]
Перенёс. 3533 удалить?

**Comment by named-entity** [comment]
Не надо, добавим туда нужный текст

**Comment by named-entity** [comment]
Текст 3510 (пустой): оказался разделом в 3509, мешает добавить текст прямо в 3509

**Comment by grandsbor** [comment]
done

**Comment by named-entity** [comment]
предложение 101327 текст 3663

**Comment by grandsbor** [comment]
У тебя же есть права это сделать самой.

**Comment by named-entity** [comment]
Нет. Рядом с предложением есть только чекбокс, которым я так и не научилась пользоваться

**Comment by grandsbor** [comment]
Точно. Спутал.

А там нет предложения 101327. Более того, такого предложения вообще нет, кто-то его уже стёр.

А чекбокс - это вообще про проверку токенизации. (Кстати, кажется, мы ей не пользуемся, может, выпилить? cc @victorbocharov)
