### ISSUE TITLE
Выдаётся "произошла ошибка" при открытии любого pools.php когда act = samples

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#695]
Хотел сегодня взять ещё пул на модерирование -- но какой бы я пул не попытался открыть из числа снятых с публикации -- выдаёт краткое сообщение "произошла ошибка" и ничего не выводит на экран.

При этом права модератора разметки у меня остались -- я вижу служебные ссылки на заглавной, могу просматривать списки "пулы в работе", "снятые с публикации" и т.п.

Пример ссылки -- http://opencorpora.org/pools.php?act=samples&pool_id=1966 остальные аналогичные, меняется только id пула.

Открыл рандомом штук пять ссылок в снятых с публикации и обе "в работе" -- эффект одинаковый.

При этом "пользовательский" режим с act=my данные показывает.

@grandsbor

**Comment by grandsbor** [comment]
Спасибо, буду разбираться

**Comment by akmetainfo** [comment]
забыл добавить: на порту 8080 (тестовый сервер) никаких дополнительных диагностических сообщений нет ;(

**Comment by akmetainfo** [comment]
Проверил -- теперь работает. Спасибо.
