### ISSUE TITLE
Словарь: лемме Шон добавить Name

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#697]
В словаре корпоры есть лемма [шон](http://opencorpora.org/dict.php?act=edit&id=380754) c пометами Noun, inan, masc.

Часто при модерировании попадается слово Шон в значении Name, anim, masc (Шон Тан, Шон Коннери и т.п.) -- а нужного разбора-то нет!

Сегодня решил посмотреть, что же это за шон такой (ну не знаю я навскидку других значений слова) и... ни в одном словаре русского языка не нашёл [(раз](https://slovari.yandex.ru/%D1%88%D0%BE%D0%BD/%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5/), [два](http://www.gramota.ru/slovari/dic/?word=%D1%88%D0%BE%D0%BD&all=x&lop=x&bts=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x), [три](http://slovaronline.com/search?word=%D1%88%D0%BE%D0%BD&x=0&y=0), [четыре](http://orf.textologia.ru/search/?q=530&sch=%F8%EE%ED&x=24&y=17)...)

Даже если предположить, что это слово -- аббревиатура от "шаровой орган управления" или "шкаф отбора напряжения", то где помета Abbr?

Я вообще для чего тикет завёл? Рано или поздно бы добавили в словарь шон как anim, Name -- но я предлагаю поразмыслить над вариантом "в этой лемме заменить inan -> anim и добавить Name".

@svbichineva

**Comment by svbichineva** [comment]
сделала одуш

**Comment by akmetainfo** [comment]
Дима, я сейчас обратил внимание: несмотря на обновление словаря разборы в модерирование не подтянулись. Правильно ли я понимаю, что нужно ждать, когда будет сделана очередная реаннотация корпуса?

Пример тут: http://opencorpora.org/pools.php?act=samples&pool_id=2586&ext&filter=not_ok&sortby= (см. 556893 "Шон Тан неоднократно получал...")

@grandsbor

**Comment by grandsbor** [comment]
Да, это автоматически не делается.
Конкретно Шона обновил руками
