### ISSUE TITLE
Можно модерировать, пока сайт находится в режиме "только для чтения".

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#699]
С четырёх до пяти утра кажется час различных регламентных работ на сайте, когда скрипты переводят его в рид-онли и что-то там считают.

Сегодня обратил внимание, что пока сайт находится в рид-онли -- некоторые функции всё же не закрыты. Я проверял задания на снятие неоднозначности и ближе к часу профилактики беспечно подумал "а, ладно -- посижу впритык, увижу, когда нотификация всплывёт". И заметил красную полоску предупреждения уже ближе к пяти утра. (Она не особо в глаза бросается, когда мозг сконцентрирован чётко на модерации и всё остальное игнорирует.)

Уверен, что функция модерации ответов не проверяет, что система находится в режиме только для чтения (проверил разово на одном примере). Возможно, следует более тщательно проверить интерфейс модератора на соблюдение режима "только чтение".

**Comment by grandsbor** [comment]
По-моему, это не страшно. Главное, чтобы не редактировались таблицы, по
которым генерируются дампы, а при модерации их нет
