### ISSUE TITLE
При закрытии разметки абзаца часть управления упоминанием остается

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#700]
Браузер: последний хром.

Нет возможности удалить упоминание, т.к. не отображаются крестики.

Проблема в <td class="ner-mention-actions"><i class="icon icon-remove ner-remove remove-mention" data-mention-id="1286"></i></td>
В main.css на 1071 строчке есть:
.ner-table-wrap.ner-disabled table tr td:nth-child(1) { 
display: none; 
}
Вот если его отрубить, кресты появляются.

alt: "Мм. КАжется все наоборот. Если после "закончить разметку абзаца" я должен терять любое управление абзацем, то баг в том, что часть управления остается. И вот в этом режиме нет крестов, но добавлять и изменять упоминания можно. А вот удалять их - уже нет."

**Comment by madfriend** [comment]
В коммите https://github.com/OpenCorpora/opencorpora/commit/3bf2d412ec4fd5fdfd179f75039c4f7e2b0bb91d починил, должно заработать. Пока не выкатывал

**Comment by grandsbor** [comment]
Выкатил

**Comment by madfriend** [comment]
@vbocharov починилось? если да, закрываем
