### ISSUE TITLE
[словарь] Лемма «дрянь» (2шт)

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#701]
В словаре присутствуют две леммы "дрянь", практически идентичные: несмотря на то, что одна anim, а другая inan -- разница только в plur+accs.

http://opencorpora.org/dict.php?act=edit&id=92519
http://opencorpora.org/dict.php?act=edit&id=92520

Разумно будет их попробовать слить?

@svbichineva

**Comment by svbichineva** [comment]
одушевленные от неодушевленных сущ. как раз отличаются формами винительного падежа:
см. пример взяглянул на табуретки / солисток (в неодуш. варианте форма вин. совпадает с им., в одуш. варианте форма вин. совпадает с формой род.). У слова _дрянь_ два значения: (1) мусор, хлам - неодуш и (2) скверный человек http://gramota.ru/slovari/dic/?lop=x&bts=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x&word=дрянь
Поэтому у нас есть две леммы с разными формами вин. падежа  

замечание: для сущ жр одушевленность проверяется по формам мн числа, для сущ мр также можно проверять и ед. числу
