### ISSUE TITLE
Щелчок на абзаце не переводит его в режим редактирования NE

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#702]
Браузеры: Chromium и Firefox. Ubuntu.

**Comment by madfriend** [comment]
Какой режим редактирования выбран - кликом или выделением?

**Comment by madfriend** [comment]
абзац вообще доступен для разметки? недоступные абзацы - серые.

**Comment by vbocharov** [comment]
Абзац белый. Курсор на нём меняет форму на руку.

**Comment by madfriend** [comment]
что-нибудь в консоли пишется? запросы какие-нибудь посылаются на сервер? что при обновлении страницы?

**Comment by vbocharov** [comment]
ner.js?5:284 Uncaught SyntaxError: Unexpected identifier
rangy-core.js:11 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

**Comment by madfriend** [comment]
Глупый баг был, я его починил, посмотри на виртуалке, пожалуйста (может потребоваться сбросить кэш)

**Comment by vbocharov** [comment]
На :8080 всё работает. На продакшене пока нет. Нажимал Ctrl-F5.

**Comment by madfriend** [comment]
забыл доступы к продакшн-машине. Можешь зайти на нее в /corpus и сделать `git pull origin master`?

**Comment by vbocharov** [comment]
с sudo?

**Comment by madfriend** [comment]
нет, должно без sudo получиться

**Comment by vbocharov** [comment]
webadmin@ocweb:/corpus$ git pull origin master
error: cannot open .git/FETCH_HEAD: Permission denied

**Comment by madfriend** [comment]
Дима выкатил. проверь, пожалуйста

**Comment by vbocharov** [comment]
работает. Спасибо!
