### ISSUE TITLE
[словарь] Лемма "теломер"

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#703]
В словаре корпоры есть лемма [теломер](http://opencorpora.org/dict.php?act=edit&id=344412), один из текстов корпуса - [статья из википедии](https://ru.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BB%D0%BE%D0%BC%D0%B5%D1%80%D1%8B) про теломеры активно использует это слово в разных склонениях.

Видно, что википедия использует слово как femn, а в словаре лемму просклоняли как masc.

Заметил когда попалось на модерировании в этом пуле: http://opencorpora.org/pools.php?act=samples&pool_id=929&ext&sortby=

@svbichineva

**Comment by grandsbor** [comment]
Я думаю, это как со словом компонент/компонента

**Comment by Web-Manya** [comment]
Я, как человек, имеющий непосредственное отношение к биологии и медицине, могу сказать, что "теломера" женского рода

**Comment by svbichineva** [comment]
поменяла род
