### ISSUE TITLE
[словарь] Лемме "Талибан" добавить Orgn

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#704]
[Лемме "Талибан"](http://opencorpora.org/dict.php?act=edit&id=342657) можно добавить помету Ogrn -- это именно только движение, организация и нет такого существительного, которое бы обозначало бы место, предмет -- т.е. лемма употребляется только как Ogrn.

При модерации ([тут](http://opencorpora.org/pools.php?act=samples&pool_id=911&ext&sortby=&skip=15) проскочило) не стал добавлять "частично правильно" или "нет правильного разбора" -- потому что можно просто лемму подрихтовать и будет всё правильно.

@svbichineva

**Comment by akmetainfo** [comment]
Аналогично - [лемма Хамас](http://opencorpora.org/dict.php?act=edit&id=369216), встречалось [тут](http://opencorpora.org/pools.php?act=samples&pool_id=1081&ext&sortby=&skip=0)

**Comment by svbichineva** [comment]
добавила обеим леммам
