### ISSUE TITLE
add_mention, скорее всего, сломан

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#710]
В lib_ne.php/add_mention делается `INSERT INTO ne_mentions SET object_type_id = ?` без указания `object_id`. Локально запрос валится. В миграции не указано дефолтное значение этой колонки. Надо проверить, что добавление упоминаний работает в проде.

**Comment by yourmary** [comment]
Действительно. Надо объект тоже принимать параметром функции? Будет что передавать?
