### ISSUE TITLE
lib_ne.php / copy_ne_entity копирует без типов

### ISSUE THREAD

**Issue by madfriend** [OpenCorpora/opencorpora#712]

**Comment by vbocharov** [comment]
+ @grandsbor

**Comment by madfriend** [comment]
+ надо проверить, что у copy_ne_mention нет такого дефекта

**Comment by yourmary** [comment]
не, в add_mention копируется ссылка на объект и его тип. А где тип у entity? Я, наверно, запуталась. Спан копируется тупо, только с новой ссылкой на аннотацию, без меншенов (где указаны типы).

**Comment by madfriend** [comment]
Дима, а где тип у entity лежит и как его достать?

**Comment by grandsbor** [comment]
entity - это спан, типы лежат в таблице ``ne_entity_tags``
