### ISSUE TITLE
Починить warning: faq

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#714]
`PHP Warning:  array_push() expects parameter 1 to be array, null given in /var/www/html/lib/lib_achievements.php on line 171, referer: http://opencorpora.org/?page=faq`

**Comment by madfriend** [comment]
это из-за собаки нулевого уровня

**Comment by grandsbor** [comment]
А если в `push()` проверять, что `$this->level > 0`, они же перестанут выдаваться?

**Comment by grandsbor** [comment]
Удалил всех собак 0-го уровня, посмотрим.
Кстати, по-видимому, на тестинге (в ветке nsk-api) было деление юзеров на четные-нечетные. И вообще, надо как-то иметь в виду, что с тестинга тоже выдаются ачивки.

**Comment by grandsbor** [comment]
Починилось тем коммитом
