### ISSUE TITLE
Дублирование спанов при компировании

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#719]
Пример "у памятника Юрию Долгорукому".

До копирования:

Спаны:
- loc_descr( памятника )
- name( Юрию )
- surname( Долгорукому )

Упоминания:
- Person( Юрию Долгорукому )
- Location( памятника Юрию Долгорукому )

После копирования:

Спаны:
- loc_descr( памятника )
- name( Юрию )
- surname( Долгорукому )
- name( Юрию )
- surname( Долгорукому )

Упоминания:
- Person( Юрию Долгорукому )
- Location( памятника Юрию Долгорукому )

**Comment by victorbocharov** [comment]
сс @madfriend @yourmary

**Comment by grandsbor** [comment]
Ты копировал всё за один клик?
Le 10 janv. 2016 10:42 AM, "Victor Bocharov" <notifications@github.com> a
écrit :

**Comment by victorbocharov** [comment]
Да

**Comment by grandsbor** [comment]
Скажи id текста, плз

**Comment by grandsbor** [comment]
Ещё: ты проверяешь в тестинге? Если в продакшене, там был недовыкачен некий Сашин фикс

**Comment by victorbocharov** [comment]
в тестинге

**Comment by grandsbor** [comment]
Аа, всё, я понял. Да, это баг

**Comment by madfriend** [comment]
правильно понимаю, что до копирования у тебя было:

*Спаны:*

loc_descr( памятника )
name( Юрию )
surname( Долгорукому )

*Упоминания:*

Person( Юрию Долгорукому )
Location( памятника Юрию Долгорукому )

А в той разметке, откуда копировал, было:

*Спаны:*

name( Юрию )
surname( Долгорукому )

?

**Comment by victorbocharov** [comment]
До копирования - это та разметка, откуда я копировал. Исходная версия не меняется. Но в копии появляются дубли.

**Comment by madfriend** [comment]
А туда, куда копировал -- там было пусто?

**Comment by grandsbor** [comment]
Саш, это баг на бэкенде
Le 10 janv. 2016 4:15 PM, "Alex Chuchunkov" <notifications@github.com> a
écrit :

**Comment by victorbocharov** [comment]
Туда, куда копировал, было пусто.

**Comment by grandsbor** [comment]
Проверь в тестинге, должно починиться

**Comment by victorbocharov** [comment]
В данный момент копирование "Спаны + упоминания" не работает никак. Т.е. нажатие на кнопку ни к чему не приводит.

**Comment by victorbocharov** [comment]
в консоли: Empty string passed to getElementById()

**Comment by grandsbor** [comment]
Упс. А теперь.

Кстати, Саш, теперь при копировании (copyEntity) может вернуться id уже существующего спана (если при копировании возник бы его дубликат).

**Comment by victorbocharov** [comment]
Всё равно не работает.
Книга 127, первый абзац, копирую разметку от AK.

**Comment by grandsbor** [comment]
Ну теперь, кажется, починил :)

**Comment by victorbocharov** [comment]
да. вроде заработало.
