### ISSUE TITLE
Тексты без разметки или с частичной разметкой в списке для модерации

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#721]
http://opencorpora.org/books.php?book_id=506&act=ner
Ещё: 3269

**Comment by victorbocharov** [comment]
cc @grandsbor

**Comment by madfriend** [comment]
в этом списке -- книги с готовностью 100%. Дима, надо проверить lib_ne/get_books_with_NE

**Comment by grandsbor** [comment]
Кажется, починил. Смотреть в тестинге

**Comment by grandsbor** [comment]
Тут всё ок?

**Comment by vbocharov** [comment]
Думаю, что да.
Перечисленных текстов нет в списке на модерацию, т.к. они не размечены.
Текстов без разметки в списке на модерацию тоже больше не видел.
