### ISSUE TITLE
Снимать выделение упоминаний после создания объекта третьего слоя

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#724]
Сейчас упоминания объектов остаются выделенными. Чтобы создать следующий объект третьего слоя с каждого нужно это выделение снимать или перезагружать страницу. Нужно, чтобы выделение снималось автоматически после того, как объект третьего слоя был создан.

**Comment by madfriend** [comment]
Витя, что в консоли JS пишется, когда создаешь новый объект? там наверняка какой-то exception. В коде снятие выделения есть, в я.браузере должно работать
