### ISSUE TITLE
Отмечать упоминания объектов, включённых в объекты третьего слоя сразу после включения

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#728]
1. сейчас они отмечаются курсивом. Кажется, что это не очень хорошо видно. Лучше сменить цвет на серый.

2. нужно, чтобы цвет менялся сразу после того, как упоминание вошло в состав объекта третьего слоя. Сейчас за время разметки одного документа нужно обновлять страницу раз пять, т.к. не удержать в памяти, кого склил, а кого - нет.

**Comment by madfriend** [comment]
2 связано с #724 -- в коде эта логика есть
