### ISSUE TITLE
правый, левый, ультраправый

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#734]
У всех этих слов есть омонимия NOUN/ADJF. Может быть, с ними надо поступить как со словом "больной" и омонимию убрать?

**Comment by svbichineva** [comment]
А ты думаешь, левая/правый употребляется как больная? 

Best,
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Я не знаю. Я хочу показать тебе, чтобы ты решила :)

**Comment by svbichineva** [comment]
у нас в корпусе женского употребления в виде сущ нет, в НКРЯ тоже нет лемм правая/левая. Считаю, что ничего делать не надо
