### ISSUE TITLE
Сдвинутое на один токен отображение спана

### ISSUE THREAD

**Issue by vbocharov** [OpenCorpora/opencorpora#739]
Спан в базе выглядит вот так:

book_3688.objects:52579 Org 87382 # )
book_3688.spans:87382 org_name 2558 16 1857827 1  # 1847240 )

В интерфейсе - это news.rambler.ru

![image](https://cloud.githubusercontent.com/assets/9334765/13564859/9f4b519a-e45d-11e5-8db7-75cb90c0975f.png)

Непонятно, как удалось это создать и почему продолжает выглядеть так странно.

https://github.com/dialogue-evaluation/factRuEval-2016/issues/82

**Comment by madfriend** [comment]
> book_3688.objects:52579 Org 87382 # )
book_3688.spans:87382 org_name 2558 16 1857827 1 # 1847240 )

как это читать?

**Comment by victorbocharov** [comment]
Я - человек-косяк.
Пофиксил баг в экспорте у себя.
