### ISSUE TITLE
Разобраться со словами типа подсудимая/подсудимый

### ISSUE THREAD

**Issue by svbichineva** [OpenCorpora/opencorpora#740]
Ещё слова:

десяток/десятка, подсудимый/подсудимая, подследственный/подследственная, вожатый/вожатая, малолеток/малолетка 

Сейчас пара подсудимый/подсудимая сделана по модели фамилий. То же самое нужно сделать для других слов. Или ещё раз об этом подумать. 

Возможно нужно также сделать слова типа Саша, Валя, Женя 

Плюс есть такие слова

варианты (-ам, -ами, -ах), глисты (-ам, -ами, -ах), залы (-ам, -ами, -ах), компоненты (-ам, -ами, -ах), методы (-ам, -ами, -ах), ставни (-ям, -ями, -ях), cтропы (-ам, -ами, -ах)

**Comment by grandsbor** [comment]
Это тебе же тикет?

**Comment by Nofenigma** [comment]
Извините, что встреваю: там всё-таки, кажется, десяток с десяткой - это разные слова, если десятка - это про деньги. Не до конца пока поняла, насколько вы сурово обращаетесь с омонимией, но всё-таки не очень здорово было бы видеть для десятки (о деньгах) вариант "десяток".
(Кстати, а почему у вас для слов общего рода типа "пьяница" помета женского рода фигурирует?)

**Comment by kmike** [comment]
См. также https://github.com/OpenCorpora/opencorpora/issues/51

**Comment by grandsbor** [comment]
Слова с пометами Name и Ms-f одновременно, кроме инициалов:
- валентуля (!)
- валечка
- валя
- данте (?)
- женечка
- женька
- женя
- капа
- паша
- слава
- саша
- хижа
- шалва
- шура
- шурка
- шурочка

**Comment by Shimorina** [comment]
также сделать пару _понятой/понятая_

(сейчас в словаре есть только мужской род)

**Comment by grandsbor** [comment]
@svbichineva @Shimorina 
что здесь осталось?

**Comment by Shimorina** [comment]
разобрались
