### ISSUE TITLE
Сделать некоторые пулы зелёными для модерации

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#742]
Из тех, что я модерировала, явные кандидаты на зелёные пулы это:
-- ADJF&femn&gent@ADJF&femn&datv@ADJF&femn&ablt@ADJF&femn&loct
-- NOUN&sing&gent@NOUN&sing&datv@NOUN&sing&loct

Там совсем нет случаев, когда модератор не согласен со всеми разметчиками.

В целом, надо бы провести ревизию всех остальных пулов тоже.

**Comment by grandsbor** [comment]
cc @victorbocharov @svbichineva

**Comment by grandsbor** [comment]
"Зелёные для модерации" - это где можно соглашаться с однозначными не глядя?
Если Витя и Света за, я сделаю.

**Comment by svbichineva** [comment]
Я против (относительно зеленого списка для модерации) любых пулов с прилагательными, так как все равно надо просматривать все примеры на наличие субстантивации
Я за второй пул я за

**Comment by victorbocharov** [comment]
согласен со Светой

31 июля 2016 г., 0:09 пользователь svbichineva <notifications@github.com>
написал:

**Comment by grandsbor** [comment]
Вроде сделал, проверьте

**Comment by svbichineva** [comment]
Да, теперь для пула NOUN&sing&gent@NOUN&sing&datv@NOUN&sing&loct список для модерации зелёный

**Comment by grandsbor** [comment]
Кстати, о субстантивации. Мы не хотим это выделить в отдельный тип заданий вместо того, чтобы напрягать модераторов?

**Comment by victorbocharov** [comment]
Я за отдельный тип заданий.

1 августа 2016 г., 13:10 пользователь Dmitry Granovsky <
notifications@github.com> написал:

**Comment by svbichineva** [comment]
А я против:
Во-первых, прилагательных очень много
Во-вторых, одновременно с субстантивацией есть эллипсис, а это значит, что это не задание зеленого/желтого уровня (а оранжевые и так не размечают)
В-третьих, мы уже очень много примеров сделали по-старому

Создать кнопку «субстантивация» очень сложно?

Хотя одно и то же прилагательное попадается в нескольких пулах и мы его помечаем несколько раз. Нужно подумать

**Comment by Shimorina** [comment]
Сейчас пул с **прилагательными** мужской-средний род зелёный, и это здорово помогает. Просмотреть весь пул на субстантивацию -- это меньше работы, чем просмотреть на субстантивацию и ещё падеж.
Поэтому я бы сделала ADJF&femn&gent@ADJF&femn&datv@ADJF&femn&ablt@ADJF&femn&loct зелёным.

**Comment by grandsbor** [comment]
Света?

**Comment by svbichineva** [comment]
да, давай сделаем зеленым

**Comment by grandsbor** [comment]
Сделал

**Comment by Shimorina** [comment]
Немного не то сделано :) Задача была про зелёные для модераторов, а не для разметчиков. То, что для разметчиков он был жёлтым, это правильно (я уже исправила обратно с зелёного на жёлтый).

**Comment by grandsbor** [comment]
Тьфу. Извините, сделаю

**Comment by grandsbor** [comment]
Внезапно сделал.
А такой же пул про причастия не сделать?

**Comment by grandsbor** [comment]
Кстати, сейчас у пула "прилагательными мужской-средний род" стоит модерация только по слову "общем" (ну помимо обычных условий), это ок? И по умолчанию у новых зеленых пулов таких слов нет.
Может, мы хотели когда-то по помете Subx такие слова выделять, но забыли?

**Comment by Shimorina** [comment]
Спасибо. Нет, причастия лучше не надо, они немного сложнее, да и к тому же там совсем мало заданий с ними, можно и так справиться.
