### ISSUE TITLE
Полный контекст предложения при модерации пулов

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#743]
Сейчас при модерации есть две ссылки (к расширенному виду, к обычному виду). Надо добавить ссылку "к полному контексту", где все предложения на странице будут раскрыты полностью.
Сейчас чтобы раскрыть предложение нужно нажимать на кнопку расширения контекста справа и слева. Это очень трудозатратно, так как есть пулы, где нужно всегда читать всё предложение целиком, чтобы снять неоднозначность.

**Comment by akmetainfo** [comment]
Мне подобные пулы почти не встречаются (сходу могу вспомнить только простановку subst), но подобный функционал мне кажется полезным. 
Какая-нибудь javascript-кнопка, по нажатию которой раскрываются все контексты на странице, либо даже GET-параметр в ссылке, чтобы два раза не вставать.

**Comment by Shimorina** [comment]
Как дела?

**Comment by grandsbor** [comment]
Так а может просто по умолчанию все раскрывать?

**Comment by Shimorina** [comment]
Хм, не знаю, надо посмотреть, как это будет выглядеть. Возможно, краткий контекст иногда более удобен

**Comment by grandsbor** [comment]
Для эксперимента сделал, чтобы в расширенном виде все контексты были раскрыты. Расскажите, как впечатления.

**Comment by Shimorina** [comment]
мне всё нра. Можно так и оставить. Что думают остальные? @svbichineva @antfed

**Comment by svbichineva** [comment]
Мне тоже нравится. 


Best regards, 
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Ну и отлично
