### ISSUE TITLE
странная лемма "вёдро"

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#745]
См. http://opencorpora.org/dict.php?act=edit&id=37428. Похоже, в одну лексему объединили ведро (ну обычное ведро) и вёдро (ясную погоду, https://ru.wiktionary.org/wiki/%D0%B2%D1%91%D0%B4%D1%80%D0%BE). К тому же первая форма - почему-то с ё, а не с е. Заметили тут: https://github.com/kmike/pymorphy2/issues/64#issuecomment-143578051.

**Comment by svbichineva** [comment]
поменяла начальную форму. Не знаю, удалять ли формы с ё?

2016-05-10 19:46 GMT+03:00 Dmitry Granovsky <notifications@github.com>:

**Comment by kmike** [comment]
Мне кажется, или удалять, или делить на 2 лексемы. Так оставлять плохо. Я бы удалил :)

**Comment by svbichineva** [comment]
мы их объединили, поскольку в мн. ч., невозможно было бы снять омонимию

Дима, что ты думаешь про удаление форм с ё?

2016-05-16 14:00 GMT+03:00 Mikhail Korobov <notifications@github.com>:

**Comment by grandsbor** [comment]
Думаю, их не надо удалять, мы же уважаем букву Ё :)
А ещё такие случаи есть?

**Comment by grandsbor** [comment]
А если разделить на две лексемы, но у той, которая вЁдро, оставить только ед.ч.?

**Comment by svbichineva** [comment]
Хорошая идея 

Best,
Svetlana Alexeeva

**Comment by svbichineva** [comment]
сделала, как предложил Дима
