### ISSUE TITLE
даже и все-таки

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#746]
Привет. Заметил, что удалили разборы для "даже" и "все-таки" как для союзов. 

"все-таки" и в [gramota.ru (Большой толковый словарь русского языка)](http://gramota.ru/slovari/dic/?word=%D0%B2%D1%81%D0%B5-%D1%82%D0%B0%D0%BA%D0%B8&all=x), и в [викисловаре](https://ru.wiktionary.org/wiki/%D0%B2%D1%81%D1%91-%D1%82%D0%B0%D0%BA%D0%B8), и в НКРЯ трактуется и как союз, и как частица. 

У "даже" в [викисловаре](https://ru.wiktionary.org/wiki/%D0%B4%D0%B0%D0%B6%D0%B5) и в НКРЯ есть разбор "союз"; на [gramota.ru (Большой толковый словарь русского языка)](http://gramota.ru/slovari/dic/?lop=x&bts=x&zar=x&ag=x&ab=x&sin=x&lv=x&az=x&pe=x&word=%D0%B4%D0%B0%D0%B6%D0%B5) есть разбор "в значении союза". 

А какая причина, почему в OpenCorpora решили делать не так?

**Comment by kmike** [comment]
Пинг :) Разборы были удалены Wed 28.10.2015; я только пару недель назад заметил, когда хотел релиз pymorphy2 сделать (не сделал из-за этого вопроса) и сравнивал, что поменялось в разборах.

**Comment by svbichineva** [comment]
Простой ответ следующий: сложно придумать правила, по которым для этих слов можно отделить Союзное употребление от частичного. 
В прототипический значении частица изменяет модальность какого-то конкретного слова, выделяя его в предложении. Союз используется для соединения слов и простых предложений.
Возьмём прототипическую частицу "именно":
Именно он спел песню (а не Таня)  != он именно спел песню (а не станцевал танец) != он спел именно песню (а не роман).
А теперь вставляем в сложное предложение: я не думал, а именно он спел песню. 
Кажется, эта та же частица и выделяет она субъект.
Кажется, что такой же первый пример у слова все-таки на грамоте:
Я не думал, а все-таки он пришёл.
Поэтому возникает сложность: когда потенциальный союз с частицей в основном значении стоит в начале предложения, то это про целое предложение или про конкретное первое слово? Внутри простого предложения в составе сложного ещё все ухудшается.
Поэтому кажется более логичным считать это просто частицей.

Со словом "даже" точно такая же ситуация + другой аргумент: посмотри названия статей на слово "даже" (везде частица, что доказывает, что частица - основное значение данного слова, не смотря на порядок значений в Викисловаре) 
Это не простая разница, и возможно мы когда-нибудь сможешь ее нормально осмыслить. 

P. S. Я все не могу написать тебе письмо, но я обнаружила в pymorphy2, что ты женские фамилии и отчества объединяешь в парадигму мужской фамилии. Это очень-очень странно. Если в тексте есть Иванова и Иванов, то это все-таки два человека и две сущности. А pymporhy2 приведёт их к одной лемме. Вероятно, ты все объединяешь, между чем у нас есть связи? "Наивысший" тоже например считают отдельным словом от слова "высший" 


Best,
Svetlana Alexeeva

**Comment by kmike** [comment]
Привет. Спасибо, про частицы мнение понял.

Насчет фамилий - это довольно техническая штука. Я не все связи разворачиваю, но многие - это позволяет склонять слова "через" эти связи - например, получить женскую фамилию из мужской через `p.inflect({'famn'})`. Нормализация по дефолту при этом идет в мужскую фамилию, но ничто не мешает нормализовывать фамилии через `p.inflect({'nomn', 'sing'})` - в этом случае получим фамилию того же рода, что и была. Т.е. благодаря "развороту" связей появляются новые возможности.

В идеале бы, конечно, сделать поддержку связей напрямую (чтоб и лексемы были без развернутых связей, и склонять по связям можно было), но пока это не реализовано - там надо менять формат того, как все хранится и тд, чтоб по-прежнему быстро работало.
