### ISSUE TITLE
[Корпус] Как быть с ошибками в корпусе

### ISSUE THREAD

**Issue by hdhkhrnslh723h** [OpenCorpora/opencorpora#754]
А как вы поступаете с опечатками и орфографическими ошибками в исходных предложениях корпуса? Просто оставляете как есть или исправляете?
Вот например в предложении 31893 явно переставлены слова:

В создания модуля «Колумбус» проекте ...

Должно быть:

В проекте создания модуля «Колумбус» ...

**Comment by akmetainfo** [comment]
Опечатки помечаются как опечатки, для этого в интерфейсе модератора есть соответствующая кнопка. 

Действия размечающего в случае, если в примере встретилась опечатка могут разниться.

1. Если опечатка находится не в слове, с которого снимается неоднозначность (выделяется полужирным начертанием и подсвечивается оранжеватым цветом) -- то можете даже комментарий не писать про опечатку: когда-нибудь это слово всё равно попадёт (ну, если там есть хоть какая-то неоднозначность) в разбор -- там-то его и рассмотрят.

2. В случае если опечатка как раз на размечаемом слове -- то нужно нажать кнопку "другое".

Аналогично, ошибки согласования расцениваются как опечатки.

Перестановка слов не учитывается.

PS Мне кажется, что это достаточный ответ и можно закрывать issue? Вот думаю: может подобные вопросы [спрашивать и отвечать в рассылке](https://groups.google.com/forum/?fromgroups#!forum/opencorpora-dev)?
