### ISSUE TITLE
Словарь: добавить устар. форму "те" (тебе)

### ISSUE THREAD

**Issue by akmetainfo** [OpenCorpora/opencorpora#755]
Достаточно много попадается примеров, когда "те" разбирается в ADJF:
>  	контекст Слава **те** господи , ........
    тот, ADJF, Subx, Apro, Anph, plur, nomn
    тот, ADJF, Subx, Apro, Anph, inan, plur, accs

Может быть есть смысл добавить разбор в парадигму для [ты](http://opencorpora.org/dict.php?act=edit&id=352128) с пометой "устар"?

@svbichineva

**Comment by svbichineva** [comment]
Она уже давно добавлена 

Best,
Svetlana Alexeeva
