### ISSUE TITLE
Новые типы пулов

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#757]
А у меня такой вопрос. Когда в самом начале создавались разные типы пулов, это был какой-то скрипт, который ходил по корпусу, или вручную неоднозначности находились? Спрашиваю потому, что вижу много омонимий, которых пока нет в "поиске примеров" и которые изначально были в словаре (т.е. в словарь не добавлялись новые разборы для слов). Так вот, надо ли об этих омонимиях рапортовать или их программа может найти?

Несколько примеров оппозиций:
- CONJ INFN NOUN (_знать_) - 133
- NOUN CONJ ADJS (_право_) - 134
- ADJS ADVB PRCL PRED (_хорошо_) - 141
- ADVB PREP ADJS (_согласно, относительно_) - 144
- VERB NOUN ADJF (_весь_) - 135
- NOUN PRTF (_вселенная_) - 145
- CONJ NOUN ADJF (_главное_) - 162 (скорее всего пересечётся с 118)
- NOUN ADJF PRTF (_данные_) - 163
- ADJF NPRO NOUN (_любой_) - 164
- ...

**Comment by svbichineva** [comment]
Да, надо рапортовать.
Все типы пулы создавались вручную Витей, он как-то сам находил случаи омонимии 

Best,
Svetlana Alexeeva

**Comment by grandsbor** [comment]
Нет, часть создавалась мной. У меня есть скрипт, который ищет омонимии

**Comment by Shimorina** [comment]
Спасибо, понятно. В любом случае это задача про то, что было бы здорово создать новые типы пулов. Можно начать с тех, которые противопоставляются только по частям речи (как в примерах выше).

Ну и чтобы в голове не держать, напишу, какие ещё омонимии вижу:

- NOUN INTJ PRCL (_спасибо_)

- ADJF: masc femn neut (для неизменяемых прил.)

- ADJF: nomn gent datv accs ablt loct (для неизменяемых прил.)

- PRTF, sing: gent vs. accs

- нарицательное vs топоним (_марке, пара, полесье_)

- нарицательное vs фамилия (_чайка_)

- аббревиатура или нет (_рис_)

- NOUN: masc femn neut (_пол, пола, поле_ в предложном падеже)

- плюралиатантум или нет (_ворот/ворота, час/часы_)

**Comment by grandsbor** [comment]
> CONJ INFN NOUN (знать)

этот создал

**Comment by grandsbor** [comment]
> NOUN CONJ ADJS (право)

http://opencorpora.org/pools.php?act=candidates&pool_type=134

> VERB NOUN ADJF (весь)

http://opencorpora.org/pools.php?act=candidates&pool_type=135

**Comment by Shimorina** [comment]
У слова _все/всё_ добавился новый разбор как частица, поэтому надо теперь создать пул для него как:
- ADVB ADJF PRCL

Практически нет пулов с предикативами:
- INTJ PRCL PRED (для слова _нет_, там уже инструкция есть)
- PRED ADJS  (_должно, нужно_)
- PRED NOUN (_пора, лень, охота, грех, неохота_)
- PRED VERB (_жаль_)
- CONJ INFN PRED (_видать_)

**Comment by svbichineva** [comment]
- ADJS NUMR ADVB (_мало_)

**Comment by Antfed** [comment]
Омонимии между изъявительным и повелительным наклонениями:

- глагол в наст/буд вр., 2л. мн.ч.  vs императив (сидите, поделите, дышите и т.д.)

- глагол в пр.вр., мн.ч. vs императив (пили, пали, дели, сели и др.)

- глагол в наст/буд вр., 2л. ед.ч. vs императив (ешь, съешь и т.п.)

**Comment by grandsbor** [comment]
@Antfed так вроде есть такие пулы?

**Comment by Antfed** [comment]
Есть пул  "Глагол: 1 лицо, будущее время / повелительное наклонение", а больше пулов с повелительным наклонением я не вижу. Где они?

**Comment by grandsbor** [comment]
Да, и правда, нет. Сделаем.

**Comment by Antfed** [comment]
омонимия  краткое прилагательное vs глагол в прошедшем времени
(смел, смела, смело, вял)
По словарю opencorpora сюда также попадают слова "горел", "устал", но употребление их как кратких прилагательных кажется сомнительным.

Есть похожий пул:
 VERB&1per&plur@ADJS
Глагол, 1 лицо, множественное число@краткое прилагательное
Имя пулов: Глагол / краткое прилагательное

Исходя из имени пулов Глагол / краткое прилагательное они должны включать слова типа "смел", но по условиям они такие слова не включают.

**Comment by Antfed** [comment]
ADVB NPRO (что-то, чего, чего-то)

**Comment by Antfed** [comment]
ADVB NPRO PRCL (ничего)

**Comment by Antfed** [comment]
ADVB ADJS INTJ (здорово)
ADVB ADJS PRCL CONJ (точно)
ADVB CONJ NOUN (раз)
ADVB ADJS PRCL (полно) (а междометием оно не может быть?)
NOUN  INTJ (батюшки, топ) (наверно сюда же слова матушки, караул, марш, для которых пока нет их разбора как междометий )
GRND ADJS (брав)

**Comment by Antfed** [comment]
INTJ ADJS ADVB (браво) (наречия браво пока нет в словаре)

**Comment by Antfed** [comment]
ADVB ADJS PRCL CONJ NOUN (ровно, добро)
ADVB ADJS CONJ (очевидно, равно, верно)
ADVB ADJS PRCL (ладно)
ADVB CONJ COMP PREP (ниже)
NOUN PRCL CONJ (правда) (есть NOUN&Name PRCL CONJ)
ADVB PRCL NOUN (куда)
ADVB ADJF CONJ (отчего)
NUMR ADVB CONJ (столько)
ADJS PRCL CONJ (конечно)
PRCL INTJ NOUN (ага)
PRCL NOUN (мол)
PREP ADJS (прям, касательно)

**Comment by Antfed** [comment]
NOUN PREP CONJ (типа)

**Comment by Antfed** [comment]
PRED ADJS CONJ (видно)
ADVB ADJS VERB (пошло)

**Comment by Antfed** [comment]
ADVB ADJS PRCL CONJ (собственно)
ADVB ADJS PRTS CONJ (видимо)
ADVB PREP CONJ (напротив)
PRED ADJS NOUN (ведомо) (а существительное "ведомо" вообще существует?)
VERB CONJ PRCL (пожалуй)
VERB CONJ ADJS (допустим)
VERB CONJ ADVB (почитай)
VERB PRCL ADVB (почти)
NOUN ADJS PRTS (катана, белен)
NOUN ADJS ADJF (гол) (гол.=голландский)
ADJS NPRO (нем) (может быть ещё прилагательное нем.=немецкий)
ADJS ADJF (адов, чёртов) (как тут различать?)

**Comment by Antfed** [comment]
PREP CONJ NOUN (плюс, минус)
NOUN ADJF VERB (простою)
ADVB GRND (зря)
ADJS PRCL (прям)

**Comment by Antfed** [comment]
PRCL PREP (ок)

**Comment by Antfed** [comment]
NPRO ADJF NOUN PRCL (сем)
NPRO PRCL (себе)

**Comment by Antfed** [comment]
VERB ADVB NOUN (порой)

**Comment by victorbocharov** [comment]
Напротив созданный типов поставил их номер из базы. Остальные создам сегодня.
Если кто-то будет создавать сам - отпишитесь прямо напротив запроса (отредактируйте комментарий), т.к. база не умеет говорить, что такой тип пула уже есть.

**Comment by Antfed** [comment]
тип пула 141 NOUN ADJF VERB уже был (тип пула 135 http://opencorpora.org/pools.php?act=candidates&pool_type=135)

**Comment by grandsbor** [comment]
переставил тип 141 на ADJS ADVB PRCL PRED

**Comment by Antfed** [comment]
VERB COMP (умней)
VERB COMP NOUN (зеленей)
VERB COMP ADJF (свежей)
VERB COMP NOUN ADJF (синей)
ADJS ADVB PRED
VERB INFN (есть, напрячь)
GRND NOUN ADJF (съезжая)

**Comment by Antfed** [comment]
COMP CONJ (скорее)
PRCL NOUN (бен, фон)
CONJ PRCL NOUN (ж)
CONJ INTJ PRCL NOUN (а, и)
INTJ PRCL NOUN (о, у)

**Comment by victorbocharov** [comment]
@grandsbor CONJ@NOUN@PRCL (ж) - не пересечётся ли с типом 119?

**Comment by Antfed** [comment]
В 4-ом комментарии  NOUN INTJ PRCL (спасибо) уже создан (тип 161)

**Comment by victorbocharov** [comment]
@Antfed отметил в 4-ом комментарии

**Comment by Antfed** [comment]
INTJ PREP NOUN (о, у)

**Comment by Antfed** [comment]
NOUN:  nomn accs ablt (райком, полом, паром)

**Comment by Antfed** [comment]
NOUN: ablt loct (золотом)

**Comment by victorbocharov** [comment]
@grandsbor
Как сделать вот такие?

- нарицательное vs топоним (марке, пара, полесье)
- нарицательное vs фамилия (чайка)

**Comment by grandsbor** [comment]
Никак. Доделаем.

5 янв 2017 г. 21:49 пользователь "Victor Bocharov" <notifications@github.com>
написал:

**Comment by Antfed** [comment]
прилагательные: качественные vs относительные (основным)

**Comment by victorbocharov** [comment]
@Antfed похоже, что этот ждёт обновления в коде, т.к. пулы типа "есть Х @ нет X" мы пока делать не умеем.

**Comment by Antfed** [comment]
NOUN: gent accs loct (девах)

**Comment by victorbocharov** [comment]
@Antfed, нужен ли аналог 131 для единственного числа?

**Comment by Antfed** [comment]
Нет, наверное

**Comment by Antfed** [comment]
PRTF tran intr (считающий)
PRTF perf impf (спавший)
GRND tran intr (тая)
GRND perf impf (спав, считав)
NOUN nomn voct (лев)
CONJ GRND PRCL (хотя) (есть инструкция http://opencorpora.org/manual.php?pool_type=88, стоит при типе пулов GRND@CONJ)
существительное: имя vs не имя (лев) (есть тип NOUN&Name&anim@NOUN&inan) (требует обновления кода)

**Comment by Antfed** [comment]
PRTS perf impf (изолирован)

**Comment by Antfed** [comment]
ADVB ADJS PRTS (осязаемо)

**Comment by Antfed** [comment]
NUMR gent datv ablt loct (сорока)
NOUN datv accs (леху)
NOUN&sing&masc nomn gent (леха)

**Comment by Antfed** [comment]
ADVB ADJS CONJ PREP (соответственно)

**Comment by Antfed** [comment]
NPRO datv ablt (ей; может быть ещё gent)

**Comment by Antfed** [comment]
NPRO femn neut (самоё/самое)

**Comment by Antfed** [comment]
ADJS PRTS VERB (читаем)

**Comment by Antfed** [comment]
У слов труся, гнуся может быть омонимия: деепричастие vs ненормативная форма глагола.

**Comment by Antfed** [comment]
GRND PRTF (питая)
GRND PRTF ADJF (витая)

**Comment by victorbocharov** [comment]
@Antfed 
> NPRO datv ablt (ей; может быть ещё gent)
в каком случае gent?

> ещё "им", "ним" тоже NPRO datv ablt или NPRO sing plur

NPRO&sing @ NPRO&plur - 184
http://opencorpora.org/pools.php?act=candidates&pool_type=184

**Comment by Antfed** [comment]
В викисловаре https://ru.wiktionary.org/wiki/она есть просторечные формы родительного падежа - ей, ней. У нас есть ней в род. падеже, но нет ей в род. падеже.

**Comment by Antfed** [comment]
PRTF ADJF COMP (бодрящее)

**Comment by grandsbor** [comment]
> PRTF ADJF COMP (бодрящее)
Ну это треш, "бодрящее" как компаратив надо стереть.

**Comment by Antfed** [comment]
Может быть, не только "бодрящее" как компаратив  надо стирать.

**Comment by grandsbor** [comment]
Конечно, не только, см. #653

**Comment by Antfed** [comment]
Может быть, ещё есть причастия с лишним разбором их как компаративов.

**Comment by grandsbor** [comment]
Наверняка есть. Это всё про тикет #653.

**Comment by Antfed** [comment]
Ещё возможные типы пулов:
NUMR masc neut (два, оба, обоих)
NUMR masc neut femn (двух)
NPRO masc neut (его) (или это как-то по-другому потом?)

Слово "давай" в словаре OpenCorpora только глагол. Ещё нужно добавить частицу (=пусть) и междометие (=до свидания). Тогда понадобится ещё 1 тип пула - VERB PPRCL INTJ.

Слово "тоще" в словаре краткое прилагательное. Ещё, в принципе, оно может быть наречием и компаративом.

**Comment by Antfed** [comment]
NOUN ADVB ADJF CONJ (т)
NOUN PREP PRCL (с)

**Comment by Antfed** [comment]
COMP CONJ NOUN (короче)

**Comment by Antfed** [comment]
NOUN PRTS VERB (валим)

**Comment by Antfed** [comment]
ADJF COMP NOUN (рыжее)

**Comment by Antfed** [comment]
ADJF VERB PRTS (моем)

**Comment by Antfed** [comment]
ADVB CONJ NOUN PRTS VERB (случаем)

**Comment by Antfed** [comment]
ADJS NOUN VERB (смела)

**Comment by Antfed** [comment]
NPRO nomn gent accs (чего)

**Comment by Antfed** [comment]
INTJ NOUN PRED (амба)

**Comment by Antfed** [comment]
INTJ NOUN PRED VERB (пас)

**Comment by Antfed** [comment]
INTJ PRED (хвать)

**Comment by Antfed** [comment]
ADJF INTJ PRCL (то-то)

**Comment by Antfed** [comment]
Для краткого прилагательного "бела": обычная форма, женский род / мужской род, род.п. (средь бела дня).

Для слова "баю", возможно, нужен разбор как междометия. Тогда понадобится тип пула INTJ NOUN VERB.

**Comment by Antfed** [comment]
ADJS CONJ (вестимо)

**Comment by Antfed** [comment]
Тип 194 http://opencorpora.org/pools.php?act=candidates&pool_type=194  даёт неправильные примеры.

**Comment by grandsbor** [comment]
> Тип 194 http://opencorpora.org/pools.php?act=candidates&pool_type=194 даёт неправильные примеры.

Ого, спасибо, посмотрю

**Comment by grandsbor** [comment]
[Добавил](http://opencorpora.org/pools.php?act=candidates&pool_type=212) поддержку отрицания в поле "граммемы"

**Comment by Shimorina** [comment]
Здорово! А можно тогда создать тип Init vs not Init для инициалов, чтобы они туда собирались, а не в оранжевый одуш-неодуш?

**Comment by grandsbor** [comment]
Ага, [сделал](http://opencorpora.org/pools.php?act=candidates&pool_type=214)

**Comment by grandsbor** [comment]
Но напоминаю, что собираться они будут и туда и туда. Кто первый опубликуется, там они и будут

**Comment by Shimorina** [comment]
Для существительных третьего склонения:

- gent@datv@(loc1|loc2)

- loc1@loc2

**Comment by Antfed** [comment]
Создал тип аббревиатура/ не аббр из 4-го комментария.

**Comment by Antfed** [comment]
неизменяемое@изменяемое (виски) - 229

**Comment by grandsbor** [comment]
Зафорсил поиск примеров для новых пулов, начиная с 224, можно смотреть

**Comment by Antfed** [comment]
Фамилия / Не фамилия из 4-го комментария - 236

**Comment by Antfed** [comment]
Инициалы: имя/отчество/(фамилия)

**Comment by Antfed** [comment]
Сингуляриятантум или нет (вёдро/ведро)

**Comment by Antfed** [comment]
Компаративы: Cmp2 (форма на по-)/ не Cmp2 (Сейчас такую неоднозначность в словаре имеют слова победнее, пожухлее, пороговее, породнее, посильнее, постыднее и др.)

**Comment by Antfed** [comment]
В типе 213 Вводное слово / Частица / Глагол http://opencorpora.org/pools.php?act=candidates&pool_type=213 надо заменить слова "вводное слово" на "союз". ("пускай" - не вводное слово)

**Comment by Antfed** [comment]
Создал плюралиатантум или нет из 4-го комментария - 244

**Comment by Antfed** [comment]
loc1@loc2 - 247

**Comment by Antfed** [comment]
Сейчас слова "двоим", "троим" имеют неоднозначность NUMR VERB PRTS. Краткие причастия "двоим", "троим", возможно, надо удалить.

**Comment by Antfed** [comment]
ADJS NUMR (мала, достаточна) - 252

**Comment by Antfed** [comment]
Прилагательное: притяжательное/ не притяжательное (адовым,чёртовым) - кажется, неразрешимая омонимия.
