### ISSUE TITLE
Отказаться от модерации

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#764]
cc @victorbocharov @madfriend 

Есть такая задача:
>  4. API "перестать быть модератором текста"

Это про что конкретно? Если модератор уже что-то сделал, он может перехотеть быть модератором?

**Comment by madfriend** [comment]
Уже сделали. Работает так: есть группа модераторов NE. На страничке ner.php они видят список текстов с полностью завершенной разметкой. С каждым текстом они могут сделать следующее:

- стать модератором (если у книги пустой moderator_id): текущий пользователь записывается как модератор книжки, на него открывается разметка всех параграфов, он видит чужую разметку во вкладках (у каждого абзаца), может ее копировать себе или может размечать самостоятельно.

- продолжить модерацию (текущий пользователь является модератором книжки и он пока не нажимал "завершить модерацию"): открывается книжка с модераторской разметкой, которую можно редактировать дальше.

- завершить модерацию  (текущий пользователь является модератором книжки и он пока не нажимал "завершить модерацию"): вся модераторская разметка в книжке "закрывается" (нельзя внести изменения).

- возобновить модерацию (у книжки есть модератор, но разметка им закрыта): текущий пользователь становится модератором книжки, разметка предыдущего модератора к этой книжке переписывается на него (меняем там ключ user_id), все абзацы снова открываются для редактирования.

**Comment by grandsbor** [comment]
Ага, ок
