### ISSUE TITLE
Дамп корпуса не содержит недавно добавленных текстов

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#773]
В дампе последний токен - 1744870. В базе - 1988207.
Думаю, что уже можно выгружать все.

**Comment by grandsbor** [comment]
В завтрашнем дампе должно стать ок

**Comment by grandsbor** [comment]
@victorbocharov В статистике разметки тексты, которые были скрытыми, тоже начали учитываться. Статистика считается по дампу, так что это неизбежно

**Comment by grandsbor** [comment]
См. скачок на графиках 23-24 августа

**Comment by victorbocharov** [comment]
вижу. спасибо!
