### ISSUE TITLE
Ошибка в базе - неверный pos у предложения

### ISSUE THREAD

**Issue by irinfox** [OpenCorpora/opencorpora#775]
Заметила, что в базе два предложения в рамках одного абзаца и одного текста имеют одинаковый pos.
http://opencorpora.org/books.php?book_id=961

Книга: 961
Абзац: 9460
Предложения: 29178, 29179 

У предложения 29179 надо поменять pos=1 на pos=2 в прод-базе.

**Comment by grandsbor** [comment]
Done. Интересно, что это было.
