### ISSUE TITLE
Не публикуются примеры

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#776]
Новые примеры ищутся, но перестали выкладываться:
http://www.opencorpora.org/pools.php?type=1

Это так и надо?

**Comment by grandsbor** [comment]
Сейчас всё так же?

**Comment by Shimorina** [comment]
Надо посмотреть.

В последний раз, когда нашлись новые примеры (а это было давно), они выложились только через несколько дней.

**Comment by grandsbor** [comment]
Сейчас выглядит так, что всё, что выклыдвается само (т.е. с проставленной сложностью и инструкцией), выложено

**Comment by Shimorina** [comment]
Да.
Вопрос возник из-за того, что раньше примеры выкладывались сразу, как нашлись, а сейчас надо ждать n дней, чтобы они выложились.
Я же не знаю, может это что-то в алгоритме поменялось.

**Comment by grandsbor** [comment]
Нет, в алгоритме вроде ничего не меняли

**Comment by grandsbor** [comment]
Судя по (нашим очень плохим) логам, в какой-то момент на машине кончалось место, из-за этого что-то зависало, база была в read-only и примеры не выкладывались

**Comment by grandsbor** [comment]
Судя по всему - это было в середине ноября

**Comment by Shimorina** [comment]
понятно, спасибо. Можно, наверно, закрыть задачу -- на ваше усмотрение.

**Comment by grandsbor** [comment]
Если ещё такое будет, переоткроем
