### ISSUE TITLE
прилагательное "барный"

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#778]
Если не трудно, можете добавить прилагательное "барный" в словарь? См. https://groups.google.com/forum/#!topic/pymorphy/9lF9RZdO08I

**Comment by grandsbor** [comment]
Добавил: http://opencorpora.org/dict.php?act=edit&saved&id=390216
Завтра будет в выгрузке

**Comment by kmike** [comment]
Ничего себе скорость 👍
