### ISSUE TITLE
мхат - нужна Abbr?

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#785]
cc @svbichineva 
http://opencorpora.org/dict.php?act=edit&id=165709

**Comment by grandsbor** [comment]
cc @Shimorina

**Comment by Shimorina** [comment]
Если делать последовательно, то ещё у следующих звуковых аббревиатур (по аналогии с _мхатом_) нет в словаре пометы Abbr: _вуз, загс, вак, омон_.

**Comment by svbichineva** [comment]
добавили
