### ISSUE TITLE
спенсер - неод.?

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#790]
Есть 2 леммы "спенсер":
- http://opencorpora.org/dict.php?act=edit&id=331748 - неод
- http://opencorpora.org/dict.php?act=edit&id=331749 - неод, гео

Я не нашёл, что такое спенсер, если не имя собственное, так что первую предлагается стереть (а скорее, поставить одуш+имя/фамилия)

cc @svbichineva, @Shimorina

**Comment by Shimorina** [comment]
пишут, что неодушевлённое это вид одежды: http://dic.academic.ru/dic.nsf/dic_fwords/34008/%D0%A1%D0%9F%D0%95%D0%9D%D0%A1%D0%95%D0%A0

**Comment by grandsbor** [comment]
А, хорошо, тогда имя и фамилию отдельно добавлю
