### ISSUE TITLE
возможность добавлять "частично правильно" в уже возвращенные пулы

### ISSUE THREAD

**Issue by svbichineva** [OpenCorpora/opencorpora#791]
в идеале - специальный интрефейс
если нет, то поправить вручную:
http://opencorpora.org/pools.php?act=samples&pool_id=3337&ext&filter=&sortby=text&skip=90 - частично правильно примеру про человека-мухоловку

заменить опечатку на частично правильно у слова "маргарита"
http://opencorpora.org/pools.php?act=samples&pool_id=579&ext&filter=focus&sortby=&skip=30

добавить частично правильно слову "лице"
http://opencorpora.org/pools.php?act=samples&pool_id=654&ext&filter=&sortby=text&skip=75

частично правильно слову "Звезда" (модуль Звезда) 
http://opencorpora.org/pools.php?act=samples&pool_id=655&ext&filter=&sortby=text&skip=45

**Comment by grandsbor** [comment]
Поставил руками.
