### ISSUE TITLE
Ms-f, GNdr и фамилии

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#795]
1. переименовать Ms-f в ms-f, создать другую Ms-f в пометах
2. у фамилий мн.ч стереть GNdr, Ms-f заменить на ms-f

**Comment by grandsbor** [comment]
cc @victorbocharov @svbichineva 
А ещё у нас есть неизменяемые фамилии, где множественное число [входит](http://opencorpora.org/dict.php?act=edit&id=378913) в парадигму единственного. Их это не коснулось. Это надо их разбить на ед.ч и мн.ч., как предлагается в тикете #51?

**Comment by grandsbor** [comment]
Собственно, в [списке ошибок](http://opencorpora.org/dict.php?act=errata) почти только незименяемые фамилии.

**Comment by grandsbor** [comment]
Для простоты сделал в неизменяемых фамилиях такую же замену, осталось что-то около 600 ошибок.

**Comment by svbichineva** [comment]
Заменить
1. anim, femn, Ms-f -> anim, ms-f (слова типа зануда)
2. anim, masc, Ms-f -> anim, ms-f

сформировать список (предположительно, ошибки): 
anim, GNdr, Ms-f

**Comment by grandsbor** [comment]
Есть имена, которые не укладываются в пункт 1 и 2 выше:
```
валентуля
валечка
женечка
женька
шура
шурка
шурочка
паша
данте (?!)
слава
саша
женя
валя
```

плюс все инициалы

**Comment by svbichineva** [comment]
Думаю, всем, кроме Данте нужно сделать преобразование типа 1:
anim, femn, Ms-f, Name -> anim, ms-f, Name

Настя, согласна?
Дима, они не укладываются в тип 1 из-за Name?

**Comment by grandsbor** [comment]
Ну да, из-за Name.
А инициалы?

**Comment by svbichineva** [comment]
не исправлено: http://opencorpora.org/dict.php?act=edit&id=290208
думаю, что инициалы также:
anim, Init, GNdr, Ms-f -> anim, Init, ms-f

**Comment by grandsbor** [comment]
Инициалы сделал

**Comment by grandsbor** [comment]
@svbichineva 
касается ли этот тикет слов типа "выхухоль", "псина", "колибри", имеющих `anim, masc/femn, Ms-f`? Валидатор считает их ошибками.

**Comment by grandsbor** [comment]
Также есть подмножество слов, у которых есть `GNdr`, 23 штуки:
```
ЗАВКАДРАМИ
ЗАВКЛУБОМ
ЗАВОБЛОНО
ЗАВСЕКТОРОМ
КЕЧУА
КОМИ
МАЙЯ
МАНСИ
МАРИ
ПАРВЕНЮ
ПРЕДМЕСТКОМА
РАМОЛИ
СААМИ
СУОМИ
ТРАВЕСТИ
ТУТСИ
УДЭ
УДЭГЕ
УЛЬТРА
ХАУСА
ХИППИ
ЦИРЛИХ-МАНИРЛИХ
ИННУ
```

**Comment by grandsbor** [comment]
Итого сделал замену во всех словах, кроме слов с GNdr (список выше), неизменяемых, а также обозначающих животных (на всякий случай).

Ещё есть 3 слова с Pltm, с ними тоже что-то надо сделать. Это слова: подсудимые, подследственные, вожатые.

**Comment by Shimorina** [comment]
Всё сделали. Запротоколировано [тут](http://opencorpora.org/wiki/%D0%A3%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8F#.D0.9A.D0.B0.D1.82.D0.B5.D0.B3.D0.BE.D1.80.D0.B8.D1.8F_.D1.80.D0.BE.D0.B4.D0.B0).

Осталось:
- добавить правила для Ms-f в граммемы (может быть: femn + Ms-f, masc + Ms-f, neut + Ms-f
не может быть: ms-f + Ms-f)
- перезапустить проверку словаря на ошибки

**Comment by grandsbor** [comment]
Done

> Всё сделали. Запротоколировано [тут](http://opencorpora.org/wiki/%D0%A3%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8F#.D0.9A.D0.B0.D1.82.D0.B5.D0.B3.D0.BE.D1.80.D0.B8.D1.8F_.D1.80.D0.BE.D0.B4.D0.B0).
> 
> Осталось:
> 
> * добавить правила для Ms-f в граммемы (может быть: femn + Ms-f, masc + Ms-f, neut + Ms-f
>   не может быть: ms-f + Ms-f)
> * перезапустить проверку словаря на ошибки

**Comment by Shimorina** [comment]
По-моему, правило для Ms-f добавлено немного не то, и снова в словаре ошибка "неразрешённая граммема" со словами вида _кофе_

> Осталось:
> 
>     добавить правила для Ms-f в граммемы (может быть: femn + Ms-f, masc + Ms-f, neut + Ms-f
>     не может быть: ms-f + Ms-f)
>     перезапустить проверку словаря на ошибки

**Comment by grandsbor** [comment]
Правило добавлено нормальное, но оно размножается и даёт такой эффект, потому что, оказывается, у нас `masc` и `femn` (но не `neut`) являются дочерними от `ms-f`. Видимо, это уже не так и надо поправить?

**Comment by Shimorina** [comment]
Это как раз [правильно](http://opencorpora.org/wiki/%D0%A3%D1%81%D1%82%D1%80%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE_%D1%81%D0%BB%D0%BE%D0%B2%D0%B0%D1%80%D1%8F#.D0.9A.D0.B0.D1.82.D0.B5.D0.B3.D0.BE.D1.80.D0.B8.D1.8F_.D1.80.D0.BE.D0.B4.D0.B0).
Мне кажется, это правила для Ms-f не те. Ms-f может встречаться с masc, femn, neut.

**Comment by grandsbor** [comment]
У нас есть система вывода правил, которая говорит, что если граммема А запрещает граммему Б у той же лексемы, то она запрещает также и все дочерние граммемы граммемы Б.

**Comment by Shimorina** [comment]
Тогда может убрать правило, что "ms-f запрещена с Ms-f"?

**Comment by grandsbor** [comment]
Я развернул правило, 20 ошибок этого вида ушли. Здесь ещё что-то осталось?

**Comment by Shimorina** [comment]
Спасибо! Закрываю
