### ISSUE TITLE
Недостаточные глаголы (победить, убедить)

### ISSUE THREAD

**Issue by Antfed** [OpenCorpora/opencorpora#796]
Сейчас у глаголов "победить", "убедить" в словаре стоит без особых помет форма 1л. ед.ч. "побежу", "убежу". При этом  у глагола "бдить" форма 1л. ед.ч. отсутствует. Может быть, надо поставить помету Infr или удалить формы 1л. ед.ч.

**Comment by grandsbor** [comment]
cc @svbichineva @Shimorina

**Comment by Shimorina** [comment]
Спасибо! Для таких случаев мы создали новую помету Hypo (гипотетическая форма). Потом её планируется также использовать для форм сравнительной степени и компаративов у относительных прилагательных. Т.е. не удалять эти формы, а приписать помету "гипотетическая форма".

Мы также добавили правила в Ограничения на граммемы, но часть слов, которым помета была добавлена ранее правил, сейчас содержат ошибки. Видимо, надо перезапустить нахождение ошибок в словаре или что-то в этом роде, чтобы ошибки исчезли.

**Comment by grandsbor** [comment]
Флаг проверки сбросил у текущих ревизий
