### ISSUE TITLE
Омонимия с и без Pltm

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#798]
cc @svbichineva, @Shimorina 

Всего 338 случаев.

45 - когда Pltm это топоним ([список](https://yadi.sk/i/cxxHHl4V3AU4Sf)), например, ПЕТУШКИ, СЛАНЦЫ
В этом списке, скорее всего, всё более-менее ок.

168 - когда Pltm это фамилия ([список](https://yadi.sk/i/AOPekVgH3AU35K)), например, БАЛАШОВЫ. Здесь разные случаи.
85 - всё остальное ([список](https://yadi.sk/i/S1nW9cd23AU6EP)), вот здесь может быть интересное. Например, ГАЛИФЕ, ПОРШНИ.

**Comment by svbichineva** [comment]
проверила первый список, который на 45 слов

**Comment by Shimorina** [comment]
Done.

Наш [лог](https://github.com/OpenCorpora/opencorpora/files/1610113/pltm.txt) списка 3.
[Лог](https://github.com/OpenCorpora/opencorpora/files/1610112/Pltm_vs_plur.Surn.txt) списка 2.
