### ISSUE TITLE
Ли - фамилия

### ISSUE THREAD

**Issue by Antfed** [OpenCorpora/opencorpora#799]
Кроме имени Ли существует и фамилия Ли (например в текстах встречается: "также Дженни Ли ( использовала "(из http://opencorpora.org/pools.php?act=candidates&pool_type=119)). Надо добавить лемму.

**Comment by Antfed** [comment]
А имя Ли вообще существует? В Википедии https://ru.wikipedia.org/wiki/Ли есть фамилия Ли, а имени нет.

**Comment by Antfed** [comment]
Слова "Ли" сейчас в найденных примерах для типа 215 Имя / Не имя http://opencorpora.org/pools.php?act=candidates&pool_type=215. Пока что не стоит давать этот тип пула на разметку.

**Comment by Antfed** [comment]
Может быть переделать тип  215 Имя / Не имя в тип Имя, фамилия или отчество / ничего из этого.

**Comment by Shimorina** [comment]
Есть такой вариант. Добавить в инструкцию правило, что если встретилась фамилия Ли, то нажимаем имя и пишем комментарий фамилия. При модерации выбирать Имя + Нет правильного разбора. Потом всем unk припишется новый разбор из словаря, когда добавим новую лемму с фамилией.

**Comment by Antfed** [comment]
Можно так.

**Comment by grandsbor** [comment]
Такие пулы ещё не опубликованы, сейчас просто добавим имя "Ли" в словарь и попросим робота ещё раз поискать задания в имя/не имя

**Comment by grandsbor** [comment]
Собственно, сделал
