### ISSUE TITLE
лишние граммемы Anph

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#802]
Во многих предложениях местоимения _им, ним, него_ (и наверно другие есть) имеют по три или две граммемы Anph.
Например, http://opencorpora.org/sentence.php?id=2255

**Comment by Shimorina** [comment]
два раза граммема Inmx: http://opencorpora.org/diff.php?sent_id=61351&set_id=21043

**Comment by grandsbor** [comment]
[Починил](http://opencorpora.org/history.php?set_id=23059). Было затронуто почти 4.5 тыс. предложений.
