### ISSUE TITLE
Выдача прав на добавление текстов?

### ISSUE THREAD

**Issue by KashchenkoP** [OpenCorpora/opencorpora#803]
Как выдать пользователю права на добавление текстов в систему?

**Comment by grandsbor** [comment]
cc @victorbocharov

**Comment by victorbocharov** [comment]
Дима, это вопрос не про opencorpora.org, а про локальную копию. Я попросил перенести этот вопрос сюда из диалога ВК, чтобы знания копились в доступном месте.

**Comment by grandsbor** [comment]
Понятно.
Интерфейса для этого нет, нужно залезть в базу и сказать
`insert into user_groups values (USER_ID, 3);`
После этого человек должен перелогиниться

**Comment by KashchenkoP** [comment]
Спасибо. А еще один вопрос есть. Как запустить обучение токенизатора?

**Comment by grandsbor** [comment]
`php scripts/tokenizer/train.php`
