### ISSUE TITLE
пицца - не Sgtm

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#805]
Привет! @avostryakov заметил, что в словаре у слова "пицца" нет множественного числа - см. http://opencorpora.org/dict.php?act=edit&id=239353. Но можно написать 5 пицц, пару пицц (https://ru.wiktionary.org/wiki/%D0%BF%D0%B8%D1%86%D1%86%D0%B0).

**Comment by grandsbor** [comment]
Ага, поправил. В завтрашней выгрузке будет.
