### ISSUE TITLE
Ошибки во мн.ч. (мебель)

### ISSUE THREAD

**Issue by Yiivgeny** [OpenCorpora/opencorpora#808]
Все падежи слова `мебель` множественного числа образованы неверно, к примеру тв.п., мн.ч.  `мебелями`.
http://opencorpora.org/dict.php?act=edit&id=156873

**Comment by grandsbor** [comment]
cc @svbichineva @Shimorina

**Comment by Antfed** [comment]
В НКРЯ есть "мебелями": Они писали и переписывали мириады бумаг; и в этих служебных комнатах с ординарными департаментскими мебелями возникали и исчезали, словно китайские тени, разномастные фигуры повседневной, как всегда, быстротекущей жизни. [Юрий Давыдов. Синие тюльпаны (1988-1989)]

**Comment by grandsbor** [comment]
Можно поставить им Arch, Infr или ещё что-нибудь

**Comment by opennota** [comment]
"Мебеля" хоть устарели, но вполне законны, встречаются у Гоголя, Достоевского, Тургенева и др.

**Comment by Yiivgeny** [comment]
@grandsbor @opennota, выпиливать их даже в голову не приходило. Но хотелось бы иметь аттрибут, чтобы программно иметь возможность выбрать актуальную версию для моих задач. Считаю что `Arch` отлично подходит.

**Comment by Shimorina** [comment]
Хорошо, Arch добавлен.
