### ISSUE TITLE
Новые существительные в словарь

### ISSUE THREAD

**Issue by avostryakov** [OpenCorpora/opencorpora#810]
Можете пожалуйста добавить следующие существительные в словарь:
диабло
буррито (пицца)
пепперони (пицца)
инь-янь
манчини (фамилия)
ниндзя

Самому не получается, наверно нет прав. Буррито, пепперони не склоняются, как я понимаю

**Comment by ins2718** [comment]
А нет возможности как-то автоматизированно добавлять слова? Для своих нужд составлял список существительных и нашлось около 5000 отсутствующих тут.

**Comment by avostryakov** [comment]
Конечно, если бы работало добавление слов в словарь через интерфейс, то я бы сам добавил.

**Comment by grandsbor** [comment]
Мы сами хотим сделать добавление слов в словарь пользователями (и даже, возможно, API для этого), но нет ресурсов

**Comment by avostryakov** [comment]
Допишу сюда добавить слово "ок" в словарь. Оказывается нету

**Comment by Shimorina** [comment]
"ок" найдётся в словаре, если поискать по форме http://opencorpora.org/dict.php?search_form=%D0%BE%D0%BA&act=lemmata

**Comment by avostryakov** [comment]
Дело в том, что pymorphy2 предпочитает лемму около, для ок. Не знаю точно почему, но если бы было слово ок, то все было бы правильно.

**Comment by Shimorina** [comment]
с этим ничего не сделать, поскольку по статистике корпуса "ок." как аббревиатура предлога "около" чаще встречается, чем "ок" как "окей" (см. более высокий score). 
```
Parse(word='ок', tag=OpencorporaTag('PREP Abbr'), normal_form='около', score=0.736842, methods_stack=((DictionaryAnalyzer(), 'ок', 2227, 1),))
Parse(word='ок', tag=OpencorporaTag('PRCL Abbr'), normal_form='окей', score=0.263157, methods_stack=((DictionaryAnalyzer(), 'ок', 3183, 1),))
```

**Comment by Antfed** [comment]
Келли может быть не только именем, но и фамилией. Добавьте, пожалуйста, в словарь.

**Comment by Shimorina** [comment]
> диабло
> буррито (пицца)
> пепперони (пицца)
> инь-янь
> манчини (фамилия)
> ниндзя

> Келли может быть не только именем, но и фамилией. Добавьте, пожалуйста, в словарь.

все слова добавлены
