### ISSUE TITLE
Неточности в разметке. Существительные из одних гласных

### ISSUE THREAD

**Issue by ins2718** [OpenCorpora/opencorpora#811]
Доброго времени суток. Это аббривеатуры и сокращения, но в разметке у них нет меток 'Orgn', 'Trad' или 'Abbr':
Б, БТР, КБ, КВТ, КД, МВТ, МТС, ПГТ, СБС, ТЧК, ЦП, ЦТК, ЧП, КБ, СНВ

**Comment by Shimorina** [comment]
Поправила всё, кроме "б". Может быть не сокращением, а буквой: "суббота пишется с двумя б"

см. также #94
