### ISSUE TITLE
переразобрать "остер" по словарю

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#815]
Когда в словарь добавили _Остер_ как [фамилию](http://opencorpora.org/dict.php?act=edit&id=389916), то почему-то переразбор произошел только у некоторых словоформ (судя по всему у _остер_ и _остера_). По-видимому, другие словоформы не были переразобраны.
Поэтому сейчас в корпусе все словоформы _остеру_ и _остером_ размечены как неодуш вместо фамилии.
Например, см. http://opencorpora.org/sentence.php?id=54266 (в истории нет переразбора)

**Comment by grandsbor** [comment]
Переделал руками, оказалось штук 15 случаев (не все)
