### ISSUE TITLE
в annot.opcorpora.no_ambig ссылка на удалённую лексему

### ISSUE THREAD

**Issue by blabaster** [OpenCorpora/opencorpora#816]
sentence id="39833"
> А в это время в Германии, в ставропигиальном приходе Покрова Пресвятой Богородицы (Дюссельдорф), настоятелем которого является архиепископ Клинский Лонгин, также совершалась Божественная Литургия в честь Казанской иконы Божией Матери.

l id="156297" t="матерь"
Эта лемма удалена:
[http://opencorpora.org/dict.php?search_lemma=матерь&act=lemmata](url)

**Comment by grandsbor** [comment]
Спасибо, обновил. В завтрашнем дампе станет хорошо.
