### ISSUE TITLE
"один" и NUMR

### ISSUE THREAD

**Issue by alexanderkuk** [OpenCorpora/opencorpora#818]
У "один" нет граммемы NUMR. У "два", "три" есть, а у "один" нет. Ошибка или в это есть какой-замысел?
```
from pymorphy2 import MorphAnalyzer
morph = MorphAnalyzer()
morph.parse('один')

[Parse(word='один', tag=OpencorporaTag('ADJF,Apro,Anum masc,sing,nomn'), normal_form='один', score=0.607142, methods_stack=((DictionaryAnalyzer(), 'один', 2239, 0),)),
 Parse(word='один', tag=OpencorporaTag('ADJF,Apro,Anum inan,masc,sing,accs'), normal_form='один', score=0.392857, methods_stack=((DictionaryAnalyzer(), 'один', 2239, 3),))]

morph.parse('два')
[Parse(word='два', tag=OpencorporaTag('NUMR masc,nomn'), normal_form='два', score=0.4, methods_stack=((DictionaryAnalyzer(), 'два', 1280, 0),)),
 Parse(word='два', tag=OpencorporaTag('NUMR inan,masc,accs'), normal_form='два', score=0.2, methods_stack=((DictionaryAnalyzer(), 'два', 1280, 3),)),
 Parse(word='два', tag=OpencorporaTag('NUMR neut,nomn'), normal_form='два', score=0.2, methods_stack=((DictionaryAnalyzer(), 'два', 1280, 9),)),
 Parse(word='два', tag=OpencorporaTag('NUMR inan,neut,accs'), normal_form='два', score=0.2, methods_stack=((DictionaryAnalyzer(), 'два', 1280, 10),))]
```

UPDATE:
Ещё у "ноль" нет NUMR
```
morph.parse('ноль')
[Parse(word='ноль', tag=OpencorporaTag('NOUN,inan,masc sing,accs'), normal_form='ноль', score=0.625, methods_stack=((DictionaryAnalyzer(), 'ноль', 191, 3),)),
 Parse(word='ноль', tag=OpencorporaTag('NOUN,inan,masc sing,nomn'), normal_form='ноль', score=0.375, methods_stack=((DictionaryAnalyzer(), 'ноль', 191, 0),))]
```

**Comment by grandsbor** [comment]
cc @svbichineva @Shimorina

**Comment by Shimorina** [comment]
В этих случаях решение, к какой части речи отнести слово, принималось исходя из его грамматических характеристик.

Так как окончания у слова один совпадают с окончаниями обычных прилагательных, то оно относится к части речи прилагательное (ADJF).
Это отличается от школьной грамматики, где один считается количественным числительным. То же относится к "школьным" порядковым числительным (_второй, пятый, десятый_ и т.д.) -- они также считаются прилагательными из-за их типа словоизменения.
Им всем добавлена граммема Anum.

_Ноль, тысяча, миллион_ и др. считаются существительными (NOUN) по ряду причин:

- У них отсутствует свойство числительных (NUMR) одновременно управлять и согласовываться с последующими существительными.
 
   _доволен новой тысячью рублЕЙ_
   _доволен новыми ста рублЯМИ_

- Они функционируют как другие существительные собирательной семантики (_куча рублей_).

- Также как и у обычных существительных, у этих слов есть множественное число (_нули, миллионы_), у числительных этой характеристики нет.

**Comment by alexanderkuk** [comment]
Ух ты, интересно, спасибо!
