### ISSUE TITLE
Отсутствующие слова

### ISSUE THREAD

**Issue by opennota** [OpenCorpora/opencorpora#819]
боракс
линемёт
луаз
миннефтехимпром
нитратомер
солеразработка
чумка

**Comment by opennota** [comment]
Ping.

**Comment by grandsbor** [comment]
@opennota Не могу не спросить, а эти слова неверно разбираются несловарной морфологией pymorphy? Или вы наш словарь используете непосредственно?

**Comment by opennota** [comment]
@grandsbor В основном непосредственно. Pymorphy2 разбирает правильно, насколько могу судить (как склоняет, не проверял).

"Ниндзя" тоже хорошее слово (замечено в тикете https://github.com/OpenCorpora/opencorpora/issues/810). И вот оно-то разбирается неправильно.

**Comment by Shimorina** [comment]
> боракс
> линемёт
> луаз
> миннефтехимпром
> нитратомер
> солеразработка
> чумка

добавлены
