### ISSUE TITLE
Ошибка. Формы-дубликаты: <человек>, <людей> (gent|plur).

### ISSUE THREAD

**Issue by rrzaripov** [OpenCorpora/opencorpora#822]
http://opencorpora.org/dict.php?act=edit&id=375073

**Comment by svbichineva** [comment]
Как вы видите, ошибка "Формы-дубликаты: <человек>, <людей> (gent|plur)" помечена зеленым и написано, что  "Эта ошибка была помечена как исключение". Это говорит о том, что здесь нет ошибки. Мы не можем поставить одному из варианту "Разговорное" или какое-то другое, так как употребление этих форм подчинено в том числе и семантическим различиям. А мы в данном случае имеем дело с морфологией. Разделить на несколько лемм мы тоже не можем, так как формы ед.ч. совпадут, что вызовет проблемы при разметке этих форм (получится неснимаемая неоднозначность).
Скажите, пожалуйста, наше решение мешает выполнению какой-то вашей задачи? Если да, скажите, что это за задача?

**Comment by rrzaripov** [comment]
@svbichineva теперь мне стало понятнее, спасибо. На самом деле мне это не сильно мешает, просто было несколько неожиданно, когда при согласовании слова 'человек' с числом, я получил 'людей' вместо 'человек'. Можно закрывать эту задачу.
