### ISSUE TITLE
Реализовать переливку пулов с отрицанием

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#823]

**Comment by grandsbor** [comment]
@Shimorina @svbichineva 
Вроде всё готово, попробуйте осторожно запустить один пул в переливку

**Comment by Shimorina** [comment]
Здорово! Запустила один -- вроде всё ок прошло

**Comment by grandsbor** [comment]
Вроде ок - т.е. никаких лишних разборов не стёрлось и наоборот ненужных не
осталось?

28 ноя 2017 г. 12:51 AM пользователь "Anastasia Shimorina" <
notifications@github.com> написал:

**Comment by Shimorina** [comment]
да, всё верно. По крайней мере с пулом Init vs !Init. Могу ещё другой вид запустить?

**Comment by grandsbor** [comment]
Да, давай ещё какой-нибудь.

28 ноя 2017 г. 12:56 AM пользователь "Anastasia Shimorina" <
notifications@github.com> написал:

**Comment by Shimorina** [comment]
Да, с другим тоже всё хорошо!

**Comment by grandsbor** [comment]
Хорошо :)
