### ISSUE TITLE
Получение мета-информации о словаре

### ISSUE THREAD

**Issue by Yiivgeny** [OpenCorpora/opencorpora#826]
Видел, что у сервиса существует API, однако не удалось быстро разобраться. Хотелось бы узнать, можно ли каким то образом получить мета-информацию об актуальном (доступном для скачивания) словаре. Более всего интересует дата последнего обновления или номер ревизии.

Если такой возможности нет, очень хотелось бы её иметь. Заранее спасибо.

Попутно вопрос: истории выгрузок, я так понимаю, тоже нигде не найти, хотелось бы узнать как часто происходит "выкладывание" словаря?

**Comment by grandsbor** [comment]
Нет, отдельного АПИ для версии словаря нет, хотя выглядит как простейшая задача.
Истории нет, выгрузка происходит каждое утро, если за последние сутки была хоть одна правка в словаре.

**Comment by Yiivgeny** [comment]
@grandsbor 
Дело в том, что обновление словаря для меня сопряжено не только для его скачивания. Поэтому хотелось бы сделать всё правильно, и заранее знать стоит ли инициировать процесс обновления или нет. 

Пока отвечал понял, что сам себе придумал проблемы. Ведь можно сделать HTTP HEAD запрос и в заголовках будет ETag и Last-Modified, что полностью покрывает мою задачу.

По поводу выгрузок, сейчас значится дата 06.10.2017, это действительно значит что никто ничего не добавлял в словарь с этой даты? Мне со стороны казалось что активность просто огромная у вас.

**Comment by grandsbor** [comment]
Да нет, не огромная.
[Легко увидеть](http://opencorpora.org/dict_history.php), что последняя правка от 5 октября.

**Comment by grandsbor** [comment]
Ну и раз вы сами придумали решение, то я, пожалуй, тикет закрою :)

**Comment by Yiivgeny** [comment]
Спасибо! В общем для решения моей задачи ничего "доделывать" не нужно.
