### ISSUE TITLE
переразобрать "ничего" из словаря

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#828]
После добавления [леммы "ничего"](http://opencorpora.org/dict.php?act=edit&id=390659), переразобрались только токены "ничё", но не токены "ничего".

**Comment by grandsbor** [comment]
@Shimorina 
Можно добавить новый разбор везде не глядя?

**Comment by Shimorina** [comment]
ага

**Comment by grandsbor** [comment]
Прикольно, баг какой-то

**Comment by grandsbor** [comment]
[Done](http://opencorpora.org/history.php?set_id=21346)
