### ISSUE TITLE
Выпилить sentence check

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#829]
@victorbocharov 

У нас есть старая-престарая фича, что-то вроде модерации токенизации. Такая галочка около предложений в полном виде ([пример](http://opencorpora.org/books.php?book_id=2282&full=1)).

Реально не используется, мешается в коде и интерфейсе. Предлагаю удалить

**Comment by victorbocharov** [comment]
Там, вроде, много этих галок проставлено было. Жалко :-/

27 ноября 2017 г., 23:41 пользователь Dmitry Granovsky <
notifications@github.com> написал:

**Comment by grandsbor** [comment]
Около 4, 5 тысяч на 109 тысяч предложений

**Comment by victorbocharov** [comment]
Если решишь удалять таблицу, забекапь её содержимое на гитхаб, пожалуйста.

2017-11-27 23:59 GMT+03:00 Dmitry Granovsky <notifications@github.com>:

**Comment by grandsbor** [comment]
[sentence_check.sql.gz](https://github.com/OpenCorpora/opencorpora/files/1524741/sentence_check.sql.gz)

**Comment by grandsbor** [comment]
Выпилил.
