### ISSUE TITLE
Дубли по одушевленности

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#830]
- призрак
- существо
- божество

Нам точно для этих слов нужны обе леммы?

**Comment by grandsbor** [comment]
cc @Shimorina @svbichineva

**Comment by Shimorina** [comment]
На мой взгляд, да. Про существо написано в инструкции (человек vs суть дела), призрак - это привидение vs очертание, напоминание. Божество - бог vs предмет поклонения (мы даже начали это слово обсуждать со Светой когда-то, но ещё не закончили)

**Comment by bzaar** [comment]
Божество в [Викисловаре](https://ru.wiktionary.org/wiki/%D0%B1%D0%BE%D0%B6%D0%B5%D1%81%D1%82%D0%B2%D0%BE) одушевленное, неодушевленного варианта нет. Значение 1 "бог" - одушевленное, значение 2 "кумир" - одушевленное. @Shimorina, можете привести пример, где оно было бы неодушевленное? Желательно в форме винительного множественного (почитал божеств/божества?)

В Национальном корпусе бардак:

"[Во Христе полнота Божества обитала телесно.](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&spd=&text=lexgramm&mode=main&sort=gr_tagging&lang=ru&nodia=1&parent1=0&level1=0&lex1=%E1%EE%E6%E5%F1%F2%E2%EE&gramm1=inan&sem1=&sem-mod1=sem&sem-mod1=sem2&flags1=&m1=&parent2=0&level2=0&min2=1&max2=1&lex2=&gramm2=&sem2=&sem-mod2=sem&sem-mod2=sem2&flags2=&m2=&docid=115234)" - неод.

"[Но умирает-то Спаситель наш Христос как человек: не Божеством Своим бессмертным, а человеческим Своим, живым, подлинно человеческим телом.](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&spd=&text=lexgramm&mode=main&sort=gr_tagging&lang=ru&nodia=1&parent1=0&level1=0&lex1=%E1%EE%E6%E5%F1%F2%E2%EE&gramm1=anim&sem1=&sem-mod1=sem&sem-mod1=sem2&flags1=&m1=&parent2=0&level2=0&min2=1&max2=1&lex2=&gramm2=&sem2=&sem-mod2=sem&sem-mod2=sem2&flags2=&m2=&p=1&docid=115251)" - одуш.

Где логика?

**Comment by bzaar** [comment]
Просмотр первых 5 страниц выдачи поиска [божество, acc,pl](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&spd=&text=lexgramm&mode=main&sort=gr_tagging&lang=ru&nodia=1&parent1=0&level1=0&lex1=%E1%EE%E6%E5%F1%F2%E2%EE&gramm1=acc%2Cpl&sem1=&sem-mod1=sem&sem-mod1=sem2&flags1=&m1=&parent2=0&level2=0&min2=1&max2=1&lex2=&gramm2=&sem2=&sem-mod2=sem&sem-mod2=sem2&flags2=&m2=&p=0) не выявил неодушевленных божеств. Там только примеры с неснятой омонимией.

**Comment by Shimorina** [comment]
В викисловаре с одушевлённостью так же плохо, как и в подкорпусе нкря со снятой омонимией.

Неодушевленные божества: [1](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&dpp=&spp=&spd=&text=lexform&mode=main&sort=gr_tagging&lang=ru&nodia=1&req=%E1%EE%E6%E5%F1%F2%E2%E0&p=28&docid=20848&sid=8900), [2](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&dpp=&spp=&spd=&text=lexform&mode=main&sort=gr_tagging&lang=ru&nodia=1&req=%E1%EE%E6%E5%F1%F2%E2%E0&p=36&docid=67025&sid=6751), [3](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&dpp=&spp=&spd=&text=lexform&mode=main&sort=gr_tagging&lang=ru&nodia=1&req=%E1%EE%E6%E5%F1%F2%E2%E0&p=32&docid=46729&sid=164), [4](http://search1.ruscorpora.ru/search.xml?env=alpha&mycorp=&mysent=&mysize=&mysentsize=&mydocsize=&dpp=&spp=&spd=&text=lexform&mode=main&sort=gr_tagging&lang=ru&nodia=1&req=%E1%EE%E6%E5%F1%F2%E2%E0&p=22&docid=40268&sid=79).

**Comment by bzaar** [comment]
Спасибо, убедили. Т.е. неодушевленные божества - это что-то вроде кукол, болванок, памятников "настоящим" божествам.

Кстати, в статье [робот](http://opencorpora.org/dict.php?act=edit&id=308075) пишет:

> Ошибка. Несовместимые граммемы: <робот> (anim|inan).
> Ошибка. Несовместимые граммемы: <роботы> (anim|inan).

Возможно, стоит разбить на две.

То же самое в статье [кукла](http://opencorpora.org/dict.php?act=edit&id=144603).

Статей "светило" у вас две - порядок.

**Comment by Shimorina** [comment]
В обоих случаях дальше написано "эта ошибка была помечена как исключение". Слова с пометой Inmx, которые могут равно употребляться по одушевленному и по неодушевленному варианту, слиты в одну статью. См. также в самом конце [этой инструкции](http://opencorpora.org/wiki/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F_anim_inan).

**Comment by grandsbor** [comment]
Ок
