### ISSUE TITLE
изменить граммемы у пула 269 в поиске примеров

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#836]
Сейчас пул [269](http://opencorpora.org/pools.php?act=candidates&pool_type=269) это NOUN&nomn@NOUN&gent@NOUN&accs, и туда попадают примеры на ед. / мн. ч.
Надо добавить граммему sing, чтобы было NOUN&nomn&sing@NOUN&gent&sing@NOUN&accs&sing

**Comment by grandsbor** [comment]
Сделал
