### ISSUE TITLE
Заменить лемму у отчеств

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#845]
(из [#812](https://github.com/OpenCorpora/opencorpora/issues/812))

Заменить лемму у всех отчеств, где лемма не равняется форме sing,nomn (таких ~ 1000 шт.).

Сейчас: лемма [прокофиевна](http://opencorpora.org/dict.php?act=edit&id=281069)
Надо: лемма прокоф**ь**евна

**Comment by grandsbor** [comment]
Может, надо и граммемы переставить? То есть из "нейтральная форма _прокофиевна_ + пачка форм с `V-be`" сделать "нейтральная форма _прокофьевна_ + пачка форм с `V-ie`".

**Comment by Shimorina** [comment]
так оно вроде сейчас и есть так, как ты предлагаешь

**Comment by grandsbor** [comment]
А, действительно, пардон

**Comment by grandsbor** [comment]
done

**Comment by grandsbor** [comment]
В нескольких местах стало хуже:
http://opencorpora.org/dict.php?act=edit&id=6784
http://opencorpora.org/dict.php?act=edit&id=68798
http://opencorpora.org/dict.php?act=edit&id=83976

Возможно, ещё есть
