### ISSUE TITLE
Устроить проверку слов, написанных с заглавной буквы, но без тегов имён собственных

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#856]

**Comment by Shimorina** [comment]
Я это сделала этой осенью. Если подробно, то:

- собрала в корпусе все слова, начинающиеся с заглавной буквы и не имеющие тегов Name, Geox, Surn, Orgn или Abbr, за исключением первого слова предложения и за исключением слов, написанных кэпслоком;

- просмотрела список и либо исправляла словарь, либо делала такие токены unk, если редко в корпусе встречается.

**Comment by grandsbor** [comment]
Круто, спасибо!
