### ISSUE TITLE
удалить Qual у компаративов

### ISSUE THREAD

**Issue by grandsbor** [OpenCorpora/opencorpora#859]
надзорнее http://opencorpora.org/dict.php?act=edit&id=168842
курортнее http://opencorpora.org/dict.php?act=edit&id=145445
шатуннее http://opencorpora.org/dict.php?act=edit&id=378499

**Comment by Shimorina** [comment]
Видимо, это какая-то новая проблема, полгода назад всё нормально удалялось у компаративов.

Ещё:
http://opencorpora.org/dict.php?act=edit&id=287359
http://opencorpora.org/dict.php?act=edit&id=347846
http://opencorpora.org/dict.php?act=edit&id=82580
http://opencorpora.org/dict.php?act=edit&id=376707
http://opencorpora.org/dict.php?act=edit&id=368525

**Comment by grandsbor** [comment]
Удаление починил, осталось собственно удалить :)
