### ISSUE TITLE
Не получается заменить Е на Ё в лемме

### ISSUE THREAD

**Issue by victorbocharov** [OpenCorpora/opencorpora#860]
Например, здесь:
http://opencorpora.org/dict.php?act=edit&id=139918

При нажатии "Сохранить" говорит, что сохранилось, но, на самом деле, сохранения не произошло.

Другие изменения текста леммы срабатывают:
http://opencorpora.org/dict_history.php?lemma_id=139918

**Comment by Shimorina** [comment]
Дубликат https://github.com/OpenCorpora/opencorpora/issues/832

Интересно, после твоего теста там вдруг появилось ё

**Comment by victorbocharov** [comment]
закрываю, т.к. дубликат
