### ISSUE TITLE
Словарные правки, предложенные юзерами, не уходят на переразбор

### ISSUE THREAD

**Issue by Shimorina** [OpenCorpora/opencorpora#866]
Правки и новые слова, предложенные юзерами в словарь, не появляются в разделе "[Токены, которые надо переразобрать](http://opencorpora.org/dict.php?act=pending)".
Например, [смог](http://opencorpora.org/dict.php?act=edit&id=392899).

**Comment by grandsbor** [comment]
Новые правки должны начать уходить. Имеющиеся попробую руками запихать

**Comment by grandsbor** [comment]
Старые поставил в очередь
