### ISSUE TITLE
Задача NLP: извлечение санскритских имен собственных

### ISSUE THREAD

**Issue by evgeniarubanova** [OpenCorpora/opencorpora#867]
Добрый день! Меня зовут Женя, я пишу дипломную работу, одной из задач которой является **извлечение санскритских имен собственных** (н-р., "_вайшампаяны_", "_Кала_", "_вед_") из русского текста (Махабхараты) и их лемматизирование. На данный момент мне удалось извлечь бОльшую их часть с помощью проверки на вхождение в словарь Зализняка и Ефремовой. Для лемматизации использую Deeppavlov (pymorphy2 справляется хуже), дает точность (именно этих слов) 47%, род определяет с точностью в 75%.

Может быть, вы знаете какие-то инструменты, которые могут быть полезны в данной задаче? Заранее спасибо за ответ!

**Comment by grandsbor** [comment]
Я не знаю.
@svbichineva @Shimorina Может, вы что-то знаете?

**Comment by svbichineva** [comment]
Я тоже не знаю. Единственное, в pymorphy2 по умолчанию скорее всего стоит наш старый словарь, его как-то можно обновить до последней версии. @Shimorina, расскажи как.

**Comment by Shimorina** [comment]
У меня тоже нет идей. Про словарь, например, написано [тут](https://github.com/kmike/pymorphy2/issues/119#issuecomment-487391716).

**Comment by Shimorina** [comment]
@evgeniarubanova Ещё можно спросить ваш вопрос в телеграм-чате по NLP: https://telegram.me/natural_language_processing
Там много народу
