### ISSUE TITLE
Ошибочная связь великомученический -> великонек (ADJF-ADJS) 

### ISSUE THREAD

**Issue by tuffnatty** [OpenCorpora/opencorpora#869]
Без комментариев

**Comment by grandsbor** [comment]
Спасибо, завтра уйдёт.
А вы их случайно нашли или как-то систематически?

**Comment by tuffnatty** [comment]
@grandsbor Ну, грубо говоря, я собираю гнездо связанных лемм в одну парадигму и пытаюсь отрезать у нее максимальный общий префикс, и помимо системных девиаций с префиксами "наи-" и "по-" на поверхность вылезают отдельные несистемные
