### ISSUE TITLE
Несуществующие слова

### ISSUE THREAD

**Issue by tuffnatty** [OpenCorpora/opencorpora#872]
анатрлий
Связи:
    анатрлий -> анатрльевич (NAME-PATR)
    анатрлий -> анатрльевна (NAME-PATR)

Это явная (распространенная) опечатка, а не орфографический вариант.

**Comment by Shimorina** [comment]
У этих слов есть помета Erro (опечатка): http://opencorpora.org/dict.php?act=gram

**Comment by tuffnatty** [comment]
А, прошу прощения, не обратил внимания, учту

**Comment by tuffnatty** [comment]
И все же, кажется, от таких помет на уровне леммы сейчас не очень много толку - полезно было бы добавить (впридачу к помете) вид связи "NORM-FREQUENT_TYPO" и связи между опечатками и правильными написаниями.

**Comment by Shimorina** [comment]
Хм, недавно мы с @svbichineva решили, что будем добавлять такие случаи в связь NORM-ORPHOVAR: http://opencorpora.org/dict.php?act=links&type=22 , так как иногда сложно разграничить опечатку от орфоварианта.
