### ISSUE TITLE
Морфологический словарь

### ISSUE THREAD

**Issue by dimatyurin** [OpenCorpora/opencorpora#900]
1) объедините одним идентификатором все формы одного глагола - личные формы, _инфинитив_, причастия, деепричастия
2) сделайте дубликат словаря, в котором грамматические категории указаны не на английском, а на русском - это позволит привлечь к его проверке несравненно более широкие массы населения
3) сделайте вывод не только в xml, но и в эксельном формате - опять же чтобы работать с ними могли простые пользователи с установленным мс-офисом на компе. В эксельном формате выведите, пожалуйста, в 3-й нормальной форме, т.е. каждую грамматическую категорию в своей собственной колонке
4) добавьте в название словаря дату - что-то вроде opencorpora.full.2022.01.30.rus.xlsx
5) выводите разницы соседних версий словаря, чтобы пользователи  проверяли вручную не весь словарь заново, а только вновь появившиеся данные в словаре - что-то вроде opencorpora.new.2022.01.30.rus.xlsx

**Comment by dimatyurin** [comment]
пример https://cloud.mail.ru/public/GXwy/rHZxZYbiq

вот грубая предобработка вашего словаря /идентификатор словоформ не совпадают/
https://cloud.mail.ru/public/Ax3X/FrkUnRyqZ

**Comment by victorbocharov** [comment]
@bzaar спасибо за развёрнутый ответ

@dimatyurin мне кажется, что на сайте выложено всё необходимое для того, чтобы сделать всё то, о чём вы пишите. Поэтому вы можете сделать это самостоятельно. Сообщите, если каких-то данных нет.

По поводу пункта 2: редактирование словаря требует квалификации. С широкими массами не получается.
