### ISSUE TITLE
у ООО в словаре нет Abbr

### ISSUE THREAD

**Issue by kmike** [OpenCorpora/opencorpora#94]
Привет. Заметил, что у многих аббривеатур в словаре нет пометки Abbr. Примеры:
- ООО
- ЗАО
- РОВД
- РУВД
- ВМФ
- ВНИИ
- УФМС
- ФАПСИ
- ХМАО разбирается как `'NOUN,anim,masc,Sgtm,Fixd,Name sing,nomn'` - вместо Name надо бы Geox, ну и Abbr, наверное;

и т.д. - похоже, у большинства подобных слов пометки Abbr нет. Это так и задумывалось? В НКРЯ, насколько помню, такие слова как abbr помечаются.

Ну и так, заметил заодно, что еще ИП в словаре нет :)

Список подозрительных слов (не всех) можно получить так:

```
fixd_no_abbr = [
    p for p in m.iter_known_word_parses() 
    if 'Abbr' not in p.tag and 'Surn' not in p.tag and 'Geox' not in p.tag and 'Name' not in p.tag and {'NOUN', 'Fixd', 'nomn', 'sing'} in p.tag
]
```

**Comment by grandsbor** [comment]
Воспользовался Мишиным способом, получилось [больше тысячи слов](https://yadi.sk/i/DGFtO8ime6vNV). Кто-нибудь готов вычитать?

**Comment by svbichineva** [comment]
1000 не готова, могу наверное 100-150 самых частотных в корпусе

**Comment by kmike** [comment]
я готов 1000, но через месяц где-нибудь, не сейчас)

**Comment by grandsbor** [comment]
Вычитал и поправил букву А :)

**Comment by grandsbor** [comment]
Сделал буквы Б и В

**Comment by Shimorina** [comment]
Весь список исправлен. Пишите, если ещё что найдёте.
